// Hand-written bindings for methods not generated by applegen.
//
// This file should be removed once the generator handles these cases:
//
//   - AddOutput, StartReading, AddInput, StartWriting, IsReadyForMoreMediaData,
//     AppendSampleBuffer, CopyNextSampleBuffer, TracksWithMediaType: deprecated
//     at macOS 11.0 and filtered by --skip-deprecated=13.0 default.
//   - SetTrackID: trackID is read-only in Apple docs but writable via ObjC header.
//   - SetInputParameters: property setter not generated for AVMutableAudioMix.
//
// Note: config.yaml CMTime/CMTimeRange mapping is fixed (now uses coremedia types),
// and block typedef resolution is fixed (resolveTypedefForBlock called from
// parseBlockHandlerInfo). However, the generated coremedia.CMTime/CMTimeRange
// structs have extra fields from Apple docs scraping (Seconds, End) that make
// them ABI-incompatible with the real C structs. Examples using CMTime should
// define local structs with the correct layout until this is fixed.
package avfoundation

import (
	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objc"
)

// AddOutput adds an output to the asset reader.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetReader/add(_:)
func (a AVAssetReader) AddOutput(output IAVAssetReaderOutput) {
	objc.Send[objc.ID](a.ID, objc.Sel("addOutput:"), output)
}

// StartReading prepares the receiver for obtaining sample buffers from the
// asset and returns whether reading started successfully.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetReader/startReading()
func (a AVAssetReader) StartReading() bool {
	return objc.Send[bool](a.ID, objc.Sel("startReading"))
}

// AddInput adds an input to the asset writer.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetWriter/add(_:)-6al7j
func (a AVAssetWriter) AddInput(input IAVAssetWriterInput) {
	objc.Send[objc.ID](a.ID, objc.Sel("addInput:"), input)
}

// StartWriting prepares the receiver for accepting input and returns whether
// writing started successfully.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetWriter/startWriting()
func (a AVAssetWriter) StartWriting() bool {
	return objc.Send[bool](a.ID, objc.Sel("startWriting"))
}

// IsReadyForMoreMediaData reports whether the input can accept more media data.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetWriterInput/isReadyForMoreMediaData
func (a AVAssetWriterInput) IsReadyForMoreMediaData() bool {
	return objc.Send[bool](a.ID, objc.Sel("isReadyForMoreMediaData"))
}

// AppendSampleBuffer appends a sample buffer to the receiver.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetWriterInput/append(_:)
func (a AVAssetWriterInput) AppendSampleBuffer(sampleBuffer objc.ID) bool {
	return objc.Send[bool](a.ID, objc.Sel("appendSampleBuffer:"), sampleBuffer)
}

// CopyNextSampleBuffer copies the next sample buffer from the output.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAssetReaderOutput/copyNextSampleBuffer()
func (a AVAssetReaderOutput) CopyNextSampleBuffer() objc.ID {
	return objc.Send[objc.ID](a.ID, objc.Sel("copyNextSampleBuffer"))
}

// TracksWithMediaType returns tracks of the specified media type.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVAsset/tracks(withMediaType:)
func (a AVAsset) TracksWithMediaType(mediaType AVMediaType) []AVAssetTrack {
	rv := objc.Send[[]objc.ID](a.ID, objc.Sel("tracksWithMediaType:"),
		objc.String(string(mediaType)))
	return objc.ConvertSlice(rv, func(id objc.ID) AVAssetTrack {
		return AVAssetTrackFromID(id)
	})
}

// SetTrackID sets the track ID for the input parameters.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVMutableAudioMixInputParameters/trackID
func (m AVMutableAudioMixInputParameters) SetTrackID(trackID int32) {
	objc.Send[objc.ID](m.ID, objc.Sel("setTrackID:"), trackID)
}

// SetInputParameters sets the parameters for the audio mix's input tracks.
//
// See: https://developer.apple.com/documentation/AVFoundation/AVMutableAudioMix/inputParameters
func (m AVMutableAudioMix) SetInputParameters(params foundation.INSArray) {
	objc.Send[objc.ID](m.ID, objc.Sel("setInputParameters:"), params)
}
