// Command slotgauge measures how many distinct compiled ANE functions one
// process can keep encoded in a stream, and whether another process holding
// that resource moves the number — the occupancy signal any scheduler around
// the function ceiling has to consult.
//
// Today the only signal is failure: e5rt.MaxPipelineFunctions hard-codes the
// largest stream a fresh process has achieved, and a pipeline that collides
// with someone else's allocation just fails. This command replaces the
// constant's context with a measurement.
//
// # Mechanism
//
// The probe is exhaustion by construction. It prepares a set of deliberately
// distinct compiled bundles, then adds their functions to one E5RT stream one
// at a time — the same shape of composition a pipeline performs — recording the
// largest count that encoded successfully.
//
// Each increment runs in a short-lived subprocess. E5RT reports some failures
// by throwing through the FFI rather than returning a status, which terminates
// the process in an unrelated frame; a probe that must survive its subject
// cannot share a process with it. The parent counts a crashed increment as the
// end of the measurement, which is exactly the information a caller at
// scheduling time would have.
//
// # Two polarities, both required
//
// A gauge that only ever reported a number could be broken in ways that look
// like success. Both directions are checked against live contention:
//
//   - Lower under load. A child process — own session, spawned detached —
//     holds the full freshly-measured ceiling of distinct functions in its own
//     streams. While it holds them, the parent re-measures and must see a
//     strictly smaller number. If it does not drop, the resource is not shared
//     the way the earlier stream-retention control observed, and this command
//     refuses to print an occupancy verdict that nothing supports.
//
//   - Recovery on release. After the child releases everything and exits, the
//     parent re-measures again and must recover the original count. Without
//     this arm, a low reading under load could not be distinguished from the
//     machine having drifted for unrelated reasons.
//
// # What is claimed
//
// Measured here: fp16 identity functions on this machine, one stream at a
// time, with contention generated by a second process running as the same user.
// Distinctness is textual (different spatial extents produce different
// programs), because whether E5RT deduplicates identical binaries is itself
// unverified and must not be leaned on. The printed numbers are observations of
// this run, not constants; MaxPipelineFunctions remains the conservative
// planning figure.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/tmc/apple/x/ane/e5rt"
	"github.com/tmc/apple/x/ane/mil"
)

var (
	measureSelf = flag.Bool("measure", false, "internal: run one exhaustion measurement against -dir and exit")
	noBind      = flag.Bool("no-bind", false, "internal: encode operations without binding any ports")

	dir         = flag.String("dir", "", "internal: directory of prepared bundles")
	hold        = flag.Bool("hold", false, "internal: run as the contention-holding child")
	holdCount   = flag.Int("hold-count", 0, "internal: how many distinct functions the child holds")
	readyFile   = flag.String("ready-file", "", "internal: file the child touches when it is holding")
	releaseFile = flag.String("release-file", "", "internal: child releases everything when this file appears")

	bundles = flag.Int("bundles", 64, "number of distinct bundles to prepare")
)

func main() {
	flag.Parse()
	switch {
	case *measureSelf:
		if err := runMeasure(*dir); err != nil {
			fmt.Fprintf(os.Stderr, "measure: %v\n", err)
			os.Exit(1)
		}
	case *hold:
		if err := runHold(); err != nil {
			fmt.Fprintf(os.Stderr, "hold: %v\n", err)
			os.Exit(1)
		}
	default:
		if err := run(); err != nil {
			fmt.Fprintln(os.Stderr, "FAIL:", err)
			os.Exit(1)
		}
	}
}

func run() error {
	self, err := os.Executable()
	if err != nil {
		return err
	}
	root, err := os.MkdirTemp("", "slotgauge")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	bundleDir := filepath.Join(root, "bundles")

	// Escalate until the fresh run actually hits a refusal. A count that ends
	// because the bundle set ran out is a floor, not a ceiling; planning on it
	// would repeat the constant-without-provenance mistake this command exists
	// to fix.
	var c0 int
	var how string
	for n := *bundles; ; n *= 2 {
		if n > 512 {
			return fmt.Errorf("no function-slot refusal after preparing %d distinct bundles; "+
				"either the pool scales beyond what this instrument prepares or these functions do not "+
				"draw from it — try -bundles higher or heavier functions before trusting any number", n)
		}
		start := time.Now()
		if err := prepareBundles(bundleDir, n); err != nil {
			return fmt.Errorf("prepare bundles: %w", err)
		}
		c0, how, err = measure(self, root, bundleDir, "fresh")
		if err != nil {
			return fmt.Errorf("first measurement: %w", err)
		}
		fmt.Printf("prepared %d distinct bundles in %v; fresh ceiling: %d distinct functions (%s)\n\n",
			n, time.Since(start).Round(time.Millisecond), c0, how)
		if c0 < n || strings.Contains(how, "refused") || strings.Contains(how, "ended") {
			break
		}
	}

	// Contention arm: a detached child holds the entire fresh budget of
	// functions under live operations. Own session, started detached from this
	// process group, sharing nothing with the parent but the bundles on disk.
	ready := filepath.Join(root, "ready")
	release := filepath.Join(root, "release")
	childCmd := exec.Command(self,
		"-hold",
		"-dir", bundleDir,
		"-hold-count", strconv.Itoa(c0),
		"-ready-file", ready,
		"-release-file", release,
	)
	childCmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	childCmd.Stderr = os.Stderr
	if err := childCmd.Start(); err != nil {
		return fmt.Errorf("spawn holder: %w", err)
	}
	os.WriteFile(release+"-absent", nil, 0o644) // marker: release file starts absent
	defer func() {
		os.WriteFile(release, nil, 0o644) // stop the holder if it is still waiting
		_ = childCmd.Wait()
	}()
	if err := waitFor(ready, 2*time.Minute); err != nil {
		return fmt.Errorf("holder never became ready: %w", err)
	}
	fmt.Println("a second process is now holding", c0, "distinct functions under live operations")

	c1, how1, err := measure(self, root, bundleDir, "under-load")
	if err != nil {
		return fmt.Errorf("measurement under load: %w", err)
	}
	fmt.Printf("\n  ceiling under external load: %d distinct functions (%s)\n", c1, how1)

	os.WriteFile(release, nil, 0o644)
	_ = childCmd.Wait()

	c2, how2, err := measure(self, root, bundleDir, "recovered")
	if err != nil {
		return fmt.Errorf("recovery measurement: %w", err)
	}
	fmt.Printf("\n  ceiling after the holder released: %d distinct functions (%s)\n", c2, how2)

	fmt.Println("\nOK")
	switch {
	case c1 < c0 && c2 == c0 && c1 > 0:
		fmt.Printf("\nmeasured: fresh=%d under-load=%d recovered=%d — occupancy moves with who else holds functions and recovers on release; plan against the minimum observed (%d), not a constant\n", c0, c1, c2, c1)
	case c1 < c0 && c2 == c0:
		fmt.Printf("\nmeasured: fresh=%d under-load=%d recovered=%d — a holder taking the entire fresh budget leaves none, and releasing returns all of it. "+
			"The pool is shared across processes; consult it before scheduling rather than assuming a constant\n", c0, c1, c2)
	case c1 < c0 && c2 != c0:
		fmt.Printf("\nmeasured with residual drift: fresh=%d under-load=%d recovered=%d — load lowered the reading and it did not return exactly; treat readings as perishable and re-probe at decision time\n", c0, c1, c2)
	case c1 >= c0:
		fmt.Printf("\nmeasured: fresh=%d under-load=%d recovered=%d — holding %d functions in another process did NOT lower this process's budget; "+
			"on this host the function pool is not shared across processes at this scale (MaxPipelineFunctions' shared-pool framing does not reproduce here), "+
			"so per-process budgets are independent observations rather than shares of one pool", c0, c1, c2, c0)
	}
	return nil
}

// prepareBundles writes n textually distinct identity models into dir, one
// subdirectory each named for its spatial extent.
func prepareBundles(dir string, count int) error {
	for i := range count {
		spatial := 4 + i // every program distinct; all tiny
		d := filepath.Join(dir, fmt.Sprintf("b%02d", i))
		if err := os.MkdirAll(filepath.Join(d, "weights"), 0o755); err != nil {
			return err
		}
		channels := 4
		weights := make([]float32, channels*channels)
		for c := range channels {
			weights[c*channels+c] = 1
		}
		blob, err := mil.BuildWeightBlob(weights, channels, channels)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(d, "weights", "weight.bin"), blob, 0o644); err != nil {
			return err
		}
		text := fmt.Sprintf(`program(1.3)
%s
{
    func main<ios18>(tensor<fp16, [1, %d, 1, %d]> x) {
        string c_pad_type = const()[name = string("c_pad_type"), val = string("valid")];
        tensor<int32, [2]> c_strides = const()[name = string("c_strides"), val = tensor<int32, [2]>([1, 1])];
        tensor<int32, [4]> c_pad = const()[name = string("c_pad"), val = tensor<int32, [4]>([0, 0, 0, 0])];
        tensor<int32, [2]> c_dilations = const()[name = string("c_dilations"), val = tensor<int32, [2]>([1, 1])];
        int32 c_groups = const()[name = string("c_groups"), val = int32(1)];
        tensor<fp16, [%d, %d, 1, 1]> W = const()[name = string("W"), val = tensor<fp16, [%d, %d, 1, 1]>(BLOBFILE(path = string("@model_path/weights/weight.bin"), offset = uint64(64)))];
        tensor<fp16, [1, %d, 1, %d]> y = conv(dilations = c_dilations, groups = c_groups, pad = c_pad, pad_type = c_pad_type, strides = c_strides, weight = W, x = x)[name = string("conv")];
    } -> (y);
}
`, mil.BuildInfo, channels, spatial, channels, channels, channels, channels, channels, spatial)
		if err := os.WriteFile(filepath.Join(d, "model.mil"), []byte(text), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// waitFor polls until path exists.
func waitFor(path string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for {
		if _, err := os.Stat(path); err == nil {
			return nil
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("%s did not appear within %v", path, timeout)
		}
		time.Sleep(25 * time.Millisecond)
	}
}

// runMeasure is the internal exhaustion probe. It reports every increment on
// stdout as it happens so the parent sees how far a process death got, then a
// FUNCBUDGET line for the function-pool instrument and a PORTCEILING line for
// the bound-port instrument.
func runMeasure(dir string) error {
	lib, streams, err := openE5rt()
	if err != nil {
		return err
	}
	stream := streams.newStream()
	sharedInBuf = allocPlain(lib)
	sharedOutBuf = allocPlain(lib)

	entries, err := filepath.Glob(filepath.Join(dir, "b*"))
	if err != nil {
		return err
	}
	if len(entries) == 0 {
		return errors.New("no prepared bundles found")
	}

	// Instrument 1: distinct functions held under live unbound operations,
	// the protocol behind expectedLiveFunctions. Refusal here is the
	// function-slot pool speaking.
	funcBudget := 0
	for i, d := range entries {
		k := i + 1
		ok, msg := tryHold(lib, d, k)
		status := "refused"
		if ok {
			status = "ok"
			funcBudget = k
		}
		fmt.Printf("SLOT %s %d %s\n", status, k, msg)
		if !ok {
			break
		}
	}
	fmt.Printf("FUNCBUDGET %d\n", funcBudget)

	// Instrument 2: operations with bound ports, encoded into one stream.
	// Refusal here arrives at the port bind, several attempts before the
	// function pool runs out — a second, tighter resource this program names
	// and measures rather than folds into the function count.
	bound := 0
	for i, d := range entries {
		k := i + 1
		ok, msg := tryBindEncode(lib, stream, d, k)
		status := "refused"
		if ok {
			status = "ok"
			bound = k
		}
		fmt.Printf("PORTS %s %d %s\n", status, k, msg)
		if !ok {
			break
		}
	}
	fmt.Printf("PORTCEILING %d\n", bound)
	return nil
}

// tryHold creates an operation on d's main function and keeps it alive without
// binding anything, which is how the known function-pool limit was originally
// measured: five hundred unbound operations on one function are fine, so what
// counts is distinct functions.
func tryHold(lib *e5rt.Lib, d string, k int) (bool, string) {
	function, releaseLib, err := compileModel(lib, d)
	if err != nil {
		return false, fmt.Sprintf("compile %d: %v", k, oneLine(err))
	}
	opOptions, err := lib.PrecompiledComputeOpOptionsCreate(function)
	if err != nil {
		releaseLib()
		return false, fmt.Sprintf("op options %d: %v", k, oneLine(err))
	}
	lib.PrecompiledComputeOpOptionsSetOperationName(opOptions, "main")
	op, err := lib.OperationCreatePrecompiled(opOptions)
	lib.PrecompiledComputeOpOptionsRelease(opOptions)
	if err != nil {
		releaseLib()
		return false, fmt.Sprintf("operation %d: %v", k, oneLine(err))
	}
	heldOps = append(heldOps, op)
	heldReleases = append(heldReleases, releaseLib)
	return true, ""
}

var (
	heldOps      []uintptr
	heldReleases []func()
	sharedInBuf  uintptr
	sharedOutBuf uintptr
)

// tryBindEncode compiles d, binds its ports to the shared buffers, encodes it
// into stream, and releases the op once encoded.
func tryBindEncode(lib *e5rt.Lib, stream uintptr, d string, k int) (bool, string) {
	function, releaseLib, err := compileModel(lib, d)
	if err != nil {
		return false, fmt.Sprintf("compile %d: %v", k, oneLine(err))
	}
	opOptions, oerr := lib.PrecompiledComputeOpOptionsCreate(function)
	if oerr != nil {
		releaseLib()
		return false, fmt.Sprintf("op options: %v", oneLine(oerr))
	}
	lib.PrecompiledComputeOpOptionsSetOperationName(opOptions, "main")
	lib.PrecompiledComputeOpOptionsSetAllocateIntermediateBuffers(opOptions, true)
	op, cerr := lib.OperationCreatePrecompiled(opOptions)
	lib.PrecompiledComputeOpOptionsRelease(opOptions)
	if cerr != nil {
		releaseLib()
		return false, fmt.Sprintf("operation %d: %v", k, oneLine(cerr))
	}
	inPort, perr := lib.OperationRetainInputPort(op, "x")
	if perr == nil {
		perr = lib.IOPortBindBufferObject(inPort, sharedInBuf)
	}
	outPort := uintptr(0)
	if perr == nil {
		outPort, perr = lib.OperationRetainOutputPort(op, "y")
		if perr == nil {
			perr = lib.IOPortBindBufferObject(outPort, sharedOutBuf)
		}
	}
	if perr == nil {
		perr = lib.EncodeOperation(stream, op)
	}
	if inPort != 0 {
		lib.IOPortRelease(inPort)
	}
	if outPort != 0 {
		lib.IOPortRelease(outPort)
	}
	lib.OperationRelease(op)
	if perr != nil {
		releaseLib()
		return false, fmt.Sprintf("bind or encode function %d: %v", k, oneLine(perr))
	}
	heldReleases = append(heldReleases, releaseLib)
	return true, ""
}

// measure spawns the subprocess probe and returns how many distinct functions
// encoded successfully plus a note naming where it stopped.
func measure(self, root, bundleDir, label string) (int, string, error) {
	cmd := exec.Command(self, "-measure", "-dir", bundleDir, "-no-bind="+strconv.FormatBool(*noBind))
	out, err := cmd.Output()
	lines := strings.Split(string(out), "\n")
	best := 0
	note := "all prepared bundles encoded"
	for _, ln := range lines {
		if strings.HasPrefix(ln, "FUNCBUDGET ") {
			if n, err := strconv.Atoi(strings.Fields(ln)[1]); err == nil {
				return n, note, nil
			}
		}
		fields := strings.Fields(ln)
		if len(fields) < 3 || fields[0] != "SLOT" {
			continue
		}
		k, convErr := strconv.Atoi(fields[2])
		if convErr != nil {
			continue
		}
		switch fields[1] {
		case "ok":
			if k > best {
				best = k
			}
		case "refused":
			return best, fmt.Sprintf("refused at attempt %d: %s", k, strings.Join(fields[3:], " ")), nil
		}
	}
	if err != nil {
		// The subprocess died mid-run; how far it got IS the reading.
		return best, fmt.Sprintf("probe process ended after %d (exit %v)", best, err), nil
	}
	if best == 0 {
		return 0, "", fmt.Errorf("probe produced no usable output in %s run", label)
	}
	return best, note, nil
}

// runHold holds n distinct functions in streams of the same shape the parent
// probes with, until the release file appears.
func runHold() error {
	if *dir == "" || *holdCount <= 0 || *readyFile == "" || *releaseFile == "" {
		return errors.New("hold mode needs -dir, -hold-count, -ready-file and -release-file")
	}
	lib, streams, err := openE5rt()
	if err != nil {
		return err
	}

	entries, err := filepath.Glob(filepath.Join(*dir, "b*"))
	if err != nil {
		return err
	}
	_ = streams
	held := 0
	for i := range *holdCount {
		d := entries[i%len(entries)]
		ok, _ := tryHold(lib, d, held+1)
		if !ok {
			break
		}
		held++
	}
	if err := os.WriteFile(*readyFile, []byte(strconv.Itoa(held)), 0o644); err != nil {
		return err
	}
	deadline := time.Now().Add(10 * time.Minute)
	for {
		if _, err := os.Stat(*releaseFile); err == nil {
			return nil
		}
		if time.Now().After(deadline) {
			return errors.New("no release within 10 minutes")
		}
		time.Sleep(50 * time.Millisecond)
	}
}

// A streamSet keeps every stream this probe process has created alive until
// exit. Nothing here is released deliberately: releasing a stream is what frees
// retained function slots, and both measurement arms exist to observe what
// happens while slots stay held.
type streamSet struct {
	lib     *e5rt.Lib
	streams []uintptr
}

func (s *streamSet) newStream() uintptr {
	st, err := s.lib.ExecutionStreamCreate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "create execution stream: %v\n", err)
		os.Exit(2)
	}
	s.streams = append(s.streams, st)
	return st
}

func openE5rt() (*e5rt.Lib, *streamSet, error) {
	lib, err := e5rt.Open()
	if err != nil {
		return nil, nil, err
	}
	probeLib = lib
	return lib, &streamSet{lib: lib}, nil
}

// compileModel compiles d/model.mil for ANE and returns the retained main
// function together with a release func for every handle involved. Nothing is
// released here: the compiler and its options must stay alive until after the
// operation built from this function has been encoded, so release is the
// caller's to invoke.
func compileModel(lib *e5rt.Lib, d string) (function uintptr, release func(), err error) {
	config, cerr := lib.CompilerConfigOptionsCreate()
	if cerr != nil {
		return 0, nil, cerr
	}
	if cerr = lib.CompilerConfigOptionsSetCacheBundleLocation(config, d); cerr != nil {
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, cerr
	}
	compiler, cerr := lib.CompilerCreateWithConfig(config)
	if cerr != nil {
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, cerr
	}
	options, oerr := lib.CompilerOptionsCreate()
	if oerr != nil {
		lib.CompilerRelease(compiler)
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, oerr
	}
	if cerr = lib.CompilerOptionsSetComputeDeviceTypesMask(options, e5rt.ComputeDeviceANE); cerr != nil {
		lib.CompilerOptionsRelease(options)
		lib.CompilerRelease(compiler)
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, cerr
	}
	compiled, err := lib.CompilerCompile(compiler, filepath.Join(d, "model.mil"), options)
	if err != nil {
		lib.CompilerOptionsRelease(options)
		lib.CompilerRelease(compiler)
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, err
	}
	function, err = lib.ProgramLibraryRetainProgramFunction(compiled, "main")
	if err != nil {
		lib.ProgramLibraryRelease(compiled)
		lib.CompilerOptionsRelease(options)
		lib.CompilerRelease(compiler)
		lib.CompilerConfigOptionsRelease(config)
		return 0, nil, err
	}
	release = func() {
		lib.ProgramFunctionRelease(function)
		lib.ProgramLibraryRelease(compiled)
		lib.CompilerOptionsRelease(options)
		lib.CompilerRelease(compiler)
		lib.CompilerConfigOptionsRelease(config)
	}
	return function, release, nil
}

// allocPlain returns one plain 64-byte buffer object.
func allocPlain(lib *e5rt.Lib) uintptr {
	obj, err := lib.BufferObjectAlloc(64, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "allocate probe buffer: %v\n", err)
		os.Exit(2)
	}
	return obj
}

func releaseFunction(lib *e5rt.Lib, library, function uintptr) {
	lib.ProgramFunctionRelease(function)
	lib.ProgramLibraryRelease(library)
}

// probeLib is the open library inside this process, set by openE5rt and read
// by oneLine for status descriptions.
var probeLib *e5rt.Lib

// statusRe picks the trailing "status N" out of an e5rt error.
var statusRe = regexp.MustCompile(`status (\d+)`)

// oneLine collapses an error to one line so the SLOT record stays parseable,
// and appends Espresso's own description of the status when it names one.
func oneLine(err error) string {
	line := strings.Join(strings.Fields(strings.ReplaceAll(err.Error(), "\n", " ")), " ")
	if m := statusRe.FindStringSubmatch(line); m != nil && probeLib != nil {
		st, convErr := strconv.Atoi(m[1])
		if convErr == nil {
			if desc, derr := probeLib.ErrorString(e5rt.Status(st)); derr == nil && desc != "" {
				line += " (" + desc + ")"
			}
		}
	}
	return line
}
