// Code generated by gen/gentable.go from opschema.json. DO NOT EDIT.

// coremltools 9.0 (d64f1cfcb117d4279e8c0c9241b395cbf46401d0)

package opschema

var opsets = map[string]map[string]*Op{
	"ios15": {
		"abs": {Type: "abs", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"add": {Type: "add", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"cast": {Type: "cast", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "dtype", Kind: KindTensor, Const: true, Domain: []DataType{"string"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"concat": {Type: "concat", Params: []Param{
			{Name: "values", Kind: KindTuple},
			{Name: "axis", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
			{Name: "interleave", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}},
		"const": {Type: "const", Params: []Param{
			{Name: "val", Kind: KindInternal, Const: true},
		}},
		"conv": {Type: "conv", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "weight", Kind: KindTensor, DomainID: "T"},
			{Name: "bias", Kind: KindTensor, Const: true, Optional: true, DomainID: "T"},
			{Name: "strides", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "pad_type", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"string"}},
			{Name: "pad", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "dilations", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "groups", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"matmul": {Type: "matmul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
			{Name: "transpose_x", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
			{Name: "transpose_y", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"maximum": {Type: "maximum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"mul": {Type: "mul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"pow": {Type: "pow", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"real_div": {Type: "real_div", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_max": {Type: "reduce_max", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_mean": {Type: "reduce_mean", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_sum": {Type: "reduce_sum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"relu": {Type: "relu", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"reshape": {Type: "reshape", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "shape", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"sigmoid": {Type: "sigmoid", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"slice_by_size": {Type: "slice_by_size", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "begin", Kind: KindTensor, Domain: []DataType{"int32"}},
			{Name: "size", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"softmax": {Type: "softmax", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axis", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"sqrt": {Type: "sqrt", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"square": {Type: "square", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"sub": {Type: "sub", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"tile": {Type: "tile", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "reps", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"transpose": {Type: "transpose", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "perm", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
	},
	"ios16": {
		"abs": {Type: "abs", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"add": {Type: "add", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"cast": {Type: "cast", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "dtype", Kind: KindTensor, Const: true, Domain: []DataType{"string"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"concat": {Type: "concat", Params: []Param{
			{Name: "values", Kind: KindTuple},
			{Name: "axis", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
			{Name: "interleave", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}},
		"const": {Type: "const", Params: []Param{
			{Name: "val", Kind: KindInternal, Const: true},
		}},
		"conv": {Type: "conv", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "weight", Kind: KindTensor, DomainID: "T"},
			{Name: "bias", Kind: KindTensor, Const: true, Optional: true, DomainID: "T"},
			{Name: "strides", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "pad_type", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"string"}},
			{Name: "pad", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "dilations", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "groups", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"matmul": {Type: "matmul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
			{Name: "transpose_x", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
			{Name: "transpose_y", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"maximum": {Type: "maximum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"mul": {Type: "mul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"pow": {Type: "pow", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"real_div": {Type: "real_div", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_max": {Type: "reduce_max", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_mean": {Type: "reduce_mean", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_sum": {Type: "reduce_sum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"relu": {Type: "relu", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"reshape": {Type: "reshape", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "shape", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"sigmoid": {Type: "sigmoid", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"slice_by_size": {Type: "slice_by_size", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "begin", Kind: KindTensor, Domain: []DataType{"int32"}},
			{Name: "size", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"softmax": {Type: "softmax", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axis", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"sqrt": {Type: "sqrt", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"square": {Type: "square", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"sub": {Type: "sub", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"tile": {Type: "tile", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "reps", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"transpose": {Type: "transpose", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "perm", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
	},
	"ios17": {
		"abs": {Type: "abs", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"add": {Type: "add", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"cast": {Type: "cast", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "dtype", Kind: KindTensor, Const: true, Domain: []DataType{"string"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "uint8", "int16", "uint16", "int32", "bool"},
		}},
		"concat": {Type: "concat", Params: []Param{
			{Name: "values", Kind: KindTuple},
			{Name: "axis", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
			{Name: "interleave", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}},
		"const": {Type: "const", Params: []Param{
			{Name: "val", Kind: KindInternal, Const: true},
		}},
		"conv": {Type: "conv", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "weight", Kind: KindTensor, DomainID: "U"},
			{Name: "bias", Kind: KindTensor, Optional: true, DomainID: "U"},
			{Name: "strides", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "pad_type", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"string"}},
			{Name: "pad", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "dilations", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "groups", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
			"U": []DataType{"fp16", "fp32"},
		}},
		"matmul": {Type: "matmul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "U"},
			{Name: "transpose_x", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
			{Name: "transpose_y", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
			"U": []DataType{"fp16", "fp32", "int32"},
		}},
		"maximum": {Type: "maximum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"mul": {Type: "mul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"pow": {Type: "pow", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"real_div": {Type: "real_div", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_max": {Type: "reduce_max", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_mean": {Type: "reduce_mean", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_sum": {Type: "reduce_sum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"relu": {Type: "relu", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"reshape": {Type: "reshape", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "shape", Kind: KindTensor, DomainID: "U"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "uint8", "int16", "uint16", "int32", "bool"},
			"U": []DataType{"int8", "int16", "int32"},
		}},
		"sigmoid": {Type: "sigmoid", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"slice_by_size": {Type: "slice_by_size", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "begin", Kind: KindTensor, DomainID: "U"},
			{Name: "size", Kind: KindTensor, DomainID: "U"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "int16", "int32", "uint8", "uint16", "bool"},
			"U": []DataType{"int8", "int16", "int32"},
		}},
		"softmax": {Type: "softmax", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axis", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"sqrt": {Type: "sqrt", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"square": {Type: "square", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"sub": {Type: "sub", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"tile": {Type: "tile", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "reps", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"transpose": {Type: "transpose", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "perm", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "int16", "int32", "uint8", "uint16", "bool"},
		}},
	},
	"ios18": {
		"abs": {Type: "abs", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"add": {Type: "add", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"cast": {Type: "cast", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "dtype", Kind: KindTensor, Const: true, Domain: []DataType{"string"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "uint8", "int16", "uint16", "int32", "bool"},
		}},
		"concat": {Type: "concat", Params: []Param{
			{Name: "values", Kind: KindTuple},
			{Name: "axis", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
			{Name: "interleave", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}},
		"const": {Type: "const", Params: []Param{
			{Name: "val", Kind: KindInternal, Const: true},
		}},
		"conv": {Type: "conv", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "weight", Kind: KindTensor, DomainID: "U"},
			{Name: "bias", Kind: KindTensor, Optional: true, DomainID: "U"},
			{Name: "strides", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "pad_type", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"string"}},
			{Name: "pad", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "dilations", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "groups", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
			"U": []DataType{"fp16", "fp32"},
		}},
		"matmul": {Type: "matmul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "U"},
			{Name: "transpose_x", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
			{Name: "transpose_y", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
			"U": []DataType{"fp16", "fp32", "int32"},
		}},
		"maximum": {Type: "maximum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"mul": {Type: "mul", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"pow": {Type: "pow", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"read_state": {Type: "read_state", Params: []Param{
			{Name: "input", Kind: KindState},
		}},
		"real_div": {Type: "real_div", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_max": {Type: "reduce_max", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_mean": {Type: "reduce_mean", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"reduce_sum": {Type: "reduce_sum", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axes", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
			{Name: "keep_dims", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"bool"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"relu": {Type: "relu", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"reshape": {Type: "reshape", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "shape", Kind: KindTensor, DomainID: "U"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "uint8", "int16", "uint16", "int32", "bool"},
			"U": []DataType{"int8", "int16", "int32"},
		}},
		"scaled_dot_product_attention": {Type: "scaled_dot_product_attention", Params: []Param{
			{Name: "query", Kind: KindTensor, DomainID: "T"},
			{Name: "key", Kind: KindTensor, DomainID: "T"},
			{Name: "value", Kind: KindTensor, DomainID: "T"},
			{Name: "attn_mask", Kind: KindTensor, Optional: true, DomainID: "M"},
		}, Domains: map[string][]DataType{
			"M": []DataType{"bool", "fp16", "fp32"},
			"T": []DataType{"fp16", "fp32"},
		}},
		"sigmoid": {Type: "sigmoid", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"slice_by_size": {Type: "slice_by_size", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "begin", Kind: KindTensor, DomainID: "U"},
			{Name: "size", Kind: KindTensor, DomainID: "U"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "int16", "int32", "uint8", "uint16", "bool"},
			"U": []DataType{"int8", "int16", "int32"},
		}},
		"softmax": {Type: "softmax", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "axis", Kind: KindTensor, Const: true, Optional: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"sqrt": {Type: "sqrt", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32"},
		}},
		"square": {Type: "square", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"sub": {Type: "sub", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "y", Kind: KindTensor, DomainID: "T"},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32"},
		}},
		"tile": {Type: "tile", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "reps", Kind: KindTensor, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int32", "bool"},
		}},
		"transpose": {Type: "transpose", Params: []Param{
			{Name: "x", Kind: KindTensor, DomainID: "T"},
			{Name: "perm", Kind: KindTensor, Const: true, Domain: []DataType{"int32"}},
		}, Domains: map[string][]DataType{
			"T": []DataType{"fp16", "fp32", "int8", "int16", "int32", "uint8", "uint16", "bool"},
		}},
	},
}

var registered = map[string]bool{
	"abs":                          true,
	"add":                          true,
	"cast":                         true,
	"concat":                       true,
	"const":                        true,
	"conv":                         true,
	"matmul":                       true,
	"maximum":                      true,
	"mul":                          true,
	"pow":                          true,
	"read_state":                   true,
	"real_div":                     true,
	"reduce_max":                   true,
	"reduce_mean":                  true,
	"reduce_sum":                   true,
	"relu":                         true,
	"reshape":                      true,
	"scaled_dot_product_attention": true,
	"sigmoid":                      true,
	"slice_by_size":                true,
	"softmax":                      true,
	"sqrt":                         true,
	"square":                       true,
	"sub":                          true,
	"tile":                         true,
	"transpose":                    true,
}
