// Package apple is a collection of Go packages for Apple platform frameworks.
//
// These bindings are cgo-free, using purego for dynamic function loading at
// runtime. They are auto-generated from Apple developer documentation via
// applegen (github.com/tmc/appledocs/cmd/applegen).

//go:generate -command applegen-generate go run github.com/tmc/appledocs/cmd/applegen generate --output . --module github.com/tmc/apple
//go:generate -command applegen-bootstrap go run github.com/tmc/appledocs/cmd/applegen bootstrap --module github.com/tmc/apple --force --verbose

//go:generate applegen-generate --generate-objc-runtime

//go:generate applegen-bootstrap -f "accelerate"
//go:generate applegen-bootstrap -f "accessibility"
//go:generate applegen-bootstrap -f "appkit"
//go:generate applegen-bootstrap -f "applicationservices"
//go:generate applegen-bootstrap -f "automator"
//go:generate applegen-bootstrap -f "audiotoolbox"
//go:generate applegen-bootstrap -f "avfoundation"
//go:generate applegen-bootstrap -f "cloudkit"
//go:generate applegen-bootstrap -f "colorsync"
//go:generate applegen-bootstrap -f "coreaudio"
//go:generate applegen-bootstrap -f "coreaudiotypes"
//go:generate applegen-bootstrap -f "corebluetooth"
//go:generate applegen-bootstrap -f "coredata"
//go:generate applegen-bootstrap -f "corefoundation"
//go:generate applegen-bootstrap -f "coregraphics"
//go:generate applegen-bootstrap -f "coreimage"
//go:generate applegen-bootstrap -f "corelocation"
//go:generate applegen-bootstrap -f "coremedia"
//go:generate applegen-bootstrap -f "coremediaio"
//go:generate applegen-bootstrap -f "coremidi"
//go:generate applegen-bootstrap -f "coreml"
//go:generate applegen-bootstrap -f "coreservices"
//go:generate applegen-bootstrap -f "corespotlight"
//go:generate applegen-bootstrap -f "coretext"
//go:generate applegen-bootstrap -f "corevideo"
//go:generate applegen-bootstrap -f "corewlan"
//go:generate applegen-bootstrap -f "cryptotokenkit"
//go:generate applegen-bootstrap -f "devicecheck"
//go:generate applegen-bootstrap -f "diskarbitration"
//go:generate applegen-bootstrap -f "dispatch"
//go:generate applegen-bootstrap -f "endpointsecurity" --go-names
//go:generate applegen-bootstrap -f "exceptionhandling"
//go:generate applegen-bootstrap -f "executionpolicy"
//go:generate applegen-bootstrap -f "fileprovider"
//go:generate applegen-bootstrap -f "findersync"
//go:generate applegen-bootstrap -f "foundation"
//go:generate applegen-bootstrap -f "fskit"
//go:generate applegen-bootstrap -f "gamecontroller"
//go:generate applegen-bootstrap -f "glkit"
//go:generate applegen-bootstrap -f "gss"
//go:generate applegen-bootstrap -f "hypervisor" --go-names
//go:generate applegen-bootstrap -f "imagecapturecore"
//go:generate applegen-bootstrap -f "imageio"
//go:generate applegen-bootstrap -f "inputmethodkit"
//go:generate applegen-bootstrap -f "iobluetooth"
//go:generate applegen-bootstrap -f "iokit"
//go:generate applegen-bootstrap -f "iosurface"
//go:generate applegen-bootstrap -f "iousbhost"
//go:generate applegen-bootstrap -f "javascriptcore"
//go:generate applegen-bootstrap -f "kernel"
//go:generate applegen-bootstrap -f "localauthentication"
//go:generate applegen-bootstrap -f "mediaextension"
//go:generate applegen-bootstrap -f "metal"
//go:generate applegen-bootstrap -f "metalkit"
//go:generate applegen-bootstrap -f "metalperformanceshaders"
//go:generate applegen-bootstrap -f "metalperformanceshadersgraph"
//go:generate applegen-bootstrap -f "modelio"
//go:generate applegen-bootstrap -f "naturallanguage"
//go:generate applegen-bootstrap -f "network" --go-names
//go:generate applegen-bootstrap -f "networkextension"
//go:generate applegen-bootstrap -f "objectivec"
//go:generate applegen-bootstrap -f "opendirectory"
//go:generate applegen-bootstrap -f "os" --go-names
//go:generate applegen-bootstrap -f "oslog"
//go:generate applegen-bootstrap -f "paravirtualizedgraphics"
//go:generate applegen-bootstrap -f "pdfkit"
//go:generate applegen-bootstrap -f "quartzcore"
//go:generate applegen-bootstrap -f "screencapturekit"
//go:generate applegen-bootstrap -f "scriptingbridge"
//go:generate applegen-bootstrap -f "security"
//go:generate applegen-bootstrap -f "servicemanagement"
//go:generate applegen-bootstrap -f "soundanalysis"
//go:generate applegen-bootstrap -f "spritekit"
//go:generate applegen-bootstrap -f "symbols"
//go:generate applegen-bootstrap -f "systemconfiguration"
//go:generate applegen-bootstrap -f "systemextensions"
//go:generate applegen-bootstrap -f "uniformtypeidentifiers"
//go:generate applegen-bootstrap -f "usernotifications"
//go:generate applegen-bootstrap -f "videotoolbox"
//go:generate applegen-bootstrap -f "virtualization"
//go:generate applegen-bootstrap -f "vision"
//go:generate applegen-bootstrap -f "vmnet"
//go:generate applegen-bootstrap -f "webkit"
//go:generate applegen-bootstrap -f "xpc"

package apple
