// Code generated from Apple documentation. DO NOT EDIT.

package vision

import (
	"github.com/tmc/apple/objc"
)

// ErrorHandler handles The block to invoke after the request finishes processing.
//
// Used by:
//   - [VNCalculateImageAestheticsScoresRequest.InitWithCompletionHandler]
//   - [VNClassifyImageRequest.InitWithCompletionHandler]
//   - [VNCoreMLRequest.InitWithCompletionHandler]
//   - [VNCoreMLRequest.InitWithModelCompletionHandler]
//   - [VNDetectAnimalBodyPoseRequest.InitWithCompletionHandler]
//   - [VNDetectBarcodesRequest.InitWithCompletionHandler]
//   - [VNDetectContoursRequest.InitWithCompletionHandler]
//   - [VNDetectDocumentSegmentationRequest.InitWithCompletionHandler]
//   - [VNDetectFaceCaptureQualityRequest.InitWithCompletionHandler]
//   - [VNDetectFaceLandmarksRequest.InitWithCompletionHandler]
//   - [VNDetectFaceRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectHorizonRequest.InitWithCompletionHandler]
//   - [VNDetectHumanBodyPose3DRequest.InitWithCompletionHandler]
//   - [VNDetectHumanBodyPose3DRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNDetectHumanBodyPoseRequest.InitWithCompletionHandler]
//   - [VNDetectHumanHandPoseRequest.InitWithCompletionHandler]
//   - [VNDetectHumanRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectTextRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithFrameAnalysisSpacingTrajectoryLengthCompletionHandler]
//   - [VNGenerateAttentionBasedSaliencyImageRequest.InitWithCompletionHandler]
//   - [VNGenerateForegroundInstanceMaskRequest.InitWithCompletionHandler]
//   - [VNGenerateImageFeaturePrintRequest.InitWithCompletionHandler]
//   - [VNGenerateObjectnessBasedSaliencyImageRequest.InitWithCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNGeneratePersonInstanceMaskRequest.InitWithCompletionHandler]
//   - [VNGeneratePersonSegmentationRequest.InitWithCompletionHandler]
//   - [VNGeneratePersonSegmentationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNImageBasedRequest.InitWithCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNInstanceMaskObservation.GenerateMaskedImageOfInstancesFromRequestHandlerCroppedToInstancesExtentError]
//   - [VNInstanceMaskObservation.GenerateScaledMaskForImageForInstancesFromRequestHandlerError]
//   - [VNRecognizeAnimalsRequest.InitWithCompletionHandler]
//   - [VNRecognizeTextRequest.InitWithCompletionHandler]
//   - [VNRequest.InitWithCompletionHandler]
//   - [VNStatefulRequest.InitWithCompletionHandler]
//   - [VNStatefulRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTargetedImageRequest.InitWithCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNTrackHomographicImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTrackHomographicImageRegistrationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackObjectRequest.InitWithCompletionHandler]
//   - [VNTrackObjectRequest.InitWithDetectedObjectObservationCompletionHandler]
//   - [VNTrackOpticalFlowRequest.InitWithCompletionHandler]
//   - [VNTrackOpticalFlowRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackRectangleRequest.InitWithCompletionHandler]
//   - [VNTrackRectangleRequest.InitWithRectangleObservationCompletionHandler]
//   - [VNTrackTranslationalImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTrackTranslationalImageRegistrationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackingRequest.InitWithCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
type ErrorHandler = func()

// NewErrorBlock wraps a Go [ErrorHandler] as an Objective-C block.
// The caller must defer the returned cleanup function.
//
// Used by:
//   - [VNCalculateImageAestheticsScoresRequest.InitWithCompletionHandler]
//   - [VNClassifyImageRequest.InitWithCompletionHandler]
//   - [VNCoreMLRequest.InitWithCompletionHandler]
//   - [VNCoreMLRequest.InitWithModelCompletionHandler]
//   - [VNDetectAnimalBodyPoseRequest.InitWithCompletionHandler]
//   - [VNDetectBarcodesRequest.InitWithCompletionHandler]
//   - [VNDetectContoursRequest.InitWithCompletionHandler]
//   - [VNDetectDocumentSegmentationRequest.InitWithCompletionHandler]
//   - [VNDetectFaceCaptureQualityRequest.InitWithCompletionHandler]
//   - [VNDetectFaceLandmarksRequest.InitWithCompletionHandler]
//   - [VNDetectFaceRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectHorizonRequest.InitWithCompletionHandler]
//   - [VNDetectHumanBodyPose3DRequest.InitWithCompletionHandler]
//   - [VNDetectHumanBodyPose3DRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNDetectHumanBodyPoseRequest.InitWithCompletionHandler]
//   - [VNDetectHumanHandPoseRequest.InitWithCompletionHandler]
//   - [VNDetectHumanRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectTextRectanglesRequest.InitWithCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNDetectTrajectoriesRequest.InitWithFrameAnalysisSpacingTrajectoryLengthCompletionHandler]
//   - [VNGenerateAttentionBasedSaliencyImageRequest.InitWithCompletionHandler]
//   - [VNGenerateForegroundInstanceMaskRequest.InitWithCompletionHandler]
//   - [VNGenerateImageFeaturePrintRequest.InitWithCompletionHandler]
//   - [VNGenerateObjectnessBasedSaliencyImageRequest.InitWithCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNGenerateOpticalFlowRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNGeneratePersonInstanceMaskRequest.InitWithCompletionHandler]
//   - [VNGeneratePersonSegmentationRequest.InitWithCompletionHandler]
//   - [VNGeneratePersonSegmentationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNHomographicImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNImageBasedRequest.InitWithCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNInstanceMaskObservation.GenerateMaskedImageOfInstancesFromRequestHandlerCroppedToInstancesExtentError]
//   - [VNInstanceMaskObservation.GenerateScaledMaskForImageForInstancesFromRequestHandlerError]
//   - [VNRecognizeAnimalsRequest.InitWithCompletionHandler]
//   - [VNRecognizeTextRequest.InitWithCompletionHandler]
//   - [VNRequest.InitWithCompletionHandler]
//   - [VNStatefulRequest.InitWithCompletionHandler]
//   - [VNStatefulRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTargetedImageRequest.InitWithCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNTargetedImageRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
//   - [VNTrackHomographicImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTrackHomographicImageRegistrationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackObjectRequest.InitWithCompletionHandler]
//   - [VNTrackObjectRequest.InitWithDetectedObjectObservationCompletionHandler]
//   - [VNTrackOpticalFlowRequest.InitWithCompletionHandler]
//   - [VNTrackOpticalFlowRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackRectangleRequest.InitWithCompletionHandler]
//   - [VNTrackRectangleRequest.InitWithRectangleObservationCompletionHandler]
//   - [VNTrackTranslationalImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTrackTranslationalImageRegistrationRequest.InitWithFrameAnalysisSpacingCompletionHandler]
//   - [VNTrackingRequest.InitWithCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCGImageOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCGImageOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCIImageOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCIImageOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCMSampleBufferOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCMSampleBufferOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCVPixelBufferOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedCVPixelBufferOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageDataOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageDataOrientationOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageURLOptionsCompletionHandler]
//   - [VNTranslationalImageRegistrationRequest.InitWithTargetedImageURLOrientationOptionsCompletionHandler]
func NewErrorBlock(handler ErrorHandler) (objc.ID, func()) {
	block := objc.NewBlock(func(b objc.Block) {
		handler()
	})
	return objc.ID(block), func() { block.Release() }
}




