// Code generated from Apple documentation for Vision. DO NOT EDIT.

package vision

import (
	"unsafe"
	"sync"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/coreml"
	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [VNRequest] class.
var (
	_VNRequestClass     VNRequestClass
	_VNRequestClassOnce sync.Once
)

func getVNRequestClass() VNRequestClass {
	_VNRequestClassOnce.Do(func() {
		_VNRequestClass = VNRequestClass{class: objc.GetClass("VNRequest")}
	})
	return _VNRequestClass
}

// GetVNRequestClass returns the class object for VNRequest.
func GetVNRequestClass() VNRequestClass {
	return getVNRequestClass()
}

type VNRequestClass struct {
	class objc.Class
}

// Alloc allocates memory for a new instance of the class.
func (vc VNRequestClass) Alloc() VNRequest {
	rv := objc.Send[VNRequest](objc.ID(vc.class), objc.Sel("alloc"))
	return rv
}

// The abstract superclass for analysis requests.
//
// # Overview
// 
// Other Vision request handlers that perform image analysis inherit from this
// abstract base class. Instantiate one of its subclasses to perform image
// analysis.
//
// # Initializing a Request
//
//   - [VNRequest.InitWithCompletionHandler]: Creates a new Vision request with an optional completion handler.
//
// # Configuring a Request
//
//   - [VNRequest.CompletionHandler]: The completion handler the system invokes after the request finishes processing.
//   - [VNRequest.PreferBackgroundProcessing]: A hint to minimize the resource burden of the request.
//   - [VNRequest.SetPreferBackgroundProcessing]
//   - [VNRequest.Results]: The collection of observation results generated by request processing.
//   - [VNRequest.Revision]: The specific algorithm or implementation revision that’s used to perform the request.
//   - [VNRequest.SetRevision]
//   - [VNRequest.UsesCPUOnly]: A Boolean signifying that the Vision request should execute exclusively on the CPU.
//   - [VNRequest.SetUsesCPUOnly]
//
// # Configuring the Compute Device
//
//   - [VNRequest.SupportedComputeStageDevices]: The collection of compute devices per stage that a request supports.
//   - [VNRequest.SetSupportedComputeStageDevices]
//
// # Canceling a Request
//
//   - [VNRequest.Cancel]: Cancels the request before it can finish executing.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest
type VNRequest struct {
	objectivec.Object
}

// VNRequestFromID constructs a [VNRequest] from an objc.ID.
//
// The abstract superclass for analysis requests.
func VNRequestFromID(id objc.ID) VNRequest {
	return VNRequest{objectivec.Object{ID: id}}
}
// NOTE: VNRequest adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [VNRequest] class.
//
// # Initializing a Request
//
//   - [IVNRequest.InitWithCompletionHandler]: Creates a new Vision request with an optional completion handler.
//
// # Configuring a Request
//
//   - [IVNRequest.CompletionHandler]: The completion handler the system invokes after the request finishes processing.
//   - [IVNRequest.PreferBackgroundProcessing]: A hint to minimize the resource burden of the request.
//   - [IVNRequest.SetPreferBackgroundProcessing]
//   - [IVNRequest.Results]: The collection of observation results generated by request processing.
//   - [IVNRequest.Revision]: The specific algorithm or implementation revision that’s used to perform the request.
//   - [IVNRequest.SetRevision]
//   - [IVNRequest.UsesCPUOnly]: A Boolean signifying that the Vision request should execute exclusively on the CPU.
//   - [IVNRequest.SetUsesCPUOnly]
//
// # Configuring the Compute Device
//
//   - [IVNRequest.SupportedComputeStageDevices]: The collection of compute devices per stage that a request supports.
//   - [IVNRequest.SetSupportedComputeStageDevices]
//
// # Canceling a Request
//
//   - [IVNRequest.Cancel]: Cancels the request before it can finish executing.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest
type IVNRequest interface {
	objectivec.IObject

	// Topic: Initializing a Request

	// Creates a new Vision request with an optional completion handler.
	InitWithCompletionHandler(completionHandler ErrorHandler) VNRequest

	// Topic: Configuring a Request

	// The completion handler the system invokes after the request finishes processing.
	CompletionHandler() VNRequestCompletionHandler
	// A hint to minimize the resource burden of the request.
	PreferBackgroundProcessing() bool
	SetPreferBackgroundProcessing(value bool)
	// The collection of observation results generated by request processing.
	Results() []VNObservation
	// The specific algorithm or implementation revision that’s used to perform the request.
	Revision() uint
	SetRevision(value uint)
	// A Boolean signifying that the Vision request should execute exclusively on the CPU.
	UsesCPUOnly() bool
	SetUsesCPUOnly(value bool)

	// Topic: Configuring the Compute Device

	// The collection of compute devices per stage that a request supports.
	SupportedComputeStageDevices() objectivec.IObject
	SetSupportedComputeStageDevices(value objectivec.IObject)

	// Topic: Canceling a Request

	// Cancels the request before it can finish executing.
	Cancel()

	// Returns the compute device for a compute stage.
	ComputeDeviceForComputeStage(computeStage VNComputeStage) coreml.MLComputeDeviceProtocol
	// Assigns a compute device for a compute stage.
	SetComputeDeviceForComputeStage(computeDevice coreml.MLComputeDeviceProtocol, computeStage VNComputeStage)
	// The collection of compute devices per stage that a request supports.
	SupportedComputeStageDevicesAndReturnError() (foundation.INSDictionary, error)
}

// Init initializes the instance.
func (r VNRequest) Init() VNRequest {
	rv := objc.Send[VNRequest](r.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (r VNRequest) Autorelease() VNRequest {
	rv := objc.Send[VNRequest](r.ID, objc.Sel("autorelease"))
	return rv
}

// NewVNRequest creates a new VNRequest instance.
func NewVNRequest() VNRequest {
	class := getVNRequestClass()
	rv := objc.Send[VNRequest](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Creates a new Vision request with an optional completion handler.
//
// completionHandler: The block to invoke after the request finishes processing.
//
// # Discussion
// 
// Vision executes the completion handler on the same queue that it executes
// the request; however, this queue differs from the one where you called
// [PerformRequestsError].
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/init(completionHandler:)
func NewRequestWithCompletionHandler(completionHandler VNRequestCompletionHandler) VNRequest {
	instance := getVNRequestClass().Alloc()
	rv := objc.Send[objc.ID](instance.ID, objc.Sel("initWithCompletionHandler:"), completionHandler)
	return VNRequestFromID(rv)
}

// Creates a new Vision request with an optional completion handler.
//
// completionHandler: The block to invoke after the request finishes processing.
//
// # Discussion
// 
// Vision executes the completion handler on the same queue that it executes
// the request; however, this queue differs from the one where you called
// [PerformRequestsError].
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/init(completionHandler:)
func (r VNRequest) InitWithCompletionHandler(completionHandler ErrorHandler) VNRequest {
_block0, _cleanup0 := NewErrorBlock(completionHandler)
	defer _cleanup0()
	rv := objc.Send[objc.ID](r.ID, objc.Sel("initWithCompletionHandler:"), _block0)
	return VNRequestFromID(rv)
}
// Cancels the request before it can finish executing.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/cancel()
func (r VNRequest) Cancel() {
	objc.Send[objc.ID](r.ID, objc.Sel("cancel"))
}
// Returns the compute device for a compute stage.
//
// computeStage: The compute stage to inspect.
//
// # Return Value
// 
// The current compute device; otherwise, `nil` if one isn’t assigned.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/computeDeviceForComputeStage:
func (r VNRequest) ComputeDeviceForComputeStage(computeStage VNComputeStage) coreml.MLComputeDeviceProtocol {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("computeDeviceForComputeStage:"), objc.String(string(computeStage)))
	return coreml.MLComputeDeviceProtocolObjectFromID(rv)
}
// Assigns a compute device for a compute stage.
//
// computeDevice: The compute device to assign to the compute stage.
//
// computeStage: The compute stage.
//
// # Discussion
// 
// If the parameter `computeDevice` is `nil`, the framework removes any
// explicit compute device assignment and allows the framework to select the
// device.
// 
// Configure any compute device for a given compute stage. When performing a
// request, the system makes a validity check. Call
// [SupportedComputeStageDevicesAndReturnError] to get valid compute devices
// for a request’s compute stages.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/setComputeDevice:forComputeStage:
func (r VNRequest) SetComputeDeviceForComputeStage(computeDevice coreml.MLComputeDeviceProtocol, computeStage VNComputeStage) {
	objc.Send[objc.ID](r.ID, objc.Sel("setComputeDevice:forComputeStage:"), computeDevice, objc.String(string(computeStage)))
}
// The collection of compute devices per stage that a request supports.
//
// # Return Value
// 
// A dictionary of per-stage compute devices; otherwise, `nil` if an error
// occurs.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/supportedComputeStageDevicesAndReturnError:
func (r VNRequest) SupportedComputeStageDevicesAndReturnError() (foundation.INSDictionary, error) {
	var errorPtr objc.ID
	rv := objc.Send[objc.ID](r.ID, objc.Sel("supportedComputeStageDevicesAndReturnError:"), unsafe.Pointer(&errorPtr))
	if errorPtr != 0 {
		objc.Send[objc.ID](errorPtr, objc.Sel("retain"))
		return nil, foundation.NSErrorFrom(errorPtr)
	}
	return foundation.NSDictionaryFromID(rv), nil

}

// The completion handler the system invokes after the request finishes
// processing.
//
// # Discussion
// 
// Vision executes the completion handler on the same queue that it executes
// the request; however, this queue differs from the one where you called
// [PerformRequestsError].
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/completionHandler
func (r VNRequest) CompletionHandler() VNRequestCompletionHandler {
	rv := objc.Send[VNRequestCompletionHandler](r.ID, objc.Sel("completionHandler"))
	return VNRequestCompletionHandler(rv)
}
// A hint to minimize the resource burden of the request.
//
// # Discussion
// 
// If set to [true], this property reduces the request’s memory footprint,
// processing footprint, and CPU/GPU contention at the potential cost of
// longer execution time.
// 
// Setting this value can help ensure that Vision processing doesn’t block
// UI updates and other rendering on the main thread.
//
// [true]: https://developer.apple.com/documentation/Swift/true
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/preferBackgroundProcessing
func (r VNRequest) PreferBackgroundProcessing() bool {
	rv := objc.Send[bool](r.ID, objc.Sel("preferBackgroundProcessing"))
	return rv
}
func (r VNRequest) SetPreferBackgroundProcessing(value bool) {
	objc.Send[struct{}](r.ID, objc.Sel("setPreferBackgroundProcessing:"), value)
}
// The collection of observation results generated by request processing.
//
// # Discussion
// 
// If the request fails, this property is [nil]. Otherwise, it contains an
// array of [VNObservation] subclasses specific to the [VNRequest] subclass.
// 
// Don’t access this property until the request has finished processing.
//
// [nil]: https://developer.apple.com/documentation/ObjectiveC/nil-227m0
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/results
func (r VNRequest) Results() []VNObservation {
	rv := objc.Send[[]objc.ID](r.ID, objc.Sel("results"))
	return objc.ConvertSlice(rv, func(id objc.ID) VNObservation {
		return VNObservationFromID(id)
	})
}
// The specific algorithm or implementation revision that’s used to perform
// the request.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/revision
func (r VNRequest) Revision() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("revision"))
	return rv
}
func (r VNRequest) SetRevision(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setRevision:"), value)
}
// A Boolean signifying that the Vision request should execute exclusively on
// the CPU.
//
// # Discussion
// 
// This value defaults to [false] to signify that the Vision request is free
// to leverage the GPU to accelerate its processing.
//
// [false]: https://developer.apple.com/documentation/Swift/false
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/usesCPUOnly
func (r VNRequest) UsesCPUOnly() bool {
	rv := objc.Send[bool](r.ID, objc.Sel("usesCPUOnly"))
	return rv
}
func (r VNRequest) SetUsesCPUOnly(value bool) {
	objc.Send[struct{}](r.ID, objc.Sel("setUsesCPUOnly:"), value)
}
// The collection of compute devices per stage that a request supports.
//
// See: https://developer.apple.com/documentation/vision/vnrequest/supportedcomputestagedevices
func (r VNRequest) SupportedComputeStageDevices() objectivec.IObject {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("supportedComputeStageDevices"))
	return objectivec.Object{ID: rv}
}
func (r VNRequest) SetSupportedComputeStageDevices(value objectivec.IObject) {
	objc.Send[struct{}](r.ID, objc.Sel("setSupportedComputeStageDevices:"), value)
}

// The current revison supported by the request.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/currentRevision
func (_VNRequestClass VNRequestClass) CurrentRevision() uint {
	rv := objc.Send[uint](objc.ID(_VNRequestClass.class), objc.Sel("currentRevision"))
	return rv
}
// The revision of the latest request for the particular SDK linked with the
// client application.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/defaultRevision
func (_VNRequestClass VNRequestClass) DefaultRevision() uint {
	rv := objc.Send[uint](objc.ID(_VNRequestClass.class), objc.Sel("defaultRevision"))
	return rv
}
// The collection of currently-supported algorithm versions for the class of
// request.
//
// # Discussion
// 
// This method allows clients to inspect at runtime what capabilities are
// available for each class of [VNRequest] in the Vision framework.
//
// See: https://developer.apple.com/documentation/Vision/VNRequest/supportedRevisions
func (_VNRequestClass VNRequestClass) SupportedRevisions() foundation.NSIndexSet {
	rv := objc.Send[objc.ID](objc.ID(_VNRequestClass.class), objc.Sel("supportedRevisions"))
	return foundation.NSIndexSetFromID(objc.ID(rv))
}

