// Code generated from Apple documentation for Foundation. DO NOT EDIT.

package foundation

import (
	"sync"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [NSMetadataQueryAttributeValueTuple] class.
var (
	_NSMetadataQueryAttributeValueTupleClass     NSMetadataQueryAttributeValueTupleClass
	_NSMetadataQueryAttributeValueTupleClassOnce sync.Once
)

func getNSMetadataQueryAttributeValueTupleClass() NSMetadataQueryAttributeValueTupleClass {
	_NSMetadataQueryAttributeValueTupleClassOnce.Do(func() {
		_NSMetadataQueryAttributeValueTupleClass = NSMetadataQueryAttributeValueTupleClass{class: objc.GetClass("NSMetadataQueryAttributeValueTuple")}
	})
	return _NSMetadataQueryAttributeValueTupleClass
}

// GetNSMetadataQueryAttributeValueTupleClass returns the class object for NSMetadataQueryAttributeValueTuple.
func GetNSMetadataQueryAttributeValueTupleClass() NSMetadataQueryAttributeValueTupleClass {
	return getNSMetadataQueryAttributeValueTupleClass()
}

type NSMetadataQueryAttributeValueTupleClass struct {
	class objc.Class
}

// Alloc allocates memory for a new instance of the class.
func (nc NSMetadataQueryAttributeValueTupleClass) Alloc() NSMetadataQueryAttributeValueTuple {
	rv := objc.Send[NSMetadataQueryAttributeValueTuple](objc.ID(nc.class), objc.Sel("alloc"))
	return rv
}







// The [NSMetadataQueryAttributeValueTuple] class represents attribute-value
// tuples, which are objects that contain the attribute name and value of a
// metadata attribute.
//
// # Overview
// 
// Attribute-value tuples are returned by [NSMetadataQuery] objects as the
// results in the value lists. Each attribute/value tuple contains the
// attribute name, the value, and the number of instances of that value that
// exist for the attribute name.
//
// # Getting Query Attribute/Value Information
//
//   - [NSMetadataQueryAttributeValueTuple.Attribute]: The attribute name for the tuple’s value.
//   - [NSMetadataQueryAttributeValueTuple.Count]: The number of instances of the value for the tuple’s attribute.
//   - [NSMetadataQueryAttributeValueTuple.Value]: The value of the tuple’s attribute.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQueryAttributeValueTuple
type NSMetadataQueryAttributeValueTuple struct {
	objectivec.Object
}

// NSMetadataQueryAttributeValueTupleFromID constructs a [NSMetadataQueryAttributeValueTuple] from an objc.ID.
//
// The [NSMetadataQueryAttributeValueTuple] class represents attribute-value
// tuples, which are objects that contain the attribute name and value of a
// metadata attribute.
func NSMetadataQueryAttributeValueTupleFromID(id objc.ID) NSMetadataQueryAttributeValueTuple {
	return NSMetadataQueryAttributeValueTuple{objectivec.Object{id}}
}
// NOTE: NSMetadataQueryAttributeValueTuple adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.





// An interface definition for the [NSMetadataQueryAttributeValueTuple] class.
//
// # Getting Query Attribute/Value Information
//
//   - [INSMetadataQueryAttributeValueTuple.Attribute]: The attribute name for the tuple’s value.
//   - [INSMetadataQueryAttributeValueTuple.Count]: The number of instances of the value for the tuple’s attribute.
//   - [INSMetadataQueryAttributeValueTuple.Value]: The value of the tuple’s attribute.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQueryAttributeValueTuple
type INSMetadataQueryAttributeValueTuple interface {
	objectivec.IObject

	// Topic: Getting Query Attribute/Value Information

	// The attribute name for the tuple’s value.
	Attribute() string
	// The number of instances of the value for the tuple’s attribute.
	Count() uint
	// The value of the tuple’s attribute.
	Value() objectivec.IObject

	// An array containing hierarchical groups of query results. (read-only)
	GroupedResults() INSMetadataQueryResultGroup
	SetGroupedResults(value INSMetadataQueryResultGroup)
	// The queue on which query result notifications are posted.
	OperationQueue() INSOperationQueue
	SetOperationQueue(value INSOperationQueue)
	// The number of results returned by the query. (read-only)
	ResultCount() int
	SetResultCount(value int)
	// An array containing the query’s results.
	Results() objectivec.IObject
	SetResults(value objectivec.IObject)
	// A dictionary containing the value lists generated by the query.
	ValueLists() INSMetadataQueryAttributeValueTuple
	SetValueLists(value INSMetadataQueryAttributeValueTuple)
}





// Init initializes the instance.
func (m NSMetadataQueryAttributeValueTuple) Init() NSMetadataQueryAttributeValueTuple {
	rv := objc.Send[NSMetadataQueryAttributeValueTuple](m.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (m NSMetadataQueryAttributeValueTuple) Autorelease() NSMetadataQueryAttributeValueTuple {
	rv := objc.Send[NSMetadataQueryAttributeValueTuple](m.ID, objc.Sel("autorelease"))
	return rv
}

// NewNSMetadataQueryAttributeValueTuple creates a new NSMetadataQueryAttributeValueTuple instance.
func NewNSMetadataQueryAttributeValueTuple() NSMetadataQueryAttributeValueTuple {
	class := getNSMetadataQueryAttributeValueTupleClass()
	rv := objc.Send[NSMetadataQueryAttributeValueTuple](objc.ID(class.class), objc.Sel("new"))
	return rv
}





















// The attribute name for the tuple’s value.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQueryAttributeValueTuple/attribute
func (m NSMetadataQueryAttributeValueTuple) Attribute() string {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("attribute"))
	return NSStringFromID(rv).String()
}



// The number of instances of the value for the tuple’s attribute.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQueryAttributeValueTuple/count
func (m NSMetadataQueryAttributeValueTuple) Count() uint {
	rv := objc.Send[uint](m.ID, objc.Sel("count"))
	return rv
}



// The value of the tuple’s attribute.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQueryAttributeValueTuple/value
func (m NSMetadataQueryAttributeValueTuple) Value() objectivec.IObject {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("value"))
	return objectivec.Object{ID: rv}
}



// An array containing hierarchical groups of query results. (read-only)
//
// See: https://developer.apple.com/documentation/foundation/nsmetadataquery/groupedresults
func (m NSMetadataQueryAttributeValueTuple) GroupedResults() INSMetadataQueryResultGroup {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("groupedResults"))
	return NSMetadataQueryResultGroupFromID(objc.ID(rv))
}
func (m NSMetadataQueryAttributeValueTuple) SetGroupedResults(value INSMetadataQueryResultGroup) {
	objc.Send[struct{}](m.ID, objc.Sel("setGroupedResults:"), value)
}



// The queue on which query result notifications are posted.
//
// See: https://developer.apple.com/documentation/foundation/nsmetadataquery/operationqueue
func (m NSMetadataQueryAttributeValueTuple) OperationQueue() INSOperationQueue {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("operationQueue"))
	return NSOperationQueueFromID(objc.ID(rv))
}
func (m NSMetadataQueryAttributeValueTuple) SetOperationQueue(value INSOperationQueue) {
	objc.Send[struct{}](m.ID, objc.Sel("setOperationQueue:"), value)
}



// The number of results returned by the query. (read-only)
//
// See: https://developer.apple.com/documentation/foundation/nsmetadataquery/resultcount
func (m NSMetadataQueryAttributeValueTuple) ResultCount() int {
	rv := objc.Send[int](m.ID, objc.Sel("resultCount"))
	return rv
}
func (m NSMetadataQueryAttributeValueTuple) SetResultCount(value int) {
	objc.Send[struct{}](m.ID, objc.Sel("setResultCount:"), value)
}



// An array containing the query’s results.
//
// See: https://developer.apple.com/documentation/foundation/nsmetadataquery/results
func (m NSMetadataQueryAttributeValueTuple) Results() objectivec.IObject {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("results"))
	return objectivec.Object{ID: rv}
}
func (m NSMetadataQueryAttributeValueTuple) SetResults(value objectivec.IObject) {
	objc.Send[struct{}](m.ID, objc.Sel("setResults:"), value)
}



// A dictionary containing the value lists generated by the query.
//
// See: https://developer.apple.com/documentation/foundation/nsmetadataquery/valuelists
func (m NSMetadataQueryAttributeValueTuple) ValueLists() INSMetadataQueryAttributeValueTuple {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("valueLists"))
	return NSMetadataQueryAttributeValueTupleFromID(objc.ID(rv))
}
func (m NSMetadataQueryAttributeValueTuple) SetValueLists(value INSMetadataQueryAttributeValueTuple) {
	objc.Send[struct{}](m.ID, objc.Sel("setValueLists:"), value)
}























