// Code generated from Apple documentation for Foundation. DO NOT EDIT.

package foundation

import (
	"context"
	"sync"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [NSMetadataQuery] class.
var (
	_NSMetadataQueryClass     NSMetadataQueryClass
	_NSMetadataQueryClassOnce sync.Once
)

func getNSMetadataQueryClass() NSMetadataQueryClass {
	_NSMetadataQueryClassOnce.Do(func() {
		_NSMetadataQueryClass = NSMetadataQueryClass{class: objc.GetClass("NSMetadataQuery")}
	})
	return _NSMetadataQueryClass
}

// GetNSMetadataQueryClass returns the class object for NSMetadataQuery.
func GetNSMetadataQueryClass() NSMetadataQueryClass {
	return getNSMetadataQueryClass()
}

type NSMetadataQueryClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (nc NSMetadataQueryClass) Class() objc.Class {
	return nc.class
}

// Alloc allocates memory for a new instance of the class.
func (nc NSMetadataQueryClass) Alloc() NSMetadataQuery {
	rv := objc.Send[NSMetadataQuery](objc.ID(nc.class), objc.Sel("alloc"))
	return rv
}

// A query that you perform against Spotlight metadata.
//
// # Overview
// 
// The [NSMetadataQuery] class encapsulates the functionality provided by the
// [MDQuery] opaque type for querying the Spotlight metadata.
// 
// [NSMetadataQuery] objects provide metadata query results in several ways:
// 
// - As individual attribute values for requested attributes. - As value lists
// that contain the distinct values for given attributes in the query results.
// - As a result array proxy, containing all the query results. This is
// suitable for use with Cocoa bindings. - As a hierarchical collection of
// results, grouping together items with the same values for specified
// grouping attributes. This is also suitable for use with Cocoa bindings.
// 
// Queries have two phases: the initial gathering phase that collects all
// currently matching results and a second live-update phase.
// 
// By default, the receiver has no limitation on its search scope. Use the
// [NSMetadataQuery.SearchScopes] property to customize.
// 
// By default, notification of updated results occurs at 1.0 seconds. Use the
// [NSMetadataQuery.NotificationBatchingInterval] property to customize.
// 
// You must set a predicate with the [Predicate] property before starting a
// query.
//
// [MDQuery]: https://developer.apple.com/documentation/coreservices/file_metadata/mdquery
//
// # Configuring Queries
//
//   - [NSMetadataQuery.SearchScopes]: An array containing the search scopes.
//   - [NSMetadataQuery.SetSearchScopes]
//   - [NSMetadataQuery.Predicate]: The predicate used to filter query results.
//   - [NSMetadataQuery.SetPredicate]
//   - [NSMetadataQuery.SortDescriptors]: An array of sort descriptor objects.
//   - [NSMetadataQuery.SetSortDescriptors]
//   - [NSMetadataQuery.ValueListAttributes]: An array of attributes whose values are gathered by the query.
//   - [NSMetadataQuery.SetValueListAttributes]
//   - [NSMetadataQuery.GroupingAttributes]: An array of grouping attributes. (read-only)
//   - [NSMetadataQuery.SetGroupingAttributes]
//   - [NSMetadataQuery.NotificationBatchingInterval]: The interval at which notification of updated results occurs.
//   - [NSMetadataQuery.SetNotificationBatchingInterval]
//   - [NSMetadataQuery.Delegate]: The query’s delegate.
//   - [NSMetadataQuery.SetDelegate]
//   - [NSMetadataQuery.SearchItems]: An array of objects that define the query’s scope.
//   - [NSMetadataQuery.SetSearchItems]
//
// # Running Queries
//
//   - [NSMetadataQuery.Started]: A Boolean value that indicates whether the query has started. (read-only)
//   - [NSMetadataQuery.StartQuery]: Attempts to start the query.
//   - [NSMetadataQuery.Gathering]: A Boolean value that indicates whether the receiver is in the initial gathering phase of the query. (read-only)
//   - [NSMetadataQuery.Stopped]: A Boolean value that indicates whether the query has stopped.
//   - [NSMetadataQuery.StopQuery]: Stops the receiver’s current query from gathering any further results.
//
// # Getting Query Results
//
//   - [NSMetadataQuery.Results]: An array containing the query’s results.
//   - [NSMetadataQuery.ResultCount]: The number of results returned by the query. (read-only)
//   - [NSMetadataQuery.ResultAtIndex]: Returns the query result at a specific index.
//   - [NSMetadataQuery.IndexOfResult]: Returns the index of a query result object in the receiver’s results array.
//   - [NSMetadataQuery.GroupedResults]: An array containing hierarchical groups of query results. (read-only)
//   - [NSMetadataQuery.EnumerateResultsUsingBlock]: Enumerates the current set of results using the given block.
//   - [NSMetadataQuery.EnumerateResultsWithOptionsUsingBlock]: Enumerates the current set of results using the given options and block.
//   - [NSMetadataQuery.ValueLists]: A dictionary containing the value lists generated by the query.
//   - [NSMetadataQuery.ValueOfAttributeForResultAtIndex]: Returns the value for the attribute name `attrName` at the index in the results specified by `idx`.
//   - [NSMetadataQuery.EnableUpdates]: Enables updates to the query results.
//   - [NSMetadataQuery.DisableUpdates]: Disables updates to the query results.
//   - [NSMetadataQuery.OperationQueue]: The queue on which query result notifications are posted.
//   - [NSMetadataQuery.SetOperationQueue]
//
// # Notifications
//
//   - [NSMetadataQuery.NSMetadataQueryDidFinishGathering]: Posted when the receiver has finished with the initial result-gathering phase of the query.
//   - [NSMetadataQuery.NSMetadataQueryDidStartGathering]: Posted when the receiver begins with the initial result-gathering phase of the query.
//   - [NSMetadataQuery.NSMetadataQueryDidUpdate]: Posted when the receiver’s results have changed during the live-update phase of the query.
//   - [NSMetadataQuery.NSMetadataQueryGatheringProgress]: Posted as the receiver is collecting results during the initial result-gathering phase of the query.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery
type NSMetadataQuery struct {
	objectivec.Object
}

// NSMetadataQueryFromID constructs a [NSMetadataQuery] from an objc.ID.
//
// A query that you perform against Spotlight metadata.
func NSMetadataQueryFromID(id objc.ID) NSMetadataQuery {
	return NSMetadataQuery{objectivec.Object{ID: id}}
}
// NOTE: NSMetadataQuery adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [NSMetadataQuery] class.
//
// # Configuring Queries
//
//   - [INSMetadataQuery.SearchScopes]: An array containing the search scopes.
//   - [INSMetadataQuery.SetSearchScopes]
//   - [INSMetadataQuery.Predicate]: The predicate used to filter query results.
//   - [INSMetadataQuery.SetPredicate]
//   - [INSMetadataQuery.SortDescriptors]: An array of sort descriptor objects.
//   - [INSMetadataQuery.SetSortDescriptors]
//   - [INSMetadataQuery.ValueListAttributes]: An array of attributes whose values are gathered by the query.
//   - [INSMetadataQuery.SetValueListAttributes]
//   - [INSMetadataQuery.GroupingAttributes]: An array of grouping attributes. (read-only)
//   - [INSMetadataQuery.SetGroupingAttributes]
//   - [INSMetadataQuery.NotificationBatchingInterval]: The interval at which notification of updated results occurs.
//   - [INSMetadataQuery.SetNotificationBatchingInterval]
//   - [INSMetadataQuery.Delegate]: The query’s delegate.
//   - [INSMetadataQuery.SetDelegate]
//   - [INSMetadataQuery.SearchItems]: An array of objects that define the query’s scope.
//   - [INSMetadataQuery.SetSearchItems]
//
// # Running Queries
//
//   - [INSMetadataQuery.Started]: A Boolean value that indicates whether the query has started. (read-only)
//   - [INSMetadataQuery.StartQuery]: Attempts to start the query.
//   - [INSMetadataQuery.Gathering]: A Boolean value that indicates whether the receiver is in the initial gathering phase of the query. (read-only)
//   - [INSMetadataQuery.Stopped]: A Boolean value that indicates whether the query has stopped.
//   - [INSMetadataQuery.StopQuery]: Stops the receiver’s current query from gathering any further results.
//
// # Getting Query Results
//
//   - [INSMetadataQuery.Results]: An array containing the query’s results.
//   - [INSMetadataQuery.ResultCount]: The number of results returned by the query. (read-only)
//   - [INSMetadataQuery.ResultAtIndex]: Returns the query result at a specific index.
//   - [INSMetadataQuery.IndexOfResult]: Returns the index of a query result object in the receiver’s results array.
//   - [INSMetadataQuery.GroupedResults]: An array containing hierarchical groups of query results. (read-only)
//   - [INSMetadataQuery.EnumerateResultsUsingBlock]: Enumerates the current set of results using the given block.
//   - [INSMetadataQuery.EnumerateResultsWithOptionsUsingBlock]: Enumerates the current set of results using the given options and block.
//   - [INSMetadataQuery.ValueLists]: A dictionary containing the value lists generated by the query.
//   - [INSMetadataQuery.ValueOfAttributeForResultAtIndex]: Returns the value for the attribute name `attrName` at the index in the results specified by `idx`.
//   - [INSMetadataQuery.EnableUpdates]: Enables updates to the query results.
//   - [INSMetadataQuery.DisableUpdates]: Disables updates to the query results.
//   - [INSMetadataQuery.OperationQueue]: The queue on which query result notifications are posted.
//   - [INSMetadataQuery.SetOperationQueue]
//
// # Notifications
//
//   - [INSMetadataQuery.NSMetadataQueryDidFinishGathering]: Posted when the receiver has finished with the initial result-gathering phase of the query.
//   - [INSMetadataQuery.NSMetadataQueryDidStartGathering]: Posted when the receiver begins with the initial result-gathering phase of the query.
//   - [INSMetadataQuery.NSMetadataQueryDidUpdate]: Posted when the receiver’s results have changed during the live-update phase of the query.
//   - [INSMetadataQuery.NSMetadataQueryGatheringProgress]: Posted as the receiver is collecting results during the initial result-gathering phase of the query.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery
type INSMetadataQuery interface {
	objectivec.IObject

	// Topic: Configuring Queries

	// An array containing the search scopes.
	SearchScopes() INSArray
	SetSearchScopes(value INSArray)
	// The predicate used to filter query results.
	Predicate() INSPredicate
	SetPredicate(value INSPredicate)
	// An array of sort descriptor objects.
	SortDescriptors() []NSSortDescriptor
	SetSortDescriptors(value []NSSortDescriptor)
	// An array of attributes whose values are gathered by the query.
	ValueListAttributes() []string
	SetValueListAttributes(value []string)
	// An array of grouping attributes. (read-only)
	GroupingAttributes() []string
	SetGroupingAttributes(value []string)
	// The interval at which notification of updated results occurs.
	NotificationBatchingInterval() float64
	SetNotificationBatchingInterval(value float64)
	// The query’s delegate.
	Delegate() NSMetadataQueryDelegate
	SetDelegate(value NSMetadataQueryDelegate)
	// An array of objects that define the query’s scope.
	SearchItems() INSArray
	SetSearchItems(value INSArray)

	// Topic: Running Queries

	// A Boolean value that indicates whether the query has started. (read-only)
	Started() bool
	// Attempts to start the query.
	StartQuery() bool
	// A Boolean value that indicates whether the receiver is in the initial gathering phase of the query. (read-only)
	Gathering() bool
	// A Boolean value that indicates whether the query has stopped.
	Stopped() bool
	// Stops the receiver’s current query from gathering any further results.
	StopQuery()

	// Topic: Getting Query Results

	// An array containing the query’s results.
	Results() INSArray
	// The number of results returned by the query. (read-only)
	ResultCount() uint
	// Returns the query result at a specific index.
	ResultAtIndex(idx uint) objectivec.IObject
	// Returns the index of a query result object in the receiver’s results array.
	IndexOfResult(result objectivec.IObject) uint
	// An array containing hierarchical groups of query results. (read-only)
	GroupedResults() []NSMetadataQueryResultGroup
	// Enumerates the current set of results using the given block.
	EnumerateResultsUsingBlock(block ObjectHandler)
	// Enumerates the current set of results using the given options and block.
	EnumerateResultsWithOptionsUsingBlock(opts NSEnumerationOptions, block ObjectHandler)
	// A dictionary containing the value lists generated by the query.
	ValueLists() INSDictionary
	// Returns the value for the attribute name `attrName` at the index in the results specified by `idx`.
	ValueOfAttributeForResultAtIndex(attrName string, idx uint) objectivec.IObject
	// Enables updates to the query results.
	EnableUpdates()
	// Disables updates to the query results.
	DisableUpdates()
	// The queue on which query result notifications are posted.
	OperationQueue() INSOperationQueue
	SetOperationQueue(value INSOperationQueue)

	// Topic: Notifications

	// Posted when the receiver has finished with the initial result-gathering phase of the query.
	NSMetadataQueryDidFinishGathering() NSNotificationName
	// Posted when the receiver begins with the initial result-gathering phase of the query.
	NSMetadataQueryDidStartGathering() NSNotificationName
	// Posted when the receiver’s results have changed during the live-update phase of the query.
	NSMetadataQueryDidUpdate() NSNotificationName
	// Posted as the receiver is collecting results during the initial result-gathering phase of the query.
	NSMetadataQueryGatheringProgress() NSNotificationName
}

// Init initializes the instance.
func (m NSMetadataQuery) Init() NSMetadataQuery {
	rv := objc.Send[NSMetadataQuery](m.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (m NSMetadataQuery) Autorelease() NSMetadataQuery {
	rv := objc.Send[NSMetadataQuery](m.ID, objc.Sel("autorelease"))
	return rv
}

// NewNSMetadataQuery creates a new NSMetadataQuery instance.
func NewNSMetadataQuery() NSMetadataQuery {
	class := getNSMetadataQueryClass()
	rv := objc.Send[NSMetadataQuery](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Attempts to start the query.
//
// # Return Value
// 
// [true] when successful; otherwise, [false].
// 
// A query may fail to start if it does not specify a [Predicate], or if the
// query has already been started.
//
// [false]: https://developer.apple.com/documentation/Swift/false
// [true]: https://developer.apple.com/documentation/Swift/true
//
// # Discussion
// 
// A query can’t be started if the receiver is already running a query or no
// predicate has been specified.
// 
// This method must be called from the receiver’s [OperationQueue] or on the
// main thread. For example:
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/start()
func (m NSMetadataQuery) StartQuery() bool {
	rv := objc.Send[bool](m.ID, objc.Sel("startQuery"))
	return rv
}
// Stops the receiver’s current query from gathering any further results.
//
// # Discussion
// 
// The receiver first completes gathering any unprocessed results. If a query
// is stopped before the gathering phase finishes, it does not post an
// [NSMetadataQueryDidStartGatheringNotification] notification.
// 
// You call this function to stop a query that is generating too many results
// to be useful but you still want to access the available results. If the
// receiver is sent a `startQuery` message after performing this method, the
// existing results are discarded.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/stop()
func (m NSMetadataQuery) StopQuery() {
	objc.Send[objc.ID](m.ID, objc.Sel("stopQuery"))
}
// Returns the query result at a specific index.
//
// idx: The index of the desired result in the query result array.
//
// # Return Value
// 
// The query result at the position specified by `idx`. By default, this
// method returns an [NSMetadataItem] object representing the requested
// result; however, the query’s delegate can substitute this object with an
// instance of a different class.
//
// # Discussion
// 
// For performance reasons, use this method when retrieving a specific result,
// rather than the array returned by [Results].
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/result(at:)
func (m NSMetadataQuery) ResultAtIndex(idx uint) objectivec.IObject {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("resultAtIndex:"), idx)
	return objectivec.Object{ID: rv}
}
// Returns the index of a query result object in the receiver’s results
// array.
//
// result: The query result object being inquired about.
//
// # Return Value
// 
// Index of `result` in the query result array.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/index(ofResult:)
func (m NSMetadataQuery) IndexOfResult(result objectivec.IObject) uint {
	rv := objc.Send[uint](m.ID, objc.Sel("indexOfResult:"), result)
	return rv
}
// Enumerates the current set of results using the given block.
//
// block: The block to execute for each current result.
//
// # Discussion
// 
// This method disables the query at the start of the iteration and reenables
// it upon completion. Use [EnumerateResultsWithOptionsUsingBlock] if you want
// to use concurrent or reverse iteration.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/enumerateResults(_:)
func (m NSMetadataQuery) EnumerateResultsUsingBlock(block ObjectHandler) {
_block0, _ := NewObjectBlock(block)
	objc.Send[objc.ID](m.ID, objc.Sel("enumerateResultsUsingBlock:"), _block0)
}
// Enumerates the current set of results using the given options and block.
//
// opts: Options for the enumeration. For a complete list of options, see
// [NSEnumerationOptions].
// //
// [NSEnumerationOptions]: https://developer.apple.com/documentation/Foundation/NSEnumerationOptions
//
// block: The block to execute for each current result.
//
// # Discussion
// 
// This method disables the query at the start of the iteration and reenables
// it upon completion.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/enumerateResults(options:using:)
func (m NSMetadataQuery) EnumerateResultsWithOptionsUsingBlock(opts NSEnumerationOptions, block ObjectHandler) {
_block1, _ := NewObjectBlock(block)
	objc.Send[objc.ID](m.ID, objc.Sel("enumerateResultsWithOptions:usingBlock:"), opts, _block1)
}
// Returns the value for the attribute name `attrName` at the index in the
// results specified by `idx`.
//
// attrName: The attribute of the result object at `idx` being inquired about. The
// attribute must be specified in [ValueListAttributes], as a sorting key in a
// specified sort descriptor, or as one of the grouping attributes specified
// set for the query.
//
// idx: The index of the desired return object in the query results array.
//
// # Return Value
// 
// Value for `attrName` in the result object at `idx` in the query result
// array.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/value(ofAttribute:forResultAt:)
func (m NSMetadataQuery) ValueOfAttributeForResultAtIndex(attrName string, idx uint) objectivec.IObject {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("valueOfAttribute:forResultAtIndex:"), objc.String(attrName), idx)
	return objectivec.Object{ID: rv}
}
// Enables updates to the query results.
//
// # Discussion
// 
// Unless you use [EnumerateResultsUsingBlock] or
// [EnumerateResultsWithOptionsUsingBlock], you should invoke this method
// after you’re done iterating over the query results.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/enableUpdates()
func (m NSMetadataQuery) EnableUpdates() {
	objc.Send[objc.ID](m.ID, objc.Sel("enableUpdates"))
}
// Disables updates to the query results.
//
// # Discussion
// 
// Unless you use [EnumerateResultsUsingBlock] or
// [EnumerateResultsWithOptionsUsingBlock], you should invoke this method
// before iterating over query results that could change due to live updates.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/disableUpdates()
func (m NSMetadataQuery) DisableUpdates() {
	objc.Send[objc.ID](m.ID, objc.Sel("disableUpdates"))
}

// An array containing the search scopes.
//
// # Discussion
// 
// This array can contain [NSURL] or [NSString] objects that represent
// file-system directories or the search scopes for the query. For a list of
// valid search scopes, see [Metadata Query Search Scopes]. An empty array
// indicates that there is no limitation on where the query searches.
//
// [Metadata Query Search Scopes]: https://developer.apple.com/documentation/Foundation/metadata-query-search-scopes
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/searchScopes
func (m NSMetadataQuery) SearchScopes() INSArray {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("searchScopes"))
	return NSArrayFromID(objc.ID(rv))
}
func (m NSMetadataQuery) SetSearchScopes(value INSArray) {
	objc.Send[struct{}](m.ID, objc.Sel("setSearchScopes:"), value)
}
// The predicate used to filter query results.
//
// # Discussion
// 
// Setting this property while a query is running stops the query and discards
// the current results. The receiver immediately starts a new query.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/predicate
func (m NSMetadataQuery) Predicate() INSPredicate {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("predicate"))
	return NSPredicateFromID(objc.ID(rv))
}
func (m NSMetadataQuery) SetPredicate(value INSPredicate) {
	objc.Send[struct{}](m.ID, objc.Sel("setPredicate:"), value)
}
// An array of sort descriptor objects.
//
// # Discussion
// 
// Setting this property while a query is running stops the query and discards
// the current results. The receiver immediately starts a new query.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/sortDescriptors
func (m NSMetadataQuery) SortDescriptors() []NSSortDescriptor {
	rv := objc.Send[[]objc.ID](m.ID, objc.Sel("sortDescriptors"))
	return objc.ConvertSlice(rv, func(id objc.ID) NSSortDescriptor {
		return NSSortDescriptorFromID(id)
	})
}
func (m NSMetadataQuery) SetSortDescriptors(value []NSSortDescriptor) {
	objc.Send[struct{}](m.ID, objc.Sel("setSortDescriptors:"), objectivec.IObjectSliceToNSArray(value))
}
// An array of attributes whose values are gathered by the query.
//
// # Discussion
// 
// The query collects the values of these attributes into uniqued lists that
// can be used to summarize the results of the query. If `attributes` is
// `nil`, the query generates no value lists. Note that value list collection
// increases CPU usage and significantly increases the memory usage of an
// [NSMetadataQuery] object.
// 
// Setting this property while a query is running stops the query and discards
// the current results. The receiver immediately starts a new query.
// 
// For a list of valid attributes, see Attribute Keys and Cloud Storage Keys
// in [NSMetadataItem].
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/valueListAttributes
func (m NSMetadataQuery) ValueListAttributes() []string {
	rv := objc.Send[[]objc.ID](m.ID, objc.Sel("valueListAttributes"))
	return objc.ConvertSliceToStrings(rv)
}
func (m NSMetadataQuery) SetValueListAttributes(value []string) {
	objc.Send[struct{}](m.ID, objc.Sel("setValueListAttributes:"), objectivec.StringSliceToNSArray(value))
}
// An array of grouping attributes. (read-only)
//
// # Discussion
// 
// Setting this property while a query is running stops the query and discards
// the current results. The receiver immediately starts a new query.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/groupingAttributes
func (m NSMetadataQuery) GroupingAttributes() []string {
	rv := objc.Send[[]objc.ID](m.ID, objc.Sel("groupingAttributes"))
	return objc.ConvertSliceToStrings(rv)
}
func (m NSMetadataQuery) SetGroupingAttributes(value []string) {
	objc.Send[struct{}](m.ID, objc.Sel("setGroupingAttributes:"), objectivec.StringSliceToNSArray(value))
}
// The interval at which notification of updated results occurs.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/notificationBatchingInterval
func (m NSMetadataQuery) NotificationBatchingInterval() float64 {
	rv := objc.Send[NSTimeInterval](m.ID, objc.Sel("notificationBatchingInterval"))
	return float64(rv)
}
func (m NSMetadataQuery) SetNotificationBatchingInterval(value float64) {
	objc.Send[struct{}](m.ID, objc.Sel("setNotificationBatchingInterval:"), value)
}
// The query’s delegate.
//
// # Discussion
// 
// This property contains an object that acts as the query’s delegate, or
// `nil`. The delegate must implement the [NSMetadataQueryDelegate]. Pass
// `nil` to remove the current delegate.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/delegate
func (m NSMetadataQuery) Delegate() NSMetadataQueryDelegate {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("delegate"))
	return NSMetadataQueryDelegateObjectFromID(rv)
}
func (m NSMetadataQuery) SetDelegate(value NSMetadataQueryDelegate) {
	objc.Send[struct{}](m.ID, objc.Sel("setDelegate:"), value)
}
// An array of objects that define the query’s scope.
//
// # Discussion
// 
// Use this method to scope the metadata query to a collection of existing
// URLs and/or metadata items. This array contains the [NSURL] and/or
// [NSMetadataItem] items to be searched.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/searchItems
func (m NSMetadataQuery) SearchItems() INSArray {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("searchItems"))
	return NSArrayFromID(objc.ID(rv))
}
func (m NSMetadataQuery) SetSearchItems(value INSArray) {
	objc.Send[struct{}](m.ID, objc.Sel("setSearchItems:"), value)
}
// A Boolean value that indicates whether the query has started. (read-only)
//
// # Discussion
// 
// This property contains [true] when the receiver has executed the
// `startQuery` method; otherwise, [false].
//
// [false]: https://developer.apple.com/documentation/Swift/false
// [true]: https://developer.apple.com/documentation/Swift/true
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/isStarted
func (m NSMetadataQuery) Started() bool {
	rv := objc.Send[bool](m.ID, objc.Sel("isStarted"))
	return rv
}
// A Boolean value that indicates whether the receiver is in the initial
// gathering phase of the query. (read-only)
//
// # Discussion
// 
// This property contains [true] when the query is in the initial gathering
// phase; otherwise, [false].
//
// [false]: https://developer.apple.com/documentation/Swift/false
// [true]: https://developer.apple.com/documentation/Swift/true
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/isGathering
func (m NSMetadataQuery) Gathering() bool {
	rv := objc.Send[bool](m.ID, objc.Sel("isGathering"))
	return rv
}
// A Boolean value that indicates whether the query has stopped.
//
// # Discussion
// 
// This property contains [true] when the receiver has stopped the query;
// otherwise, [false].
//
// [false]: https://developer.apple.com/documentation/Swift/false
// [true]: https://developer.apple.com/documentation/Swift/true
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/isStopped
func (m NSMetadataQuery) Stopped() bool {
	rv := objc.Send[bool](m.ID, objc.Sel("isStopped"))
	return rv
}
// An array containing the query’s results.
//
// # Discussion
// 
// The array is a proxy object that is primarily intended for use with Cocoa
// bindings. While it is possible to copy the proxy array and receive a
// “snapshot” of the complete current query results, it is generally not
// recommended due to performance and memory issues. To access individual
// result array elements, use the [ResultCount] and [ResultAtIndex] methods.
// 
// The array supports [Key-value observing], which can be used to be notified
// when items are added, removed, or updated in the array of results.
// 
// By default, this array contains [NSMetadataItem] objects, each of which
// represents the metadata associated with a file. However, the query’s
// delegate can substitute these objects with instances of a different class.
//
// [Key-value observing]: https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html#//apple_ref/doc/uid/TP40008195-CH16
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/results
func (m NSMetadataQuery) Results() INSArray {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("results"))
	return NSArrayFromID(objc.ID(rv))
}
// The number of results returned by the query. (read-only)
//
// # Discussion
// 
// For performance reasons, you should use this method, rather than invoking
// `count` on [Results].
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/resultCount
func (m NSMetadataQuery) ResultCount() uint {
	rv := objc.Send[uint](m.ID, objc.Sel("resultCount"))
	return rv
}
// An array containing hierarchical groups of query results. (read-only)
//
// # Discussion
// 
// These groups are based on the receiver’s grouping attributes.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/groupedResults
func (m NSMetadataQuery) GroupedResults() []NSMetadataQueryResultGroup {
	rv := objc.Send[[]objc.ID](m.ID, objc.Sel("groupedResults"))
	return objc.ConvertSlice(rv, func(id objc.ID) NSMetadataQueryResultGroup {
		return NSMetadataQueryResultGroupFromID(id)
	})
}
// A dictionary containing the value lists generated by the query.
//
// # Discussion
// 
// This property contains a dictionary of [NSMetadataQueryAttributeValueTuple]
// objects.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/valueLists
func (m NSMetadataQuery) ValueLists() INSDictionary {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("valueLists"))
	return NSDictionaryFromID(objc.ID(rv))
}
// The queue on which query result notifications are posted.
//
// # Discussion
// 
// Use this property to decouple the processing of results from the thread
// used to execute the query. This makes it easier to synchronize query result
// processing with other related operations—such as updating the data model
// or user interface—which you might want to perform on the main queue.
//
// See: https://developer.apple.com/documentation/Foundation/NSMetadataQuery/operationQueue
func (m NSMetadataQuery) OperationQueue() INSOperationQueue {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("operationQueue"))
	return NSOperationQueueFromID(objc.ID(rv))
}
func (m NSMetadataQuery) SetOperationQueue(value INSOperationQueue) {
	objc.Send[struct{}](m.ID, objc.Sel("setOperationQueue:"), value)
}
// Posted when the receiver has finished with the initial result-gathering
// phase of the query.
//
// See: https://developer.apple.com/documentation/foundation/nsnotification/name-swift.struct/nsmetadataquerydidfinishgathering
func (m NSMetadataQuery) NSMetadataQueryDidFinishGathering() NSNotificationName {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("NSMetadataQueryDidFinishGatheringNotification"))
	return NSNotificationName(NSStringFromID(rv).String())
}
// Posted when the receiver begins with the initial result-gathering phase of
// the query.
//
// See: https://developer.apple.com/documentation/foundation/nsnotification/name-swift.struct/nsmetadataquerydidstartgathering
func (m NSMetadataQuery) NSMetadataQueryDidStartGathering() NSNotificationName {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("NSMetadataQueryDidStartGatheringNotification"))
	return NSNotificationName(NSStringFromID(rv).String())
}
// Posted when the receiver’s results have changed during the live-update
// phase of the query.
//
// See: https://developer.apple.com/documentation/foundation/nsnotification/name-swift.struct/nsmetadataquerydidupdate
func (m NSMetadataQuery) NSMetadataQueryDidUpdate() NSNotificationName {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("NSMetadataQueryDidUpdateNotification"))
	return NSNotificationName(NSStringFromID(rv).String())
}
// Posted as the receiver is collecting results during the initial
// result-gathering phase of the query.
//
// See: https://developer.apple.com/documentation/foundation/nsnotification/name-swift.struct/nsmetadataquerygatheringprogress
func (m NSMetadataQuery) NSMetadataQueryGatheringProgress() NSNotificationName {
	rv := objc.Send[objc.ID](m.ID, objc.Sel("NSMetadataQueryGatheringProgressNotification"))
	return NSNotificationName(NSStringFromID(rv).String())
}

// EnumerateResultsUsingBlockSync is a synchronous wrapper around [NSMetadataQuery.EnumerateResultsUsingBlock].
// It blocks until the completion handler fires or the context is cancelled.
func (m NSMetadataQuery) EnumerateResultsUsingBlockSync(ctx context.Context) (objectivec.IObject, error) {
	done := make(chan objectivec.IObject, 1)
	m.EnumerateResultsUsingBlock(func(val objectivec.IObject) {
		done <- val
	})
	select {
	case r := <-done:
		return r, nil
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// EnumerateResultsWithOptionsUsingBlockSync is a synchronous wrapper around [NSMetadataQuery.EnumerateResultsWithOptionsUsingBlock].
// It blocks until the completion handler fires or the context is cancelled.
func (m NSMetadataQuery) EnumerateResultsWithOptionsUsingBlockSync(ctx context.Context, opts NSEnumerationOptions) (objectivec.IObject, error) {
	done := make(chan objectivec.IObject, 1)
	m.EnumerateResultsWithOptionsUsingBlock(opts, func(val objectivec.IObject) {
		done <- val
	})
	select {
	case r := <-done:
		return r, nil
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

