// Code generated from Apple documentation for Foundation. DO NOT EDIT.
//go:build ios
// +build ios

package foundation

import (
	"github.com/tmc/apple/objc"
)

// An object containing the payload information that launches an App Clip.
//
// # Discussion
//
// When your App Clip launches, use the activation payload to verify a
// user’s location. For more information, see [Responding to invocations].
//
// See: https://developer.apple.com/documentation/Foundation/NSUserActivity/appClipActivationPayload
//
// [Responding to invocations]: https://developer.apple.com/documentation/AppClip/responding-to-invocations
func (u NSUserActivity) AppClipActivationPayload() unsafe.Pointer {
	rv := objc.Send[unsafe.Pointer](u.ID, objc.Sel("appClipActivationPayload"))
	return rv
}

// A Boolean value that determines whether Siri can suggest the user activity
// as a shortcut to the user.
//
// # Discussion
//
// To donate a user activity to Siri Shortcuts, set [EligibleForPrediction] to
// true and make the user activity current. To make the user activity current,
// call the activity’s [BecomeCurrent] method, or assign it to the
// [userActivity] property on a [UIViewController] or [UIResponder] object.
// For more information, see [Donating Shortcuts].
//
// See: https://developer.apple.com/documentation/Foundation/NSUserActivity/isEligibleForPrediction
//
// [Donating Shortcuts]: https://developer.apple.com/documentation/SiriKit/donating-shortcuts
// [UIResponder]: https://developer.apple.com/documentation/UIKit/UIResponder
// [UIViewController]: https://developer.apple.com/documentation/UIKit/UIViewController
// [userActivity]: https://developer.apple.com/documentation/UIKit/UIResponder/userActivity
func (u NSUserActivity) EligibleForPrediction() bool {
	rv := objc.Send[bool](u.ID, objc.Sel("isEligibleForPrediction"))
	return rv
}
func (u NSUserActivity) SetEligibleForPrediction(value bool) {
	objc.Send[struct{}](u.ID, objc.Sel("setEligibleForPrediction:"), value)
}

// A set of defined contexts in which an intent or activity might be relevant
// to a user.
//
// # Discussion
//
// When you donate an activity, include a set of relevant
// [INShortcutAvailabilityOptions] to describe appropriate categories for
// offering a shortcut to the activity.
//
// If none of the availability options apply to your intent, use the empty
// set. The empty set is the default value for this property.
//
// See: https://developer.apple.com/documentation/Foundation/NSUserActivity/shortcutAvailability
//
// [INShortcutAvailabilityOptions]: https://developer.apple.com/documentation/Intents/INShortcutAvailabilityOptions
func (u NSUserActivity) ShortcutAvailability() uint {
	rv := objc.Send[uint](u.ID, objc.Sel("shortcutAvailability"))
	return rv
}
func (u NSUserActivity) SetShortcutAvailability(value uint) {
	objc.Send[struct{}](u.ID, objc.Sel("setShortcutAvailability:"), value)
}

// The NDEF message read by the system in the background.
//
// # Discussion
//
// For user activities not generated by background tag reading,
// [NdefMessagePayload] returns a message that contains only one
// [NFCNDEFPayload] record. That record has a [typeNameFormat] of
// [NFCTypeNameFormat.empty]. For more information, see [Adding Support for
// Background Tag Reading].
//
// See: https://developer.apple.com/documentation/Foundation/NSUserActivity/ndefMessagePayload
//
// [Adding Support for Background Tag Reading]: https://developer.apple.com/documentation/CoreNFC/adding-support-for-background-tag-reading
// [NFCNDEFPayload]: https://developer.apple.com/documentation/CoreNFC/NFCNDEFPayload
// [NFCTypeNameFormat.empty]: https://developer.apple.com/documentation/CoreNFC/NFCTypeNameFormat/empty
// [typeNameFormat]: https://developer.apple.com/documentation/CoreNFC/NFCNDEFPayload/typeNameFormat
func (u NSUserActivity) NdefMessagePayload() unsafe.Pointer {
	rv := objc.Send[unsafe.Pointer](u.ID, objc.Sel("ndefMessagePayload"))
	return rv
}

// A unique identifier from the app’s media content catalog for the
// currently displayed media item.
//
// See: https://developer.apple.com/documentation/Foundation/NSUserActivity/externalMediaContentIdentifier
func (u NSUserActivity) ExternalMediaContentIdentifier() string {
	rv := objc.Send[objc.ID](u.ID, objc.Sel("externalMediaContentIdentifier"))
	return NSStringFromID(rv).String()
}
func (u NSUserActivity) SetExternalMediaContentIdentifier(value string) {
	objc.Send[struct{}](u.ID, objc.Sel("setExternalMediaContentIdentifier:"), objc.String(value))
}
