// Code generated from Apple documentation. DO NOT EDIT.

package coregraphics

import (
	"unsafe"
	"github.com/tmc/apple/corefoundation"
)

// CGBitmapContextReleaseDataCallback is a callback function used to release data associate with the bitmap context.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGBitmapContextReleaseDataCallback
type CGBitmapContextReleaseDataCallback = func(unsafe.Pointer, unsafe.Pointer)

// CGButtonCount is represents the number of buttons being set in a synthetic mouse event.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGButtonCount
type CGButtonCount = uint32

// CGCharCode is represents a character generated by pressing one or more keys on a keyboard.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGCharCode
type CGCharCode = uint16

// CGColorConversionInfoRef is an object that describes how to convert between color spaces for use by other system services.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGColorConversionInfo
type CGColorConversionInfoRef uintptr

// CGColorRef is a set of components that define a color, with a color space specifying how to interpret them.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGColor
type CGColorRef uintptr

// CGColorSpaceRef is a profile that specifies how to interpret a color value for display.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGColorSpace
type CGColorSpaceRef uintptr

// CGContextRef is a Quartz 2D drawing environment.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGContext
type CGContextRef uintptr

// CGDataConsumerPutBytesCallback is copies data from a Core Graphics-supplied buffer into a data consumer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataConsumerPutBytesCallback
type CGDataConsumerPutBytesCallback = func(unsafe.Pointer, unsafe.Pointer, uint) uint

// CGDataConsumerRef is an abstraction for data-writing tasks that eliminates the need to manage a raw memory buffer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataConsumer
type CGDataConsumerRef uintptr

// CGDataConsumerReleaseInfoCallback is releases any private data or resources associated with the data consumer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataConsumerReleaseInfoCallback
type CGDataConsumerReleaseInfoCallback = func(unsafe.Pointer)

// CGDataProviderGetBytePointerCallback is a callback function that returns a generic pointer to the provider data.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderGetBytePointerCallback
type CGDataProviderGetBytePointerCallback = func(unsafe.Pointer) unsafe.Pointer

// CGDataProviderGetBytesAtPositionCallback is a callback function that copies data from the provider into a Core Graphics buffer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderGetBytesAtPositionCallback
type CGDataProviderGetBytesAtPositionCallback = func(unsafe.Pointer, unsafe.Pointer, int64, uint) uint

// CGDataProviderGetBytesCallback is a callback function that copies from a provider data stream into a Core Graphics buffer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderGetBytesCallback
type CGDataProviderGetBytesCallback = func(unsafe.Pointer, unsafe.Pointer, uint) uint

// CGDataProviderRef is an abstraction for data-reading tasks that eliminates the need to manage a raw memory buffer.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProvider
type CGDataProviderRef uintptr

// CGDataProviderReleaseBytePointerCallback is a callback function that releases the pointer Core Graphics obtained by calling [CGDataProviderGetBytePointerCallback].
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderReleaseBytePointerCallback
type CGDataProviderReleaseBytePointerCallback = func(unsafe.Pointer, unsafe.Pointer)

// CGDataProviderReleaseDataCallback is a callback function that releases data you supply to the function [init(dataInfo:data:size:releaseData:)].
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderReleaseDataCallback
type CGDataProviderReleaseDataCallback = func(unsafe.Pointer, unsafe.Pointer, uint)

// CGDataProviderReleaseInfoCallback is a callback function that releases any private data or resources associated with the data provider.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderReleaseInfoCallback
type CGDataProviderReleaseInfoCallback = func(unsafe.Pointer)

// CGDataProviderRewindCallback is a callback function that moves the current position in the data stream back to the beginning.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderRewindCallback
type CGDataProviderRewindCallback = func(unsafe.Pointer)

// CGDataProviderSkipForwardCallback is a callback function that advances the current position in the data stream supplied by the provider.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDataProviderSkipForwardCallback
type CGDataProviderSkipForwardCallback = func(unsafe.Pointer, int64) int64

// CGDirectDisplayID is a unique identifier for an attached display.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDirectDisplayID
type CGDirectDisplayID = uint32

// CGDisplayBlendFraction is the percentage of blend color used in a fade operation.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayBlendFraction
type CGDisplayBlendFraction = float32

// CGDisplayConfigRef is a reference to a display configuration transaction.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayConfigRef
type CGDisplayConfigRef uintptr

// CGDisplayFadeInterval is the duration in seconds of a fade operation or a fade hardware reservation.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayFadeInterval
type CGDisplayFadeInterval = float32

// CGDisplayFadeReservationToken is a token issued by Quartz when reserving one or more displays for a fade operation during a specified interval.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayFadeReservationToken
type CGDisplayFadeReservationToken = uint32

// CGDisplayModeRef is a reference to a display mode object.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayMode
type CGDisplayModeRef uintptr

// CGDisplayReconfigurationCallBack is a client-supplied callback function that’s invoked whenever the configuration of a local display is changed.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayReconfigurationCallBack
type CGDisplayReconfigurationCallBack = func(uint, uint, unsafe.Pointer)

// CGDisplayReservationInterval is the time interval for a fade reservation.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayReservationInterval
type CGDisplayReservationInterval = float32

// CGDisplayStreamFrameAvailableHandler is a block called when a data stream has a new frame event to process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayStreamFrameAvailableHandler
type CGDisplayStreamFrameAvailableHandler = func(CGDisplayStreamFrameStatus, uint64, IOSurfaceRef, *CGDisplayStreamUpdateRef)

// CGDisplayStreamRef is a reference to a display stream object.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayStream
type CGDisplayStreamRef uintptr

// CGDisplayStreamUpdateRef is a reference to frame update’s metadata.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGDisplayStreamUpdate
type CGDisplayStreamUpdateRef uintptr

// See: https://developer.apple.com/documentation/CoreGraphics/CGErrorCallback
type CGErrorCallback = func()

// See: https://developer.apple.com/documentation/CoreGraphics/CGEventErr
type CGEventErr = unsafe.Pointer

// CGEventMask is defines a mask that identifies the set of Quartz events to be observed in an event tap.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventMask
type CGEventMask = uint64

// CGEventRef is defines an opaque type that represents a low-level hardware event.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEvent
type CGEventRef uintptr

// CGEventSourceKeyboardType is defines a code that represents the type of keyboard used with a specified event source.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventSourceKeyboardType
type CGEventSourceKeyboardType = uint32

// CGEventSourceRef is defines an opaque type that represents the source of a Quartz event.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventSource
type CGEventSourceRef uintptr

// CGEventTapCallBack is a client-supplied callback function that’s invoked whenever an associated event tap receives a Quartz event.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventTapCallBack
type CGEventTapCallBack = func(uintptr, CGEventType, uintptr, unsafe.Pointer) uintptr

// CGEventTapInformation is defines the structure used to report information about event taps.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventTapInformation
type CGEventTapInformation = unsafe.Pointer

// CGEventTapProxy is defines an opaque type that represents state within the client application that’s associated with an event tap.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventTapProxy
type CGEventTapProxy = uintptr

// CGEventTimestamp is defines the elapsed time in nanoseconds since startup that a Quartz event occurred.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGEventTimestamp
type CGEventTimestamp = uint64

// CGFontIndex is an index into a font table.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGFontIndex
type CGFontIndex = uint16

// CGFontRef is a set of character glyphs and layout information for drawing text.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGFont
type CGFontRef uintptr

// CGFunctionEvaluateCallback is performs custom operations on the supplied input data to produce output data.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGFunctionEvaluateCallback
type CGFunctionEvaluateCallback = func(unsafe.Pointer, []float64, []float64)

// CGFunctionRef is a general facility for defining and using callback functions.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGFunction
type CGFunctionRef uintptr

// CGFunctionReleaseInfoCallback is performs custom clean-up tasks when Core Graphics deallocates a [CGFunctionRef] object.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGFunctionReleaseInfoCallback
type CGFunctionReleaseInfoCallback = func(unsafe.Pointer)

// CGGammaValue is a value used to map a color generated in software to a color supported by the display hardware.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGGammaValue
type CGGammaValue = float32

// CGGlyph is an index into the internal glyph table of a font.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGGlyph
type CGGlyph = unsafe.Pointer

// CGGradientRef is a definition for a smooth transition between colors for drawing radial and axial gradient fills.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGGradient
type CGGradientRef uintptr

// CGImageRef is a bitmap image or image mask.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGImage
type CGImageRef uintptr

// CGKeyCode is represents the virtual key codes used in keyboard events.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGKeyCode
type CGKeyCode = uint16

// CGLayerRef is an offscreen context for reusing content drawn with Core Graphics.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGLayer
type CGLayerRef uintptr

// CGMutablePathRef is a mutable graphics path: a mathematical description of shapes or lines to be drawn in a graphics context.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGMutablePath
type CGMutablePathRef uintptr

// CGOpenGLDisplayMask is a bitmask used in OpenGL to specify a set of attached displays.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGOpenGLDisplayMask
type CGOpenGLDisplayMask = uint32

// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFArrayApplierBlock
type CGPDFArrayApplierBlock = func(uint32, *CGPDFObjectRef, unsafe.Pointer) bool

// CGPDFArrayRef is an opaque type that encapsulates a PDF array.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFArrayRef
type CGPDFArrayRef uintptr

// CGPDFBoolean is a PDF Boolean value.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFBoolean
type CGPDFBoolean = uint8

// CGPDFContentStreamRef is an opaque type that provides access to the data that describes the appearance of a PDF page.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFContentStreamRef
type CGPDFContentStreamRef uintptr

// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFDictionaryApplierBlock
type CGPDFDictionaryApplierBlock = func([]byte, *CGPDFObjectRef, unsafe.Pointer) bool

// CGPDFDictionaryApplierFunction is performs custom processing on a key-value pair from a PDF dictionary, using optional contextual information.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFDictionaryApplierFunction
type CGPDFDictionaryApplierFunction = func(*byte, uintptr, unsafe.Pointer)

// CGPDFDictionaryRef is a type that encapsulates a PDF dictionary.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFDictionaryRef
type CGPDFDictionaryRef uintptr

// CGPDFDocumentRef is a document that contains PDF (Portable Document Format) drawing information.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFDocument
type CGPDFDocumentRef uintptr

// CGPDFInteger is a PDF integer value.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFInteger
type CGPDFInteger = int

// CGPDFObjectRef is a type that contains information about a PDF object.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFObjectRef
type CGPDFObjectRef uintptr

// CGPDFOperatorCallback is performs custom processing for PDF operators.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFOperatorCallback
type CGPDFOperatorCallback = func(uintptr, unsafe.Pointer)

// CGPDFOperatorTableRef is a type that stores callback functions for PDF operators.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFOperatorTableRef
type CGPDFOperatorTableRef uintptr

// CGPDFPageRef is a type that represents a page in a PDF document.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFPage
type CGPDFPageRef uintptr

// CGPDFReal is a PDF real value.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFReal
type CGPDFReal = float64

// CGPDFScannerRef is a type used to parse a PDF content stream.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFScannerRef
type CGPDFScannerRef uintptr

// CGPDFStreamRef is a type that represents a PDF stream.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFStreamRef
type CGPDFStreamRef uintptr

// CGPDFStringRef is a data type that represents a string in a PDF document.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFStringRef
type CGPDFStringRef uintptr

// See: https://developer.apple.com/documentation/CoreGraphics/CGPDFTagProperty
type CGPDFTagProperty = corefoundation.CFStringRef

// CGPSConverterBeginDocumentCallback is performs custom tasks at the beginning of a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterBeginDocumentCallback
type CGPSConverterBeginDocumentCallback = func(unsafe.Pointer)

// CGPSConverterBeginPageCallback is performs custom tasks at the beginning of each page in a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterBeginPageCallback
type CGPSConverterBeginPageCallback = func(unsafe.Pointer, uint, uintptr)

// CGPSConverterEndDocumentCallback is performs custom tasks at the end of a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterEndDocumentCallback
type CGPSConverterEndDocumentCallback = func(unsafe.Pointer, bool)

// CGPSConverterEndPageCallback is performs custom tasks at the end of each page of a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterEndPageCallback
type CGPSConverterEndPageCallback = func(unsafe.Pointer, uint, uintptr)

// CGPSConverterMessageCallback is passes messages generated during a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterMessageCallback
type CGPSConverterMessageCallback = func(unsafe.Pointer, uintptr)

// CGPSConverterProgressCallback is reports progress periodically during a PostScript conversion process.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterProgressCallback
type CGPSConverterProgressCallback = func(unsafe.Pointer)

// CGPSConverterRef is an opaque data type used to convert PostScript data to PDF data.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverter
type CGPSConverterRef uintptr

// CGPSConverterReleaseInfoCallback is performs custom tasks when a PostScript converter is released.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPSConverterReleaseInfoCallback
type CGPSConverterReleaseInfoCallback = func(unsafe.Pointer)

// CGPathApplierFunction is defines a callback function that can view an element in a graphics path.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPathApplierFunction
type CGPathApplierFunction = func(unsafe.Pointer, uintptr)

// See: https://developer.apple.com/documentation/CoreGraphics/CGPathApplyBlock
type CGPathApplyBlock = func(*CGPathElement)

// CGPathRef is an immutable graphics path: a mathematical description of shapes or lines to be drawn in a graphics context.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPath
type CGPathRef uintptr

// CGPatternDrawPatternCallback is draws a pattern cell.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPatternDrawPatternCallback
type CGPatternDrawPatternCallback = func(unsafe.Pointer, uintptr)

// CGPatternRef is a 2D pattern to be used for drawing graphics paths.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPattern
type CGPatternRef uintptr

// CGPatternReleaseInfoCallback is release private data or resources associated with the pattern.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGPatternReleaseInfoCallback
type CGPatternReleaseInfoCallback = func(unsafe.Pointer)

// CGRectCount is the size of an array of Quartz rectangles.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGRectCount
type CGRectCount = uint32

// CGRefreshRate is a display’s refresh rate in frames per second.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGRefreshRate
type CGRefreshRate = float64

// See: https://developer.apple.com/documentation/CoreGraphics/CGRenderingBufferProvider
type CGRenderingBufferProviderRef uintptr

// CGScreenRefreshCallback is a client-supplied callback function that’s invoked when an area of the display is modified or refreshed.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGScreenRefreshCallback
type CGScreenRefreshCallback = func(uint, uintptr, unsafe.Pointer)

// CGScreenUpdateMoveCallback is a client-supplied callback function invoked when an area of the display is moved.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGScreenUpdateMoveCallback
type CGScreenUpdateMoveCallback = func(CGScreenUpdateMoveDelta, uint, uintptr, unsafe.Pointer)

// CGShadingRef is a definition for a smooth transition between colors, controlled by a custom function you provide, for drawing radial and axial gradient fills.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGShading
type CGShadingRef uintptr

// CGWheelCount is represents the number of wheels being set in a scroll wheel event.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGWheelCount
type CGWheelCount = uint32

// CGWindowID is the data type used to store window identifiers.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGWindowID
type CGWindowID = uint32

// CGWindowLevel is a level assigned to a window by an application framework.
//
// See: https://developer.apple.com/documentation/CoreGraphics/CGWindowLevel
type CGWindowLevel = int32

// See: https://developer.apple.com/documentation/CoreGraphics/ColorSyncProfile
type ColorSyncProfileRef uintptr

// See: https://developer.apple.com/documentation/CoreGraphics/IOSurfaceRef
type IOSurfaceRef uintptr

// CGEvent is an opaque Core Graphics event reference type.

type CGEvent = CGEventRef

// CGFont is a bare alias for CGFontRef.

type CGFont = CGFontRef

