//go:build darwin

// Package mil generates MIL (Model Intermediate Language) programs and weight
// blobs for Apple Neural Engine compilation.
//
//	text := mil.GenConv(16, 16, 1)
//	blob, _ := mil.BuildWeightBlob(weights, 16, 16)
//
// # Static control flow
//
// The following describes the engine's execution model as reported by
// Bryngelson, "Apple Neural Engine", arXiv 2606.22283, §2.5 ("A walked graph,
// not a decoded stream"). It is documented here because it constrains what a
// program generated by this package may express. It has not been independently
// verified by this package; treat it as the paper's claim.
//
// A compiled program is a static graph of work segments that the hardware
// walks, not an instruction stream a processor decodes. The compiler fixes the
// order and shape of every segment ahead of time. Consequences for a caller:
//
//   - Control flow must be static. The graph shape is decided at compile time,
//     so the work the engine performs cannot depend on values computed during
//     the run.
//   - Data-dependent branching does not execute on the engine; no path through
//     the graph selects itself from a runtime value. A network that needs one
//     must resolve it on the host, or restructure it so the branch becomes a
//     fixed computation, such as a mask applied to both sides rather than a
//     choice between them.
//   - A loop with a fixed trip count unrolls into a fixed graph and is
//     admissible. A loop whose length depends on the data is not.
//   - There is no readable instruction trace and no program counter, which is
//     why no host-side debugger view of a running program exists.
//
// # Compile-time limits
//
// Limits from §19 ("Pitfalls and limits") that a caller of this package can hit
// while generating and compiling a program, again per the paper and not
// verified here:
//
//   - Symbolic shapes: a tensor with an unknown dimension parses but fails to
//     compile on the unentitled direct path. Compile per concrete shape, and
//     pad, bucket, or recompile per length (§19.10).
//   - Dynamic-weight convolution compiles only at batch one; batch two or more
//     fails to compile (§19.9).
//   - A direct image input declaring a four-character-code interchange format
//     fails at backend lowering on the direct path; the uint8 in-graph image
//     input is the supported form (§19.6).
//   - A failed compile restarts the shared compile service. Pace compiles after
//     a failure by roughly 15 seconds so a burst of failures cannot accumulate
//     (§19.4).
//   - Compile time, not just run time, can blow up: a trainable convolution's
//     compile cost scales with batch, and a cluster with roughly twelve or more
//     parallel branches reconverging into one consumer drives a super-linear
//     cut search (§19.5).
//
// TODO: none of the above has been checked against a running system by this
// package. Verify each limit before relying on it as a validation rule.
package mil
