// Code generated from Apple documentation for Metal. DO NOT EDIT.

package metal

import (
	"sync"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [MTLRenderPassDescriptor] class.
var (
	_MTLRenderPassDescriptorClass     MTLRenderPassDescriptorClass
	_MTLRenderPassDescriptorClassOnce sync.Once
)

func getMTLRenderPassDescriptorClass() MTLRenderPassDescriptorClass {
	_MTLRenderPassDescriptorClassOnce.Do(func() {
		_MTLRenderPassDescriptorClass = MTLRenderPassDescriptorClass{class: objc.GetClass("MTLRenderPassDescriptor")}
	})
	return _MTLRenderPassDescriptorClass
}

// GetMTLRenderPassDescriptorClass returns the class object for MTLRenderPassDescriptor.
func GetMTLRenderPassDescriptorClass() MTLRenderPassDescriptorClass {
	return getMTLRenderPassDescriptorClass()
}

type MTLRenderPassDescriptorClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (mc MTLRenderPassDescriptorClass) Class() objc.Class {
	return mc.class
}

// Alloc allocates memory for a new instance of the class.
func (mc MTLRenderPassDescriptorClass) Alloc() MTLRenderPassDescriptor {
	rv := objc.Send[MTLRenderPassDescriptor](objc.ID(mc.class), objc.Sel("alloc"))
	return rv
}

// A group of render targets that hold the results of a render pass.
//
// # Overview
// 
// An [MTLRenderPassDescriptor] instance contains a collection of attachments
// used as the rendering destination for pixels generated by a rendering pass.
// The [MTLRenderPassDescriptor] instance also sets the destination buffer for
// visibility information generated by a rendering pass.
//
// # Specifying the attachments for a rendering pass
//
//   - [MTLRenderPassDescriptor.ColorAttachments]: An array of state information for attachments that store color data.
//   - [MTLRenderPassDescriptor.DepthAttachment]: State information for an attachment that stores depth data.
//   - [MTLRenderPassDescriptor.SetDepthAttachment]
//   - [MTLRenderPassDescriptor.StencilAttachment]: State information for an attachment that stores stencil data.
//   - [MTLRenderPassDescriptor.SetStencilAttachment]
//
// # Specifying the visibility result buffer
//
//   - [MTLRenderPassDescriptor.VisibilityResultBuffer]: A buffer where the GPU writes visibility test results when fragments pass depth and stencil tests.
//   - [MTLRenderPassDescriptor.SetVisibilityResultBuffer]
//
// # Layered rendering
//
//   - [MTLRenderPassDescriptor.RenderTargetArrayLength]: The number of active layers that all attachments need to have for layered rendering.
//   - [MTLRenderPassDescriptor.SetRenderTargetArrayLength]
//   - [MTLRenderPassDescriptor.RenderTargetWidth]: The width, in pixels, to constrain the render target to.
//   - [MTLRenderPassDescriptor.SetRenderTargetWidth]
//   - [MTLRenderPassDescriptor.RenderTargetHeight]: The height, in pixels, to constrain the render target to.
//   - [MTLRenderPassDescriptor.SetRenderTargetHeight]
//
// # Specifying tile shading parameters
//
//   - [MTLRenderPassDescriptor.ImageblockSampleLength]: The per-sample size, in bytes, of the largest explicit imageblock layout in the render pass.
//   - [MTLRenderPassDescriptor.SetImageblockSampleLength]
//   - [MTLRenderPassDescriptor.ThreadgroupMemoryLength]: The per-tile size, in bytes, of the persistent threadgroup memory allocation.
//   - [MTLRenderPassDescriptor.SetThreadgroupMemoryLength]
//   - [MTLRenderPassDescriptor.TileWidth]: The tile width, in pixels.
//   - [MTLRenderPassDescriptor.SetTileWidth]
//   - [MTLRenderPassDescriptor.TileHeight]: The tile height, in pixels.
//   - [MTLRenderPassDescriptor.SetTileHeight]
//
// # Specifying sample counts
//
//   - [MTLRenderPassDescriptor.DefaultRasterSampleCount]: The raster sample count for the render pass when the render pass doesn’t have explicit attachments.
//   - [MTLRenderPassDescriptor.SetDefaultRasterSampleCount]
//
// # Specifying a rasterization rate map
//
//   - [MTLRenderPassDescriptor.RasterizationRateMap]: The rasterization rate map to use when executing the render pass.
//   - [MTLRenderPassDescriptor.SetRasterizationRateMap]
//
// # Specifying sample buffers for GPU counters
//
//   - [MTLRenderPassDescriptor.SampleBufferAttachments]: The array of sample buffers that the render pass can access.
//
// # Instance Properties
//
//   - [MTLRenderPassDescriptor.SupportColorAttachmentMapping]: Specifies if the render pass should support color attachment mapping.
//   - [MTLRenderPassDescriptor.SetSupportColorAttachmentMapping]
//   - [MTLRenderPassDescriptor.VisibilityResultType]: Specifies if Metal accumulates visibility results between render encoders or resets them.
//   - [MTLRenderPassDescriptor.SetVisibilityResultType]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor
type MTLRenderPassDescriptor struct {
	objectivec.Object
}

// MTLRenderPassDescriptorFromID constructs a [MTLRenderPassDescriptor] from an objc.ID.
//
// A group of render targets that hold the results of a render pass.
func MTLRenderPassDescriptorFromID(id objc.ID) MTLRenderPassDescriptor {
	return MTLRenderPassDescriptor{objectivec.Object{ID: id}}
}
// NOTE: MTLRenderPassDescriptor adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [MTLRenderPassDescriptor] class.
//
// # Specifying the attachments for a rendering pass
//
//   - [IMTLRenderPassDescriptor.ColorAttachments]: An array of state information for attachments that store color data.
//   - [IMTLRenderPassDescriptor.DepthAttachment]: State information for an attachment that stores depth data.
//   - [IMTLRenderPassDescriptor.SetDepthAttachment]
//   - [IMTLRenderPassDescriptor.StencilAttachment]: State information for an attachment that stores stencil data.
//   - [IMTLRenderPassDescriptor.SetStencilAttachment]
//
// # Specifying the visibility result buffer
//
//   - [IMTLRenderPassDescriptor.VisibilityResultBuffer]: A buffer where the GPU writes visibility test results when fragments pass depth and stencil tests.
//   - [IMTLRenderPassDescriptor.SetVisibilityResultBuffer]
//
// # Layered rendering
//
//   - [IMTLRenderPassDescriptor.RenderTargetArrayLength]: The number of active layers that all attachments need to have for layered rendering.
//   - [IMTLRenderPassDescriptor.SetRenderTargetArrayLength]
//   - [IMTLRenderPassDescriptor.RenderTargetWidth]: The width, in pixels, to constrain the render target to.
//   - [IMTLRenderPassDescriptor.SetRenderTargetWidth]
//   - [IMTLRenderPassDescriptor.RenderTargetHeight]: The height, in pixels, to constrain the render target to.
//   - [IMTLRenderPassDescriptor.SetRenderTargetHeight]
//
// # Specifying tile shading parameters
//
//   - [IMTLRenderPassDescriptor.ImageblockSampleLength]: The per-sample size, in bytes, of the largest explicit imageblock layout in the render pass.
//   - [IMTLRenderPassDescriptor.SetImageblockSampleLength]
//   - [IMTLRenderPassDescriptor.ThreadgroupMemoryLength]: The per-tile size, in bytes, of the persistent threadgroup memory allocation.
//   - [IMTLRenderPassDescriptor.SetThreadgroupMemoryLength]
//   - [IMTLRenderPassDescriptor.TileWidth]: The tile width, in pixels.
//   - [IMTLRenderPassDescriptor.SetTileWidth]
//   - [IMTLRenderPassDescriptor.TileHeight]: The tile height, in pixels.
//   - [IMTLRenderPassDescriptor.SetTileHeight]
//
// # Specifying sample counts
//
//   - [IMTLRenderPassDescriptor.DefaultRasterSampleCount]: The raster sample count for the render pass when the render pass doesn’t have explicit attachments.
//   - [IMTLRenderPassDescriptor.SetDefaultRasterSampleCount]
//
// # Specifying a rasterization rate map
//
//   - [IMTLRenderPassDescriptor.RasterizationRateMap]: The rasterization rate map to use when executing the render pass.
//   - [IMTLRenderPassDescriptor.SetRasterizationRateMap]
//
// # Specifying sample buffers for GPU counters
//
//   - [IMTLRenderPassDescriptor.SampleBufferAttachments]: The array of sample buffers that the render pass can access.
//
// # Instance Properties
//
//   - [IMTLRenderPassDescriptor.SupportColorAttachmentMapping]: Specifies if the render pass should support color attachment mapping.
//   - [IMTLRenderPassDescriptor.SetSupportColorAttachmentMapping]
//   - [IMTLRenderPassDescriptor.VisibilityResultType]: Specifies if Metal accumulates visibility results between render encoders or resets them.
//   - [IMTLRenderPassDescriptor.SetVisibilityResultType]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor
type IMTLRenderPassDescriptor interface {
	objectivec.IObject

	// Topic: Specifying the attachments for a rendering pass

	// An array of state information for attachments that store color data.
	ColorAttachments() IMTLRenderPassColorAttachmentDescriptorArray
	// State information for an attachment that stores depth data.
	DepthAttachment() IMTLRenderPassDepthAttachmentDescriptor
	SetDepthAttachment(value IMTLRenderPassDepthAttachmentDescriptor)
	// State information for an attachment that stores stencil data.
	StencilAttachment() IMTLRenderPassStencilAttachmentDescriptor
	SetStencilAttachment(value IMTLRenderPassStencilAttachmentDescriptor)

	// Topic: Specifying the visibility result buffer

	// A buffer where the GPU writes visibility test results when fragments pass depth and stencil tests.
	VisibilityResultBuffer() MTLBuffer
	SetVisibilityResultBuffer(value MTLBuffer)

	// Topic: Layered rendering

	// The number of active layers that all attachments need to have for layered rendering.
	RenderTargetArrayLength() uint
	SetRenderTargetArrayLength(value uint)
	// The width, in pixels, to constrain the render target to.
	RenderTargetWidth() uint
	SetRenderTargetWidth(value uint)
	// The height, in pixels, to constrain the render target to.
	RenderTargetHeight() uint
	SetRenderTargetHeight(value uint)

	// Topic: Specifying tile shading parameters

	// The per-sample size, in bytes, of the largest explicit imageblock layout in the render pass.
	ImageblockSampleLength() uint
	SetImageblockSampleLength(value uint)
	// The per-tile size, in bytes, of the persistent threadgroup memory allocation.
	ThreadgroupMemoryLength() uint
	SetThreadgroupMemoryLength(value uint)
	// The tile width, in pixels.
	TileWidth() uint
	SetTileWidth(value uint)
	// The tile height, in pixels.
	TileHeight() uint
	SetTileHeight(value uint)

	// Topic: Specifying sample counts

	// The raster sample count for the render pass when the render pass doesn’t have explicit attachments.
	DefaultRasterSampleCount() uint
	SetDefaultRasterSampleCount(value uint)

	// Topic: Specifying a rasterization rate map

	// The rasterization rate map to use when executing the render pass.
	RasterizationRateMap() MTLRasterizationRateMap
	SetRasterizationRateMap(value MTLRasterizationRateMap)

	// Topic: Specifying sample buffers for GPU counters

	// The array of sample buffers that the render pass can access.
	SampleBufferAttachments() IMTLRenderPassSampleBufferAttachmentDescriptorArray

	// Topic: Instance Properties

	// Specifies if the render pass should support color attachment mapping.
	SupportColorAttachmentMapping() bool
	SetSupportColorAttachmentMapping(value bool)
	// Specifies if Metal accumulates visibility results between render encoders or resets them.
	VisibilityResultType() MTLVisibilityResultType
	SetVisibilityResultType(value MTLVisibilityResultType)

	// An option for rendering to the texture in a render pass.
	RenderTarget() MTLTextureUsage
	SetRenderTarget(value MTLTextureUsage)
	// Options that determine how you can use the texture.
	Usage() MTLTextureUsage
	SetUsage(value MTLTextureUsage)
	// Retrieves the programmable sample positions set for a render pass.
	GetSamplePositionsCount(positions []MTLSamplePosition, count uint) uint
	// Sets the programmable sample positions for a render pass.
	SetSamplePositionsCount(positions []MTLSamplePosition, count uint)
}

// Init initializes the instance.
func (r MTLRenderPassDescriptor) Init() MTLRenderPassDescriptor {
	rv := objc.Send[MTLRenderPassDescriptor](r.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (r MTLRenderPassDescriptor) Autorelease() MTLRenderPassDescriptor {
	rv := objc.Send[MTLRenderPassDescriptor](r.ID, objc.Sel("autorelease"))
	return rv
}

// NewMTLRenderPassDescriptor creates a new MTLRenderPassDescriptor instance.
func NewMTLRenderPassDescriptor() MTLRenderPassDescriptor {
	class := getMTLRenderPassDescriptorClass()
	rv := objc.Send[MTLRenderPassDescriptor](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Retrieves the programmable sample positions set for a render pass.
//
// positions: A pointer to a destination array of sample positions where Metal writes the
// programmable sample positions.
//
// count: The number of programmable sample positions to retrieve.
//
// # Return Value
// 
// The total number of programmable sample positions set for the render pass.
//
// # Discussion
// 
// The value of `count` needs to be equal to the number of programmable sample
// positions set by a previous call to the [SetSamplePositionsCount] method
// (the `count` parameter). Also, the `positions` array needs to contain at
// least as many elements as the value of `count`.
// 
// If you don’t know the correct value for `count`, you may query this
// method by passing a `nil` array for `positions` and a `0` value for
// `count`. This method returns the number of programmable sample positions
// that are currently set.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/getSamplePositions:count:
func (r MTLRenderPassDescriptor) GetSamplePositionsCount(positions []MTLSamplePosition, count uint) uint {
	rv := objc.Send[uint](r.ID, objc.Sel("getSamplePositions:count:"), objc.CArray(positions), count)
	return rv
}
// Sets the programmable sample positions for a render pass.
//
// positions: An array of programmable sample positions for the render pass.
//
// count: The number of elements, which needs to match the render pass sample count,
// or `0` to disable custom sample positions.
//
// # Discussion
// 
// Programmable sample positions need to be floating-point values in the
// `[0.0, 1.0)` range along each axis, with the origin `(0,0)` defined at the
// top-left corner. Values can be set from `0/16` up to `15/16`, inclusive, in
// 1`/16` increments along each axis.
// 
// If the value of `count` is `0`, the GPU uses the default sample positions
// for the render pass.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/setSamplePositions:count:
func (r MTLRenderPassDescriptor) SetSamplePositionsCount(positions []MTLSamplePosition, count uint) {
	objc.Send[objc.ID](r.ID, objc.Sel("setSamplePositions:count:"), objc.CArray(positions), count)
}

// Creates a default render pass descriptor.
//
// # Return Value
// 
// A new render pass descriptor with no attachments at all.
//
// # Discussion
// 
// Set the desired color attachments with the [SetObjectAtIndexedSubscript]
// method of the [ColorAttachments] property. Set the desired depth and
// stencil attachments with the [DepthAttachment] and [StencilAttachment]
// properties, respectively.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/renderPassDescriptor
func (_MTLRenderPassDescriptorClass MTLRenderPassDescriptorClass) RenderPassDescriptor() MTLRenderPassDescriptor {
	rv := objc.Send[objc.ID](objc.ID(_MTLRenderPassDescriptorClass.class), objc.Sel("renderPassDescriptor"))
	return MTLRenderPassDescriptorFromID(rv)
}

// An array of state information for attachments that store color data.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/colorAttachments
func (r MTLRenderPassDescriptor) ColorAttachments() IMTLRenderPassColorAttachmentDescriptorArray {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("colorAttachments"))
	return MTLRenderPassColorAttachmentDescriptorArrayFromID(objc.ID(rv))
}
// State information for an attachment that stores depth data.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/depthAttachment
func (r MTLRenderPassDescriptor) DepthAttachment() IMTLRenderPassDepthAttachmentDescriptor {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("depthAttachment"))
	return MTLRenderPassDepthAttachmentDescriptorFromID(objc.ID(rv))
}
func (r MTLRenderPassDescriptor) SetDepthAttachment(value IMTLRenderPassDepthAttachmentDescriptor) {
	objc.Send[struct{}](r.ID, objc.Sel("setDepthAttachment:"), value)
}
// State information for an attachment that stores stencil data.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/stencilAttachment
func (r MTLRenderPassDescriptor) StencilAttachment() IMTLRenderPassStencilAttachmentDescriptor {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("stencilAttachment"))
	return MTLRenderPassStencilAttachmentDescriptorFromID(objc.ID(rv))
}
func (r MTLRenderPassDescriptor) SetStencilAttachment(value IMTLRenderPassStencilAttachmentDescriptor) {
	objc.Send[struct{}](r.ID, objc.Sel("setStencilAttachment:"), value)
}
// A buffer where the GPU writes visibility test results when fragments pass
// depth and stencil tests.
//
// # Discussion
// 
// When encoding a render pass, you can tell the GPU to record data about
// fragments that pass depth and stencil tests. Typically, you use visibility
// testing to track whether a particular piece of geometry is visible in the
// current frame, so you can omit drawing calls for hidden objects when
// encoding future frames. This technique is sometimes called . You can record
// separate tests for different pieces of geometry.
// 
// Set this property to provide the buffer for the GPU to store visibility
// results when it executes the render pass. The GPU stores visibility results
// as 64-bit integers, so you need to reserve `8` bytes for each visibility
// result that you want to track. After creating the render command encoder,
// call [SetVisibilityResultModeOffset] to start each visibility test.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/visibilityResultBuffer
func (r MTLRenderPassDescriptor) VisibilityResultBuffer() MTLBuffer {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("visibilityResultBuffer"))
	return MTLBufferObjectFromID(rv)
}
func (r MTLRenderPassDescriptor) SetVisibilityResultBuffer(value MTLBuffer) {
	objc.Send[struct{}](r.ID, objc.Sel("setVisibilityResultBuffer:"), value)
}
// The number of active layers that all attachments need to have for layered
// rendering.
//
// # Discussion
// 
// The default value is `0`, indicating that the GPU does not use layered
// rendering on this render pass.
// 
// The table below gives typical values you might set, depending on the type
// of texture being used as attachments in the render pass. Your vertex shader
// need to select the render target array index between `0` and the array
// length minus `1`.
// 
// [Table data omitted]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/renderTargetArrayLength
func (r MTLRenderPassDescriptor) RenderTargetArrayLength() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("renderTargetArrayLength"))
	return rv
}
func (r MTLRenderPassDescriptor) SetRenderTargetArrayLength(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setRenderTargetArrayLength:"), value)
}
// The width, in pixels, to constrain the render target to.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/renderTargetWidth
func (r MTLRenderPassDescriptor) RenderTargetWidth() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("renderTargetWidth"))
	return rv
}
func (r MTLRenderPassDescriptor) SetRenderTargetWidth(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setRenderTargetWidth:"), value)
}
// The height, in pixels, to constrain the render target to.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/renderTargetHeight
func (r MTLRenderPassDescriptor) RenderTargetHeight() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("renderTargetHeight"))
	return rv
}
func (r MTLRenderPassDescriptor) SetRenderTargetHeight(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setRenderTargetHeight:"), value)
}
// The per-sample size, in bytes, of the largest explicit imageblock layout in
// the render pass.
//
// # Discussion
// 
// If `imageBlockSampleLength` isn’t specified, Metal determines the
// imageblock sample length from the render pass attachment formats. If any
// render pipelines bound to the encoder reference imageblocks with explicit
// layout, you need to set this property.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/imageblockSampleLength
func (r MTLRenderPassDescriptor) ImageblockSampleLength() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("imageblockSampleLength"))
	return rv
}
func (r MTLRenderPassDescriptor) SetImageblockSampleLength(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setImageblockSampleLength:"), value)
}
// The per-tile size, in bytes, of the persistent threadgroup memory
// allocation.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/threadgroupMemoryLength
func (r MTLRenderPassDescriptor) ThreadgroupMemoryLength() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("threadgroupMemoryLength"))
	return rv
}
func (r MTLRenderPassDescriptor) SetThreadgroupMemoryLength(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setThreadgroupMemoryLength:"), value)
}
// The tile width, in pixels.
//
// # Discussion
// 
// The valid tile sizes are `32 x 32`, `32 x 16`, and `16 x 16`. The Metal
// driver chooses a default size when your app doesn’t set a tile size.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/tileWidth
func (r MTLRenderPassDescriptor) TileWidth() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("tileWidth"))
	return rv
}
func (r MTLRenderPassDescriptor) SetTileWidth(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setTileWidth:"), value)
}
// The tile height, in pixels.
//
// # Discussion
// 
// The valid tile sizes are `32 x 32`, `32 x 16`, and `16 x 16`. The Metal
// driver chooses a default size when your app doesn’t set a tile size.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/tileHeight
func (r MTLRenderPassDescriptor) TileHeight() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("tileHeight"))
	return rv
}
func (r MTLRenderPassDescriptor) SetTileHeight(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setTileHeight:"), value)
}
// The raster sample count for the render pass when the render pass doesn’t
// have explicit attachments.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/defaultRasterSampleCount
func (r MTLRenderPassDescriptor) DefaultRasterSampleCount() uint {
	rv := objc.Send[uint](r.ID, objc.Sel("defaultRasterSampleCount"))
	return rv
}
func (r MTLRenderPassDescriptor) SetDefaultRasterSampleCount(value uint) {
	objc.Send[struct{}](r.ID, objc.Sel("setDefaultRasterSampleCount:"), value)
}
// The rasterization rate map to use when executing the render pass.
//
// # Discussion
// 
// The default value is `nil`, which means that viewport coordinates are in
// the same coordinate system as the physical coordinates in the render
// target. Otherwise, Metal uses the rate map to convert between viewport
// coordinates and physical coordinates in the render target.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/rasterizationRateMap
func (r MTLRenderPassDescriptor) RasterizationRateMap() MTLRasterizationRateMap {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("rasterizationRateMap"))
	return MTLRasterizationRateMapObjectFromID(rv)
}
func (r MTLRenderPassDescriptor) SetRasterizationRateMap(value MTLRasterizationRateMap) {
	objc.Send[struct{}](r.ID, objc.Sel("setRasterizationRateMap:"), value)
}
// The array of sample buffers that the render pass can access.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/sampleBufferAttachments
func (r MTLRenderPassDescriptor) SampleBufferAttachments() IMTLRenderPassSampleBufferAttachmentDescriptorArray {
	rv := objc.Send[objc.ID](r.ID, objc.Sel("sampleBufferAttachments"))
	return MTLRenderPassSampleBufferAttachmentDescriptorArrayFromID(objc.ID(rv))
}
// Specifies if the render pass should support color attachment mapping.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/supportColorAttachmentMapping
func (r MTLRenderPassDescriptor) SupportColorAttachmentMapping() bool {
	rv := objc.Send[bool](r.ID, objc.Sel("supportColorAttachmentMapping"))
	return rv
}
func (r MTLRenderPassDescriptor) SetSupportColorAttachmentMapping(value bool) {
	objc.Send[struct{}](r.ID, objc.Sel("setSupportColorAttachmentMapping:"), value)
}
// Specifies if Metal accumulates visibility results between render encoders
// or resets them.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDescriptor/visibilityResultType
func (r MTLRenderPassDescriptor) VisibilityResultType() MTLVisibilityResultType {
	rv := objc.Send[MTLVisibilityResultType](r.ID, objc.Sel("visibilityResultType"))
	return MTLVisibilityResultType(rv)
}
func (r MTLRenderPassDescriptor) SetVisibilityResultType(value MTLVisibilityResultType) {
	objc.Send[struct{}](r.ID, objc.Sel("setVisibilityResultType:"), value)
}
// An option for rendering to the texture in a render pass.
//
// See: https://developer.apple.com/documentation/metal/mtltextureusage/rendertarget
func (r MTLRenderPassDescriptor) RenderTarget() MTLTextureUsage {
	rv := objc.Send[MTLTextureUsage](r.ID, objc.Sel("MTLTextureUsageRenderTarget"))
	return MTLTextureUsage(rv)
}
func (r MTLRenderPassDescriptor) SetRenderTarget(value MTLTextureUsage) {
	objc.Send[struct{}](r.ID, objc.Sel("setMTLTextureUsageRenderTarget:"), value)
}
// Options that determine how you can use the texture.
//
// See: https://developer.apple.com/documentation/metal/mtltexturedescriptor/usage
func (r MTLRenderPassDescriptor) Usage() MTLTextureUsage {
	rv := objc.Send[MTLTextureUsage](r.ID, objc.Sel("usage"))
	return MTLTextureUsage(rv)
}
func (r MTLRenderPassDescriptor) SetUsage(value MTLTextureUsage) {
	objc.Send[struct{}](r.ID, objc.Sel("setUsage:"), value)
}

