// Code generated from Apple documentation for Metal. DO NOT EDIT.

package metal

import (
	"sync"
	"github.com/tmc/apple/objc"
)

// The class instance for the [MTLRenderPassStencilAttachmentDescriptor] class.
var (
	_MTLRenderPassStencilAttachmentDescriptorClass     MTLRenderPassStencilAttachmentDescriptorClass
	_MTLRenderPassStencilAttachmentDescriptorClassOnce sync.Once
)

func getMTLRenderPassStencilAttachmentDescriptorClass() MTLRenderPassStencilAttachmentDescriptorClass {
	_MTLRenderPassStencilAttachmentDescriptorClassOnce.Do(func() {
		_MTLRenderPassStencilAttachmentDescriptorClass = MTLRenderPassStencilAttachmentDescriptorClass{class: objc.GetClass("MTLRenderPassStencilAttachmentDescriptor")}
	})
	return _MTLRenderPassStencilAttachmentDescriptorClass
}

// GetMTLRenderPassStencilAttachmentDescriptorClass returns the class object for MTLRenderPassStencilAttachmentDescriptor.
func GetMTLRenderPassStencilAttachmentDescriptorClass() MTLRenderPassStencilAttachmentDescriptorClass {
	return getMTLRenderPassStencilAttachmentDescriptorClass()
}

type MTLRenderPassStencilAttachmentDescriptorClass struct {
	class objc.Class
}

// Alloc allocates memory for a new instance of the class.
func (mc MTLRenderPassStencilAttachmentDescriptorClass) Alloc() MTLRenderPassStencilAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassStencilAttachmentDescriptor](objc.ID(mc.class), objc.Sel("alloc"))
	return rv
}







// A stencil render target that serves as the output destination for stencil
// pixels generated by a render pass.
//
// # Specifying the resolve filter
//
//   - [MTLRenderPassStencilAttachmentDescriptor.StencilResolveFilter]: The filter used for stencil multisample resolve.
//   - [MTLRenderPassStencilAttachmentDescriptor.SetStencilResolveFilter]
//
// # Specifying the stencil clear value
//
//   - [MTLRenderPassStencilAttachmentDescriptor.ClearStencil]: The value to use when clearing the stencil attachment.
//   - [MTLRenderPassStencilAttachmentDescriptor.SetClearStencil]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor
type MTLRenderPassStencilAttachmentDescriptor struct {
	MTLRenderPassAttachmentDescriptor
}

// MTLRenderPassStencilAttachmentDescriptorFromID constructs a [MTLRenderPassStencilAttachmentDescriptor] from an objc.ID.
//
// A stencil render target that serves as the output destination for stencil
// pixels generated by a render pass.
func MTLRenderPassStencilAttachmentDescriptorFromID(id objc.ID) MTLRenderPassStencilAttachmentDescriptor {
	return MTLRenderPassStencilAttachmentDescriptor{MTLRenderPassAttachmentDescriptor: MTLRenderPassAttachmentDescriptorFromID(id)}
}
// NOTE: MTLRenderPassStencilAttachmentDescriptor adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.





// An interface definition for the [MTLRenderPassStencilAttachmentDescriptor] class.
//
// # Specifying the resolve filter
//
//   - [IMTLRenderPassStencilAttachmentDescriptor.StencilResolveFilter]: The filter used for stencil multisample resolve.
//   - [IMTLRenderPassStencilAttachmentDescriptor.SetStencilResolveFilter]
//
// # Specifying the stencil clear value
//
//   - [IMTLRenderPassStencilAttachmentDescriptor.ClearStencil]: The value to use when clearing the stencil attachment.
//   - [IMTLRenderPassStencilAttachmentDescriptor.SetClearStencil]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor
type IMTLRenderPassStencilAttachmentDescriptor interface {
	IMTLRenderPassAttachmentDescriptor

	// Topic: Specifying the resolve filter

	// The filter used for stencil multisample resolve.
	StencilResolveFilter() MTLMultisampleStencilResolveFilter
	SetStencilResolveFilter(value MTLMultisampleStencilResolveFilter)

	// Topic: Specifying the stencil clear value

	// The value to use when clearing the stencil attachment.
	ClearStencil() uint32
	SetClearStencil(value uint32)
}





// Init initializes the instance.
func (r MTLRenderPassStencilAttachmentDescriptor) Init() MTLRenderPassStencilAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassStencilAttachmentDescriptor](r.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (r MTLRenderPassStencilAttachmentDescriptor) Autorelease() MTLRenderPassStencilAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassStencilAttachmentDescriptor](r.ID, objc.Sel("autorelease"))
	return rv
}

// NewMTLRenderPassStencilAttachmentDescriptor creates a new MTLRenderPassStencilAttachmentDescriptor instance.
func NewMTLRenderPassStencilAttachmentDescriptor() MTLRenderPassStencilAttachmentDescriptor {
	class := getMTLRenderPassStencilAttachmentDescriptorClass()
	rv := objc.Send[MTLRenderPassStencilAttachmentDescriptor](objc.ID(class.class), objc.Sel("new"))
	return rv
}





















// The filter used for stencil multisample resolve.
//
// # Discussion
// 
// The default value is [MultisampleStencilResolveFilterSample0].
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor/stencilResolveFilter
func (r MTLRenderPassStencilAttachmentDescriptor) StencilResolveFilter() MTLMultisampleStencilResolveFilter {
	rv := objc.Send[MTLMultisampleStencilResolveFilter](r.ID, objc.Sel("stencilResolveFilter"))
	return MTLMultisampleStencilResolveFilter(rv)
}
func (r MTLRenderPassStencilAttachmentDescriptor) SetStencilResolveFilter(value MTLMultisampleStencilResolveFilter) {
	objc.Send[struct{}](r.ID, objc.Sel("setStencilResolveFilter:"), value)
}



// The value to use when clearing the stencil attachment.
//
// # Discussion
// 
// If the [LoadAction] property of the attachment is set to [LoadActionClear],
// then at the start of a render pass, the GPU fills the contents of the
// attachment with the value stored in the [ClearStencil] property. Otherwise,
// the GPU ignores [ClearStencil].
// 
// The default value is `0`.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor/clearStencil
func (r MTLRenderPassStencilAttachmentDescriptor) ClearStencil() uint32 {
	rv := objc.Send[uint32](r.ID, objc.Sel("clearStencil"))
	return rv
}
func (r MTLRenderPassStencilAttachmentDescriptor) SetClearStencil(value uint32) {
	objc.Send[struct{}](r.ID, objc.Sel("setClearStencil:"), value)
}
























