// Code generated from Apple documentation for Metal. DO NOT EDIT.

package metal

import (
	"sync"
	"github.com/tmc/apple/objc"
)

// The class instance for the [MTLRenderPassDepthAttachmentDescriptor] class.
var (
	_MTLRenderPassDepthAttachmentDescriptorClass     MTLRenderPassDepthAttachmentDescriptorClass
	_MTLRenderPassDepthAttachmentDescriptorClassOnce sync.Once
)

func getMTLRenderPassDepthAttachmentDescriptorClass() MTLRenderPassDepthAttachmentDescriptorClass {
	_MTLRenderPassDepthAttachmentDescriptorClassOnce.Do(func() {
		_MTLRenderPassDepthAttachmentDescriptorClass = MTLRenderPassDepthAttachmentDescriptorClass{class: objc.GetClass("MTLRenderPassDepthAttachmentDescriptor")}
	})
	return _MTLRenderPassDepthAttachmentDescriptorClass
}

// GetMTLRenderPassDepthAttachmentDescriptorClass returns the class object for MTLRenderPassDepthAttachmentDescriptor.
func GetMTLRenderPassDepthAttachmentDescriptorClass() MTLRenderPassDepthAttachmentDescriptorClass {
	return getMTLRenderPassDepthAttachmentDescriptorClass()
}

type MTLRenderPassDepthAttachmentDescriptorClass struct {
	class objc.Class
}

// Alloc allocates memory for a new instance of the class.
func (mc MTLRenderPassDepthAttachmentDescriptorClass) Alloc() MTLRenderPassDepthAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassDepthAttachmentDescriptor](objc.ID(mc.class), objc.Sel("alloc"))
	return rv
}

// A depth render target that serves as the output destination for depth
// pixels generated by a render pass.
//
// # Specifying clearing value
//
//   - [MTLRenderPassDepthAttachmentDescriptor.ClearDepth]: The depth to use when clearing the depth attachment.
//   - [MTLRenderPassDepthAttachmentDescriptor.SetClearDepth]
//
// # MSAA depth resolve
//
//   - [MTLRenderPassDepthAttachmentDescriptor.DepthResolveFilter]: The filter used for an MSAA depth resolve operation.
//   - [MTLRenderPassDepthAttachmentDescriptor.SetDepthResolveFilter]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor
type MTLRenderPassDepthAttachmentDescriptor struct {
	MTLRenderPassAttachmentDescriptor
}

// MTLRenderPassDepthAttachmentDescriptorFromID constructs a [MTLRenderPassDepthAttachmentDescriptor] from an objc.ID.
//
// A depth render target that serves as the output destination for depth
// pixels generated by a render pass.
func MTLRenderPassDepthAttachmentDescriptorFromID(id objc.ID) MTLRenderPassDepthAttachmentDescriptor {
	return MTLRenderPassDepthAttachmentDescriptor{MTLRenderPassAttachmentDescriptor: MTLRenderPassAttachmentDescriptorFromID(id)}
}
// NOTE: MTLRenderPassDepthAttachmentDescriptor adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [MTLRenderPassDepthAttachmentDescriptor] class.
//
// # Specifying clearing value
//
//   - [IMTLRenderPassDepthAttachmentDescriptor.ClearDepth]: The depth to use when clearing the depth attachment.
//   - [IMTLRenderPassDepthAttachmentDescriptor.SetClearDepth]
//
// # MSAA depth resolve
//
//   - [IMTLRenderPassDepthAttachmentDescriptor.DepthResolveFilter]: The filter used for an MSAA depth resolve operation.
//   - [IMTLRenderPassDepthAttachmentDescriptor.SetDepthResolveFilter]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor
type IMTLRenderPassDepthAttachmentDescriptor interface {
	IMTLRenderPassAttachmentDescriptor

	// Topic: Specifying clearing value

	// The depth to use when clearing the depth attachment.
	ClearDepth() float64
	SetClearDepth(value float64)

	// Topic: MSAA depth resolve

	// The filter used for an MSAA depth resolve operation.
	DepthResolveFilter() MTLMultisampleDepthResolveFilter
	SetDepthResolveFilter(value MTLMultisampleDepthResolveFilter)
}

// Init initializes the instance.
func (r MTLRenderPassDepthAttachmentDescriptor) Init() MTLRenderPassDepthAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassDepthAttachmentDescriptor](r.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (r MTLRenderPassDepthAttachmentDescriptor) Autorelease() MTLRenderPassDepthAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassDepthAttachmentDescriptor](r.ID, objc.Sel("autorelease"))
	return rv
}

// NewMTLRenderPassDepthAttachmentDescriptor creates a new MTLRenderPassDepthAttachmentDescriptor instance.
func NewMTLRenderPassDepthAttachmentDescriptor() MTLRenderPassDepthAttachmentDescriptor {
	class := getMTLRenderPassDepthAttachmentDescriptorClass()
	rv := objc.Send[MTLRenderPassDepthAttachmentDescriptor](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// The depth to use when clearing the depth attachment.
//
// # Discussion
// 
// If the [LoadAction] property of the attachment is set to [LoadActionClear],
// then at the start of a render pass, the GPU fills the contents of the
// attachment with the value stored in the [ClearDepth] property. Otherwise,
// the GPU ignores [ClearDepth].
// 
// The default value is `1.0`.
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor/clearDepth
func (r MTLRenderPassDepthAttachmentDescriptor) ClearDepth() float64 {
	rv := objc.Send[float64](r.ID, objc.Sel("clearDepth"))
	return rv
}
func (r MTLRenderPassDepthAttachmentDescriptor) SetClearDepth(value float64) {
	objc.Send[struct{}](r.ID, objc.Sel("setClearDepth:"), value)
}

// The filter used for an MSAA depth resolve operation.
//
// # Discussion
// 
// The default value is [MultisampleDepthResolveFilterSample0].
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor/depthResolveFilter
func (r MTLRenderPassDepthAttachmentDescriptor) DepthResolveFilter() MTLMultisampleDepthResolveFilter {
	rv := objc.Send[MTLMultisampleDepthResolveFilter](r.ID, objc.Sel("depthResolveFilter"))
	return MTLMultisampleDepthResolveFilter(rv)
}
func (r MTLRenderPassDepthAttachmentDescriptor) SetDepthResolveFilter(value MTLMultisampleDepthResolveFilter) {
	objc.Send[struct{}](r.ID, objc.Sel("setDepthResolveFilter:"), value)
}

