// Code generated from Apple documentation for Metal. DO NOT EDIT.

package metal

import (
	"sync"
	"github.com/tmc/apple/objc"
)

// The class instance for the [MTLRenderPassColorAttachmentDescriptor] class.
var (
	_MTLRenderPassColorAttachmentDescriptorClass     MTLRenderPassColorAttachmentDescriptorClass
	_MTLRenderPassColorAttachmentDescriptorClassOnce sync.Once
)

func getMTLRenderPassColorAttachmentDescriptorClass() MTLRenderPassColorAttachmentDescriptorClass {
	_MTLRenderPassColorAttachmentDescriptorClassOnce.Do(func() {
		_MTLRenderPassColorAttachmentDescriptorClass = MTLRenderPassColorAttachmentDescriptorClass{class: objc.GetClass("MTLRenderPassColorAttachmentDescriptor")}
	})
	return _MTLRenderPassColorAttachmentDescriptorClass
}

// GetMTLRenderPassColorAttachmentDescriptorClass returns the class object for MTLRenderPassColorAttachmentDescriptor.
func GetMTLRenderPassColorAttachmentDescriptorClass() MTLRenderPassColorAttachmentDescriptorClass {
	return getMTLRenderPassColorAttachmentDescriptorClass()
}

type MTLRenderPassColorAttachmentDescriptorClass struct {
	class objc.Class
}

// Alloc allocates memory for a new instance of the class.
func (mc MTLRenderPassColorAttachmentDescriptorClass) Alloc() MTLRenderPassColorAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassColorAttachmentDescriptor](objc.ID(mc.class), objc.Sel("alloc"))
	return rv
}







// A color render target that serves as the output destination for color
// pixels generated by a render pass.
//
// # Specifying clearing value
//
//   - [MTLRenderPassColorAttachmentDescriptor.ClearColor]: The color to use when clearing the color attachment.
//   - [MTLRenderPassColorAttachmentDescriptor.SetClearColor]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassColorAttachmentDescriptor
type MTLRenderPassColorAttachmentDescriptor struct {
	MTLRenderPassAttachmentDescriptor
}

// MTLRenderPassColorAttachmentDescriptorFromID constructs a [MTLRenderPassColorAttachmentDescriptor] from an objc.ID.
//
// A color render target that serves as the output destination for color
// pixels generated by a render pass.
func MTLRenderPassColorAttachmentDescriptorFromID(id objc.ID) MTLRenderPassColorAttachmentDescriptor {
	return MTLRenderPassColorAttachmentDescriptor{MTLRenderPassAttachmentDescriptor: MTLRenderPassAttachmentDescriptorFromID(id)}
}
// NOTE: MTLRenderPassColorAttachmentDescriptor adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.





// An interface definition for the [MTLRenderPassColorAttachmentDescriptor] class.
//
// # Specifying clearing value
//
//   - [IMTLRenderPassColorAttachmentDescriptor.ClearColor]: The color to use when clearing the color attachment.
//   - [IMTLRenderPassColorAttachmentDescriptor.SetClearColor]
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassColorAttachmentDescriptor
type IMTLRenderPassColorAttachmentDescriptor interface {
	IMTLRenderPassAttachmentDescriptor

	// Topic: Specifying clearing value

	// The color to use when clearing the color attachment.
	ClearColor() MTLClearColor
	SetClearColor(value MTLClearColor)
}





// Init initializes the instance.
func (r MTLRenderPassColorAttachmentDescriptor) Init() MTLRenderPassColorAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassColorAttachmentDescriptor](r.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (r MTLRenderPassColorAttachmentDescriptor) Autorelease() MTLRenderPassColorAttachmentDescriptor {
	rv := objc.Send[MTLRenderPassColorAttachmentDescriptor](r.ID, objc.Sel("autorelease"))
	return rv
}

// NewMTLRenderPassColorAttachmentDescriptor creates a new MTLRenderPassColorAttachmentDescriptor instance.
func NewMTLRenderPassColorAttachmentDescriptor() MTLRenderPassColorAttachmentDescriptor {
	class := getMTLRenderPassColorAttachmentDescriptorClass()
	rv := objc.Send[MTLRenderPassColorAttachmentDescriptor](objc.ID(class.class), objc.Sel("new"))
	return rv
}





















// The color to use when clearing the color attachment.
//
// # Discussion
// 
// If the [LoadAction] property of the attachment is set to [LoadActionClear],
// then at the start of a render pass, the GPU fills the texture with the
// value stored in the [ClearColor] property. Otherwise, the GPU ignores the
// [ClearColor] property.
// 
// The [ClearColor] property represents a set of RGBA components. The default
// value is `(0.0, 0.0, 0.0, 1.0)` (black). Use the [MTLClearColorMake]
// function to construct an [MTLClearColor] value.
//
// [MTLClearColor]: https://developer.apple.com/documentation/Metal/MTLClearColor
//
// See: https://developer.apple.com/documentation/Metal/MTLRenderPassColorAttachmentDescriptor/clearColor
func (r MTLRenderPassColorAttachmentDescriptor) ClearColor() MTLClearColor {
	rv := objc.Send[MTLClearColor](r.ID, objc.Sel("clearColor"))
	return MTLClearColor(rv)
}
func (r MTLRenderPassColorAttachmentDescriptor) SetClearColor(value MTLClearColor) {
	objc.Send[struct{}](r.ID, objc.Sel("setClearColor:"), value)
}
























