// Command signpostnames generates a signpost string pool so names decode in
// trace output.
//
// The unified logging system decodes signpost names from a loaded image's
// __TEXT,__oslogstring section (see the signpost package). signpostnames
// scans Go source for the string literals passed as names to signpost calls
// (IntervalBegin, IntervalEnd, Event, and their Message and formatted f
// variants), plus the os_log format literals of the f variants, adds the
// format strings the package emits, and assembles them with clang into one
// of two containers:
//
//   - Default: an object file (names_darwin.syso) that go build links into
//     the binary. This requires external linking, which any CGO_ENABLED=1
//     build uses automatically on macOS (no cgo source is needed; the .syso
//     itself forces it). CGO_ENABLED=0 builds link internally and silently
//     drop the section - the syso path does not work there.
//   - With -dylib: a small dylib (names_darwin.dylib) loaded at run time via
//     signpost.LoadNames. This works in every build mode, including
//     CGO_ENABLED=0, at the cost of shipping the dylib beside the binary.
//
// Usage:
//
//	signpostnames [-dylib] [-o output] [-funcs fn=argindex,...] [-extra name]... [dir]...
//
// With -o - the assembly listing is written to standard output instead.
// Programs that wrap signpost calls in a helper declare it with -funcs, as
// with go vet's printf analyzer: -funcs handle=1 pools the second argument of
// every call to handle. Names built at run time cannot be discovered
// statically; either restructure the program to use literal names, or pass
// them with -extra. Names missing from the pool still emit and pair, but
// decode as "<missing name>".
//
// A typical package uses it via go:generate:
//
//	//go:generate go run github.com/tmc/apple/x/signpost/cmd/signpostnames -o names_darwin.syso
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// nameFuncs maps function or method names to the index of their name
// argument. The signpost methods are built in; -funcs adds user wrappers.
var nameFuncs = map[string]int{
	"IntervalBegin":        1,
	"IntervalEnd":          1,
	"Event":                1,
	"IntervalBeginMessage": 1,
	"IntervalEndMessage":   1,
	"EventMessage":         1,
	"IntervalBeginf":       1,
	"IntervalEndf":         1,
	"Eventf":               1,
}

// formatFuncs maps the formatted variants to the index of their os_log
// format argument, which must decode like a name and is pooled the same way.
var formatFuncs = map[string]int{
	"IntervalBeginf": 2,
	"IntervalEndf":   2,
	"Eventf":         2,
}

// formatStrings are emitted by the signpost package itself and must decode.
var formatStrings = []string{"", "%{public}s"}

func main() {
	log.SetFlags(0)
	log.SetPrefix("signpostnames: ")
	out := flag.String("o", "", `output file (default names_darwin.syso, or names_darwin.dylib with -dylib; "-" writes assembly to stdout)`)
	dylib := flag.Bool("dylib", false, "build a runtime-loadable dylib for signpost.LoadNames instead of a linkable object")
	funcs := flag.String("funcs", "", "comma-separated fn=argindex wrappers whose argument is a signpost name")
	var extras stringList
	flag.Var(&extras, "extra", "additional name to pool (repeatable)")
	flag.Parse()
	if *out == "" {
		if *dylib {
			*out = "names_darwin.dylib"
		} else {
			*out = "names_darwin.syso"
		}
	}

	for f := range strings.SplitSeq(*funcs, ",") {
		if f == "" {
			continue
		}
		name, idx, ok := strings.Cut(f, "=")
		n, err := strconv.Atoi(idx)
		if !ok || err != nil || n < 0 {
			log.Fatalf("bad -funcs entry %q: want fn=argindex", f)
		}
		nameFuncs[name] = n
	}

	dirs := flag.Args()
	if len(dirs) == 0 {
		dirs = []string{"."}
	}

	found := map[string]bool{}
	for _, dir := range dirs {
		if err := scanDir(dir, found); err != nil {
			log.Fatal(err)
		}
	}
	for _, e := range extras {
		found[e] = true
	}
	var names []string
	for n := range found {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("; Signpost string pool. Generated by signpostnames; DO NOT EDIT.\n")
	b.WriteString(".section __TEXT,__oslogstring,cstring_literals\n")
	if *dylib {
		// signpost.LoadNames resolves string offsets relative to this
		// anchor, so it must be the first thing in the section.
		b.WriteString(".globl _signpost_names\n_signpost_names:\n")
	}
	for _, s := range append(formatStrings, names...) {
		fmt.Fprintf(&b, ".asciz %q\n", s)
	}

	if *out == "-" {
		os.Stdout.WriteString(b.String())
		return
	}
	tmp, err := os.CreateTemp("", "signpostnames-*.s")
	if err != nil {
		log.Fatal(err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(b.String()); err != nil {
		log.Fatal(err)
	}
	tmp.Close()
	args := []string{"-x", "assembler", tmp.Name(), "-o", *out}
	if *dylib {
		args = append([]string{"-dynamiclib"}, args...)
	} else {
		args = append([]string{"-c"}, args...)
	}
	cmd := exec.Command("clang", args...)
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("assemble: %v", err)
	}
}

// scanDir parses the Go files in dir and records string-literal name
// arguments of signpost calls.
func scanDir(dir string, found map[string]bool) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			return err
		}
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			var fn string
			switch f := call.Fun.(type) {
			case *ast.SelectorExpr:
				fn = f.Sel.Name
			case *ast.Ident:
				fn = f.Name
			default:
				return true
			}
			record := func(idx int) {
				if len(call.Args) <= idx {
					return
				}
				if lit, ok := call.Args[idx].(*ast.BasicLit); ok && lit.Kind == token.STRING {
					if s, err := strconv.Unquote(lit.Value); err == nil {
						found[s] = true
					}
				}
			}
			if idx, ok := nameFuncs[fn]; ok {
				record(idx)
			}
			if idx, ok := formatFuncs[fn]; ok {
				record(idx)
			}
			return true
		})
	}
	return nil
}

type stringList []string

func (s *stringList) String() string     { return strings.Join(*s, ",") }
func (s *stringList) Set(v string) error { *s = append(*s, v); return nil }
