// Code generated from Apple documentation for SpriteKit. DO NOT EDIT.

package spritekit

import (
	"sync"
	"unsafe"

	"github.com/tmc/apple/appkit"
	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objc"
)

// The class instance for the [SKLightNode] class.
var (
	_SKLightNodeClass     SKLightNodeClass
	_SKLightNodeClassOnce sync.Once
)

func getSKLightNodeClass() SKLightNodeClass {
	_SKLightNodeClassOnce.Do(func() {
		_SKLightNodeClass = SKLightNodeClass{class: objc.GetClass("SKLightNode")}
	})
	return _SKLightNodeClass
}

// GetSKLightNodeClass returns the class object for SKLightNode.
func GetSKLightNodeClass() SKLightNodeClass {
	return getSKLightNodeClass()
}

type SKLightNodeClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (sc SKLightNodeClass) Class() objc.Class {
	return sc.class
}

// Alloc allocates memory for a new instance of the class.
func (sc SKLightNodeClass) Alloc() SKLightNode {
	rv := objc.Send[SKLightNode](objc.ID(sc.class), objc.Sel("alloc"))
	return rv
}

// A node that lights surrounding nodes.
//
// # Overview
//
// To use lighting, add a light node to the scene. Because lights are nodes,
// they can be moved or perform actions just like other nodes. However, light
// nodes are invisible except through their effects on sprite nodes configured
// to interact with them. When a sprite node is affected by a light, the
// lighting properties of the light node and the lighting properties of the
// sprite node determine what is rendered. Lighting may affect how unrelated
// portions of the scene are rendered. For example, if a sprite is configured
// to cast a shadow, the shadow is rendered on top of other content.
//
// An [SKLightNode] object and an [SKSpriteNode] object add lighting to the
// scene if all of the following are true:
//
// - The light node and the sprite node are both in the scene. - The light
// node’s [SKLightNode.Enabled] property is true. - The light node’s
// [SKLightNode.CategoryBitMask] property and one of the sprite’s lighting
// masks are logically combined using an AND operation, and the result is a
// nonzero number.
//
// [SKLightNode] describes the different kinds of effects that can be
// generated by a light, based on which mask is being tested on the sprite.
//
// [Table data omitted]
//
// If any of the criteria are not met, the sprite is considered unlit and is
// rendered using the default behavior.
//
// # Determining Whether a Light Node Is Active
//
//   - [SKLightNode.IsEnabled]: A Boolean value that indicates whether the node is casting light.
//   - [SKLightNode.SetEnabled]
//   - [SKLightNode.CategoryBitMask]: A mask that defines which categories this light belongs to.
//   - [SKLightNode.SetCategoryBitMask]
//
// # Configuring the Lighting Properties
//
//   - [SKLightNode.AmbientColor]: The ambient color of the light.
//   - [SKLightNode.SetAmbientColor]
//   - [SKLightNode.LightColor]: The diffuse and specular color of the light source.
//   - [SKLightNode.SetLightColor]
//   - [SKLightNode.ShadowColor]: The color of any shadow cast by a sprite.
//   - [SKLightNode.SetShadowColor]
//   - [SKLightNode.Falloff]: The exponent for the rate of decay of the light source.
//   - [SKLightNode.SetFalloff]
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode
type SKLightNode struct {
	SKNode
}

// SKLightNodeFromID constructs a [SKLightNode] from an objc.ID.
//
// A node that lights surrounding nodes.
func SKLightNodeFromID(id objc.ID) SKLightNode {
	return SKLightNode{SKNode: SKNodeFromID(id)}
}

// NOTE: SKLightNode adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [SKLightNode] class.
//
// # Determining Whether a Light Node Is Active
//
//   - [ISKLightNode.IsEnabled]: A Boolean value that indicates whether the node is casting light.
//   - [ISKLightNode.SetEnabled]
//   - [ISKLightNode.CategoryBitMask]: A mask that defines which categories this light belongs to.
//   - [ISKLightNode.SetCategoryBitMask]
//
// # Configuring the Lighting Properties
//
//   - [ISKLightNode.AmbientColor]: The ambient color of the light.
//   - [ISKLightNode.SetAmbientColor]
//   - [ISKLightNode.LightColor]: The diffuse and specular color of the light source.
//   - [ISKLightNode.SetLightColor]
//   - [ISKLightNode.ShadowColor]: The color of any shadow cast by a sprite.
//   - [ISKLightNode.SetShadowColor]
//   - [ISKLightNode.Falloff]: The exponent for the rate of decay of the light source.
//   - [ISKLightNode.SetFalloff]
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode
type ISKLightNode interface {
	ISKNode

	// Topic: Determining Whether a Light Node Is Active

	// A Boolean value that indicates whether the node is casting light.
	IsEnabled() bool
	SetEnabled(value bool)
	// A mask that defines which categories this light belongs to.
	CategoryBitMask() uint32
	SetCategoryBitMask(value uint32)

	// Topic: Configuring the Lighting Properties

	// The ambient color of the light.
	AmbientColor() appkit.NSColor
	SetAmbientColor(value appkit.NSColor)
	// The diffuse and specular color of the light source.
	LightColor() appkit.NSColor
	SetLightColor(value appkit.NSColor)
	// The color of any shadow cast by a sprite.
	ShadowColor() appkit.NSColor
	SetShadowColor(value appkit.NSColor)
	// The exponent for the rate of decay of the light source.
	Falloff() float64
	SetFalloff(value float64)
}

// Init initializes the instance.
func (l SKLightNode) Init() SKLightNode {
	rv := objc.Send[SKLightNode](l.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (l SKLightNode) Autorelease() SKLightNode {
	rv := objc.Send[SKLightNode](l.ID, objc.Sel("autorelease"))
	return rv
}

// NewSKLightNode creates a new SKLightNode instance.
func NewSKLightNode() SKLightNode {
	class := getSKLightNodeClass()
	rv := objc.Send[SKLightNode](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Called when a node is initialized from an .sks file.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKNode/init(coder:)
func NewLightNodeWithCoder(aDecoder foundation.INSCoder) SKLightNode {
	instance := getSKLightNodeClass().Alloc()
	rv := objc.Send[objc.ID](instance.ID, objc.Sel("initWithCoder:"), aDecoder)
	return SKLightNodeFromID(rv)
}

// Creates a new node by loading an archive file from the game’s main
// bundle.
//
// filename: The name of the file, without a file extension. The file must be in the
// app’s main bundle and have a `XCUIElementTypeSks` filename extension.
//
// # Return Value
//
// The unarchived node object.
//
// # Discussion
//
// If you call this method on a subclass of the [SKScene] class and the object
// in the archive is an [SKScene] object, the returned object is initialized
// as if it is a member of the subclass. You use this behavior to create scene
// layouts in the Xcode Editor and provide custom behaviors in your subclass.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKNode/init(fileNamed:)
func NewLightNodeWithFileNamed(filename string) SKLightNode {
	rv := objc.Send[objc.ID](objc.ID(getSKLightNodeClass().class), objc.Sel("nodeWithFileNamed:"), objc.String(filename))
	return SKLightNodeFromID(rv)
}

// See: https://developer.apple.com/documentation/SpriteKit/SKNode/init(fileNamed:securelyWithClasses:)
func NewLightNodeWithFileNamedSecurelyWithClassesAndError(filename string, classes foundation.INSSet) (SKLightNode, error) {
	var errorPtr objc.ID
	rv := objc.Send[objc.ID](objc.ID(getSKLightNodeClass().class), objc.Sel("nodeWithFileNamed:securelyWithClasses:andError:"), objc.String(filename), classes, unsafe.Pointer(&errorPtr))
	if errorPtr != 0 {
		objc.Send[objc.ID](errorPtr, objc.Sel("retain"))
		return SKLightNode{}, foundation.NSErrorFrom(errorPtr)
	}
	if rv == 0 {
		return SKLightNode{}, objc.ErrInitFailed
	}
	return SKLightNodeFromID(rv), nil
}

// A Boolean value that indicates whether the node is casting light.
//
// # Discussion
//
// If the value is true, the light is enabled and affects sprite nodes in the
// scene. The default is true.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/isEnabled
func (l SKLightNode) IsEnabled() bool {
	rv := objc.Send[bool](l.ID, objc.Sel("isEnabled"))
	return rv
}
func (l SKLightNode) SetEnabled(value bool) {
	objc.Send[struct{}](l.ID, objc.Sel("setEnabled:"), value)
}

// A mask that defines which categories this light belongs to.
//
// # Discussion
//
// Every light in a scene can be assigned to up to 32 different categories,
// each corresponding to a bit in the bit mask. SpriteKit does not predefine
// any lighting categories, so it is up to you to define which values are used
// in your game. When a scene is rendered, a light’s
// [SKLightNode.CategoryBitMask] property is compared to each sprite node’s
// [SKSpriteNode.LightingBitMask], [SKSpriteNode.ShadowCastBitMask], and
// [SKSpriteNode.ShadowedBitMask] properties to determine whether that sprite
// interacts with the light.
//
// The default value is `0x00000001`.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/categoryBitMask
func (l SKLightNode) CategoryBitMask() uint32 {
	rv := objc.Send[uint32](l.ID, objc.Sel("categoryBitMask"))
	return rv
}
func (l SKLightNode) SetCategoryBitMask(value uint32) {
	objc.Send[struct{}](l.ID, objc.Sel("setCategoryBitMask:"), value)
}

// The ambient color of the light.
//
// # Discussion
//
// The alpha value of the color is ignored. The default color is black,
// meaning that the light does not have an ambient component. The ambient
// component of the light is not affected by the light’s
// [SKLightNode.Falloff] property, nor is it affected by any normal map
// ([SKSpriteNode.NormalTexture]) on the sprite node.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/ambientColor
func (l SKLightNode) AmbientColor() appkit.NSColor {
	rv := objc.Send[objc.ID](l.ID, objc.Sel("ambientColor"))
	return appkit.NSColorFromID(objc.ID(rv))
}
func (l SKLightNode) SetAmbientColor(value appkit.NSColor) {
	objc.Send[struct{}](l.ID, objc.Sel("setAmbientColor:"), value)
}

// The diffuse and specular color of the light source.
//
// # Discussion
//
// The default value is white.
//
// If you are using custom shaders, you can substitute an [SKUniform] object
// instead.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/lightColor
func (l SKLightNode) LightColor() appkit.NSColor {
	rv := objc.Send[objc.ID](l.ID, objc.Sel("lightColor"))
	return appkit.NSColorFromID(objc.ID(rv))
}
func (l SKLightNode) SetLightColor(value appkit.NSColor) {
	objc.Send[struct{}](l.ID, objc.Sel("setLightColor:"), value)
}

// The color of any shadow cast by a sprite.
//
// # Discussion
//
// The default color is black with an opacity (alpha) of `0.5`.
//
// When lighting is calculated, shadows are created as if a ray was cast out
// from the light node’s position. If a sprite casts a shadow, the rays are
// blocked when they intersect with the sprite’s physics body. Otherwise,
// the sprite’s texture is used to generate a mask, and any pixel in the
// sprite node’s texture that has an alpha value that is nonzero blocks the
// light.
//
// Shadows may be cast on content that is rendered prior to the sprite, even
// if that content does not otherwise interact with the light.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/shadowColor
func (l SKLightNode) ShadowColor() appkit.NSColor {
	rv := objc.Send[objc.ID](l.ID, objc.Sel("shadowColor"))
	return appkit.NSColorFromID(objc.ID(rv))
}
func (l SKLightNode) SetShadowColor(value appkit.NSColor) {
	objc.Send[struct{}](l.ID, objc.Sel("setShadowColor:"), value)
}

// The exponent for the rate of decay of the light source.
//
// # Discussion
//
// The default value is `1.0`, which means the light decays linearly with
// distance. The value must be a positive number less than or equal to `1.0`.
//
// See: https://developer.apple.com/documentation/SpriteKit/SKLightNode/falloff
func (l SKLightNode) Falloff() float64 {
	rv := objc.Send[float64](l.ID, objc.Sel("falloff"))
	return rv
}
func (l SKLightNode) SetFalloff(value float64) {
	objc.Send[struct{}](l.ID, objc.Sel("setFalloff:"), value)
}
