// Code generated from Apple documentation for CoreVideo. DO NOT EDIT.

// Package corevideo provides Go bindings for the CoreVideo framework.
//
// Process digital video, including manipulation of individual frames, using a
// pipeline-based API and support for both Metal and OpenGL.
//
// Core Video provides a pipeline model for digital video. It simplifies
// working with video by partitioning the process into discrete steps. This
// makes it easier for developers to access and manipulate individual frames
// without having to worry about translating between data types or display
// synchronization issues. Apps that don’t need to manipulate individual
// video frames don’t need to use Core Video directly.
//
// # Data Processing
//
//   - CVBuffer: An abstract base class that defines how to interact with data buffers. ([CVAttachmentMode])
//   - CVPixelBuffer: An image buffer that holds pixels in main memory. ([CVPixelBufferLockFlags], [CVPlanarComponentInfo], [CVPlanarPixelBufferInfo], [CVPlanarPixelBufferInfo_YCbCrPlanar], [CVPlanarPixelBufferInfo_YCbCrBiPlanar])
//   - CVPixelBufferPool: A utility object for managing a recyclable set of pixel buffer objects. ([CVPixelBufferPoolFlushFlags])
//   - CVPixelFormatDescription: An API that provides functions and types for defining custom pixel formats. ([CVFillExtendedPixelsCallBackData], [CVFillExtendedPixelsCallBack])
//
// # Time Management
//
//   - [CVTime]: A structure used for storing Core Video time values. ([CVTime], [CVSMPTETime], [CVSMPTETimeType], [CVSMPTETimeFlags], [CVTimeFlags])
//   - CVDisplayLink: A high-priority thread that notifies your app when a given display will need each frame. ([CVDisplayLinkOutputHandler], [CVOptionFlags], [CVDisplayLinkOutputCallback], [CVDisplayLinkOutputHandler])
//
// # Core Video Error Constants
//
//   - [Result Codes]: Describes the result codes generated by Core Video operations.
//   - [Data Types]: Common data types used by the Core Video framework. ([CVReturn])
//
// # Variables
//
//   - [KCVImageBufferDisplayMaskRectangleKey]: Specifies the rectangular display area within the image.
//   - [KCVImageBufferDisplayMaskRectangleStereoLeftKey]: Specifies the rectangular display area within the left-eye view of stereo images, using the same keys as .
//   - [KCVImageBufferDisplayMaskRectangleStereoRightKey]: Specifies the rectangular display area within the right-eye view of stereo images, using the same keys as .
//   - [KCVImageBufferLogTransferFunction_AppleLog2]
//   - [KCVImageBufferPostDecodeProcessingFrameMetadataKey]
//   - [KCVImageBufferPostDecodeProcessingSequenceMetadataKey]
//   - [KCVImageBufferSceneIlluminationKey]
//   - [KCVMetalBufferCacheMaximumBufferAgeKey]
//   - [KCVPixelBufferIOSurfacePurgeableKey]
//   - [KCVPixelFormatBitsPerComponent]
//
// # Functions
//
//   - [CVMetalBufferCacheCreate]
//   - [CVMetalBufferCacheCreateBufferFromImage]
//   - [CVMetalBufferCacheFlush]
//   - [CVMetalBufferCacheGetTypeID]
//   - [CVMetalBufferGetBuffer]
//   - [CVMetalBufferGetTypeID]
//   - [CVPixelBufferIsCompatibleWithAttributes]
//   - [CVPixelFormatTypeCopyFourCharCodeString]
//
// # Type Aliases
//
//   - [CVMetalBufferRef]
//   - [CVMetalBufferCacheRef]//
//
// [Data Types]: https://developer.apple.com/documentation/corevideo/data-types
// [Result Codes]: https://developer.apple.com/documentation/corevideo/result-codes
package corevideo

import (
	"fmt"
	"os"

	"github.com/ebitengine/purego"
)

// frameworkPaths lists paths to try when loading the CoreVideo library,
// in order. Frameworks whose symbols live in a known dylib resolve to that
// dylib alone; the rest try the framework bundle first and then a /usr/lib
// dylib fallback, which covers C-API frameworks that are not in the dyld
// shared cache as bundles.
var frameworkPaths = []string{
	"/System/Library/Frameworks/CoreVideo.framework/CoreVideo",
	"/usr/lib/libCoreVideo.dylib",
}

// frameworkHandle is the handle to the loaded framework.
var frameworkHandle uintptr

func init() {
	for _, path := range frameworkPaths {
		h, err := purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
		if err == nil {
			frameworkHandle = h
			return
		}
	}
	// Loading is best-effort: the warning is silent by default because a missing
	// framework is harmless unless one of its symbols is actually called. Set
	// APPLE_FRAMEWORK_LOAD_DEBUG to surface load failures while diagnosing.
	if os.Getenv("APPLE_FRAMEWORK_LOAD_DEBUG") != "" {
		fmt.Fprintf(os.Stderr, "warning: CoreVideo: failed to load framework from any known path\n")
	}
}
