
// Code generated from Apple documentation for CoreVideo. DO NOT EDIT.

// Package corevideo provides Go bindings for the CoreVideo framework.
//
// Process digital video, including manipulation of individual frames, using a pipeline-based API and support for both Metal and OpenGL.
//
// Core Video provides a pipeline model for digital video. It simplifies working with video by partitioning the process into discrete steps. This makes it easier for developers to access and manipulate individual frames without having to worry about translating between data types or display synchronization issues. Apps that don’t need to manipulate individual video frames don’t need to use Core Video directly.
//
// # Data Processing
//
//   - CVBuffer: An abstract base class that defines how to interact with data buffers. ([CVAttachmentMode])
//   - CVImageBuffer: An interface for managing different types of image data.
//   - CVPixelBuffer: An image buffer that holds pixels in main memory. ([CVPixelBufferLockFlags], [CVPlanarComponentInfo], [CVPlanarPixelBufferInfo], [CVPlanarPixelBufferInfo_YCbCrPlanar], [CVPlanarPixelBufferInfo_YCbCrBiPlanar])
//   - CVPixelBufferPool: A utility object for managing a recyclable set of pixel buffer objects. ([CVPixelBufferPoolFlushFlags])
//   - CVPixelFormatDescription: An API that provides functions and types for defining custom pixel formats. ([CVFillExtendedPixelsCallBackData], [CVFillExtendedPixelsCallBack])
//
// # Time Management
//
//   - CVTime: A structure used for storing Core Video time values. ([CVTime], [CVSMPTETime], [CVSMPTETimeType], [CVSMPTETimeFlags], [CVTimeFlags])
//   - CVDisplayLink: A high-priority thread that notifies your app when a given display will need each frame. ([CVDisplayLinkOutputHandler], [CVOptionFlags], [CVDisplayLinkOutputCallback], [CVDisplayLinkOutputHandler])
//
// # Metal
//
//   - CVMetalTextureCache: A cache used to create and manage Metal texture objects.
//   - CVMetalTexture: A texture-based image buffer that supplies source image data for use with the Metal framework.
//
// # OpenGL
//
//   - CVOpenGLTextureCache: A cache used to create and manage OpenGL texture objects.
//   - CVOpenGLTexture: A texture-based image buffer that supplies source image data to OpenGL.
//   - CVOpenGLBuffer: An image buffer used to store image data in video memory.
//   - CVOpenGLBufferPool: A utility object for managing a set of recyclable OpenGL buffer objects.
//
// # OpenGL ES
//
//   - CVOpenGLESTextureCache: A cache used to create and manage OpenGL ES texture objects.
//   - CVOpenGLESTexture: A texture-based image buffer that supplies source image data to OpenGL ES.
//
// # Core Video Error Constants
//
//   - Result Codes: Describes the result codes generated by Core Video operations.
//   - Data Types: Common data types used by the Core Video framework. ([CVReturn])
//
// # Classes
//
//   - CVMetalBufferCache
//   - CVReadOnlyPixelBuffer: CVReadOnlyPixelBuffer provides an immutable view of the pixel data held by the pixel buffer.
//
// # Protocols
//
//   - CVBufferRepresentable: CVBufferRepresentable protocol is a sealed protocol intended to be implemented by the types in CoreVideo framework.
//   - CVImageBufferRepresentable: CVImageBufferRepresentable protocol is a sealed protocol intended to be implemented by the types in CoreVideo framework.
//   - CVPixelBufferRepresentable: CVPixelBufferRepresentable protocol is a sealed protocol intended to be implemented by the types in CoreVideo framework.
//
// # Variables
//
//   - kCVImageBufferDisplayMaskRectangleKey: Specifies the rectangular display area within the image.
//   - kCVImageBufferDisplayMaskRectangleStereoLeftKey: Specifies the rectangular display area within the left-eye view of stereo images, using the same keys as .
//   - kCVImageBufferDisplayMaskRectangleStereoRightKey: Specifies the rectangular display area within the right-eye view of stereo images, using the same keys as .
//   - kCVImageBufferLogTransferFunction_AppleLog2
//   - kCVImageBufferPostDecodeProcessingFrameMetadataKey
//   - kCVImageBufferPostDecodeProcessingSequenceMetadataKey
//   - kCVImageBufferSceneIlluminationKey
//   - kCVMetalBufferCacheMaximumBufferAgeKey
//   - kCVPixelBufferIOSurfacePurgeableKey
//   - kCVPixelFormatBitsPerComponent
//   - kCVPixelFormatType_30RGBLE_8A_BiPlanar
//   - kCVPixelFormatType_30RGB_r210
//   - kCVPixelFormatType_96VersatileBayerPacked12
//   - kCVPixelFormatType_Lossless_30RGBLEPackedWideGamut
//   - kCVPixelFormatType_Lossless_30RGBLE_8A_BiPlanar
//   - kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarFullRange
//   - kCVPixelFormatType_Lossless_64RGBAHalf
//
// # Functions
//
//   - CVMetalBufferCacheCreate(_:_:_:_:)
//   - CVMetalBufferCacheCreateBufferFromImage(_:_:_:_:)
//   - CVMetalBufferCacheFlush(_:_:)
//   - CVMetalBufferCacheGetTypeID()
//   - CVMetalBufferGetBuffer(_:)
//   - CVMetalBufferGetTypeID()
//   - CVPixelBufferIsCompatibleWithAttributes(_:_:)
//   - CVPixelFormatTypeCopyFourCharCodeString(_:)
//
// # Type Aliases
//
//   - CVMetalBuffer
//
// # Enumerations
//
//   - CVImageBufferOriginPosition
//
// [CoreVideo Documentation]: https://developer.apple.com/documentation/CoreVideo
package corevideo

import (
	"fmt"
	"os"
	"github.com/ebitengine/purego"
)

// frameworkPath is the system path to the framework binary.
const frameworkPath = "/System/Library/Frameworks/CoreVideo.framework/CoreVideo"
// frameworkHandle is the handle to the loaded framework.
var frameworkHandle uintptr

func init() {
	var err error
	frameworkHandle, err = purego.Dlopen(frameworkPath, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: CoreVideo: failed to load %s: %v\n", frameworkPath, err)
		return 
	}
}

