// Code generated from Apple documentation for Dispatch. DO NOT EDIT.

// Package dispatch provides Go bindings for Apple's Grand Central Dispatch (GCD).
//
// GCD is a low-level API for managing concurrent operations. This package
// exposes Go-idiomatic wrappers (exported, like QueueCreate). Raw generated
// C bindings are package-private and used internally by these wrappers.
//
// # Go Runtime Compatibility
//
// GCD and Go's runtime both manage threads. Key considerations:
//
//   - Use dispatch_async_f (not dispatch_async) for Go function callbacks
//   - Go closures passed to GCD will execute on GCD-managed threads
//   - Use sync.WaitGroup or channels to coordinate with Go code
//   - For main thread work on macOS, use the main dispatch queue
//
// # Basic Usage
//
//	queue := dispatch.GetGlobalQueue(dispatch.QOSDefault)
//	queue.Async(func() {
//	    // Work executes on a GCD thread
//	})
//
// # Groups for Coordination
//
//	group := dispatch.GroupCreate()
//	queue := dispatch.GetGlobalQueue(dispatch.QOSDefault)
//	for i := 0; i < 10; i++ {
//	    group.Async(queue, func() {
//	        // Parallel work
//	    })
//	}
//	group.Wait(dispatch.TimeForever)
//
// # Callback Memory
//
// Each unique dispatch function (Async, Sync, BarrierAsync, After,
// Group.Async, Group.Notify) uses a single permanent purego callback.
// Work closures are passed via a context map, not via new callbacks.
// This means an unlimited number of dispatches can be performed without
// exhausting purego's 2000-callback limit.
//
// # Apple Framework Interop
//
// When passing dispatch queues to Apple frameworks, prefer the main dispatch
// queue or a nil/default queue to let the framework manage thread affinity.
package dispatch

import (
	"fmt"
	"os"
	"runtime"
	"sync"
	"sync/atomic"
	"syscall"
	"time"
	"unsafe"

	"github.com/ebitengine/purego"
	"github.com/tmc/apple/objc"
)

// Dispatch_source_type_t aliases the unexported dispatch_source_type_t so the
// pipeline-generated _dispatch_source_create var can reference it.
type Dispatch_source_type_t = dispatch_source_type_t

// Private libdispatch symbols not generated by the normal function pipeline.
var (
	_dispatch_io_read_f  func(channel uintptr, offset int64, length uint64, queue uintptr, ctx unsafe.Pointer, handler uintptr)
	_dispatch_io_write_f func(channel uintptr, offset int64, data uintptr, queue uintptr, ctx unsafe.Pointer, handler uintptr)
)

// _dispatch_queue_attr_concurrent is the DISPATCH_QUEUE_CONCURRENT attribute
// loaded via dlsym (it's a global symbol, not a function).
var _dispatch_queue_attr_concurrent dispatch_queue_attr_t

// _dispatch_main_q is the main dispatch queue (Dispatch_get_main_queue()
// is a macro that expands to &_dispatch_main_q).
var _dispatch_main_q uintptr

// _dispatch_data_empty_val is the global empty dispatch data singleton.
var _dispatch_data_empty_val dispatch_data_t

// SourceType identifies the type of a dispatch source.
type SourceType uintptr

// Source type constants loaded via dlsym.
var (
	SourceTypeDataAdd     SourceType
	SourceTypeDataOr      SourceType
	SourceTypeDataReplace SourceType
	SourceTypeMachSend    SourceType
	SourceTypeMachRecv    SourceType
	SourceTypeMemPressure SourceType
	SourceTypeProc        SourceType
	SourceTypeRead        SourceType
	SourceTypeSignal      SourceType
	SourceTypeTimer       SourceType
	SourceTypeVnode       SourceType
	SourceTypeWrite       SourceType
)

// ProcFlags for DISPATCH_SOURCE_TYPE_PROC sources.
type ProcFlags uintptr

const (
	ProcExit   ProcFlags = 0x80000000
	ProcFork   ProcFlags = 0x40000000
	ProcExec   ProcFlags = 0x20000000
	ProcSignal ProcFlags = 0x08000000
)

// VnodeFlags for DISPATCH_SOURCE_TYPE_VNODE sources.
type VnodeFlags uintptr

const (
	VnodeDelete  VnodeFlags = 0x1
	VnodeWrite   VnodeFlags = 0x2
	VnodeExtend  VnodeFlags = 0x4
	VnodeAttrib  VnodeFlags = 0x8
	VnodeLink    VnodeFlags = 0x10
	VnodeRename  VnodeFlags = 0x20
	VnodeRevoke  VnodeFlags = 0x40
	VnodeFunlock VnodeFlags = 0x100
)

// MemoryPressureFlags for DISPATCH_SOURCE_TYPE_MEMORYPRESSURE sources.
type MemoryPressureFlags uintptr

const (
	MemPressureNormal   MemoryPressureFlags = 0x01
	MemPressureWarn     MemoryPressureFlags = 0x02
	MemPressureCritical MemoryPressureFlags = 0x04
)

// TimerFlags for dispatch_source_set_timer.
type TimerFlags uint

const (
	TimerStrict TimerFlags = 0x1
)

// IOType identifies the type of a dispatch IO channel.
type IOType uint

const (
	IOStream IOType = 0
	IORandom IOType = 1
)

// IOCloseFlags for dispatch_io_close.
type IOCloseFlags uint

const (
	IOStop IOCloseFlags = 0x1
)

// IOIntervalFlags for dispatch_io_set_interval.
type IOIntervalFlags uint

const (
	IOStrictInterval IOIntervalFlags = 0x1
)

// persistentWorkMap stores event handler closures for dispatch sources.
// Unlike workMap, these are not deleted after execution (sources fire repeatedly).
var persistentWorkMap sync.Map // id (uintptr) → func()
var persistentWorkCounter atomic.Uint64

// cancelWorkMap stores cancel handler closures for dispatch sources.
var cancelWorkMap sync.Map // id (uintptr) → func()

// registrationWorkMap stores registration handler closures for dispatch sources.
var registrationWorkMap sync.Map // id (uintptr) → func()

// ioWorkMap stores IO completion handler closures.
var ioWorkMap sync.Map // id (uintptr) → func(bool, Data, error)

// ioCleanupMap stores IO channel cleanup handler closures.
var ioCleanupMap sync.Map // id (uintptr) → func(error)

var ioWorkCounter atomic.Uint64

// workMap stores pending work closures keyed by a monotonic ID.
// dispatch_*_f functions receive the ID as the context pointer,
// and the single shared callback looks up and executes the closure.
// This avoids calling purego.NewCallback per dispatch, which would
// exhaust the 2000-callback limit.
var workMap struct {
	mu    sync.Mutex
	items map[uintptr]workItem
}

var workID atomic.Uintptr

type workItem struct {
	fn    func()
	token *uintptr
}

// storeWork saves a closure and returns a context pointer for dispatch_*_f.
func storeWork(fn func()) unsafe.Pointer {
	token := new(uintptr)
	*token = workID.Add(1)
	key := uintptr(unsafe.Pointer(token))
	workMap.mu.Lock()
	workMap.items[key] = workItem{fn: fn, token: token}
	workMap.mu.Unlock()
	return unsafe.Pointer(token)
}

// sharedTrampoline is the single C callback used by all dispatch operations.
// It receives the work ID as its context argument, looks up the closure,
// and executes it.
var sharedTrampoline unsafe.Pointer

// sharedPersistentTrampoline is the callback for dispatch source event handlers.
// Unlike sharedTrampoline, it does NOT delete the closure (sources fire repeatedly).
var sharedPersistentTrampoline uintptr

// sharedCancelTrampoline is the callback for dispatch source cancel handlers.
var sharedCancelTrampoline uintptr

// sharedRegistrationTrampoline is the callback for dispatch source registration handlers.
var sharedRegistrationTrampoline uintptr

// sharedIOTrampoline is the callback for dispatch IO completion handlers.
var sharedIOTrampoline uintptr

// sharedIOCleanupTrampoline is the callback for dispatch IO channel cleanup handlers.
var sharedIOCleanupTrampoline uintptr

// sharedBarrierTrampoline is the callback for dispatch IO barrier operations.
var sharedBarrierTrampoline uintptr

func storeIOWork(fn func(bool, Data, error)) uintptr {
	id := uintptr(ioWorkCounter.Add(1))
	ioWorkMap.Store(id, fn)
	return id
}

func storeIOCleanup(fn func(error)) uintptr {
	id := uintptr(ioWorkCounter.Add(1))
	ioCleanupMap.Store(id, fn)
	return id
}

func newIOCleanupCallback(cleanup func(error)) uintptr {
	cleanupID := storeIOCleanup(cleanup)
	return purego.NewCallback(func(errCode int32) {
		if fn, ok := ioCleanupMap.LoadAndDelete(cleanupID); ok {
			var goErr error
			if errCode != 0 {
				goErr = syscall.Errno(errCode)
			}
			fn.(func(error))(goErr)
		}
	})
}

func init() {
	workMap.items = make(map[uintptr]workItem)

	sharedTrampoline = unsafe.Pointer(purego.NewCallback(func(ctx uintptr) {
		workMap.mu.Lock()
		item := workMap.items[ctx]
		delete(workMap.items, ctx)
		workMap.mu.Unlock()
		if item.fn != nil {
			item.fn()
		}
	}))

	sharedPersistentTrampoline = purego.NewCallback(func(ctx uintptr) {
		if fn, ok := persistentWorkMap.Load(ctx); ok {
			fn.(func())()
		}
	})

	sharedCancelTrampoline = purego.NewCallback(func(ctx uintptr) {
		if fn, ok := cancelWorkMap.LoadAndDelete(ctx); ok {
			fn.(func())()
		}
		// Also clean up persistent event handler.
		persistentWorkMap.Delete(ctx)
	})

	sharedRegistrationTrampoline = purego.NewCallback(func(ctx uintptr) {
		if fn, ok := registrationWorkMap.LoadAndDelete(ctx); ok {
			fn.(func())()
		}
	})

	sharedIOTrampoline = purego.NewCallback(func(ctx uintptr, done uintptr, dataObj uintptr, errCode int32) {
		if fn, ok := ioWorkMap.Load(ctx); ok {
			var goErr error
			if errCode != 0 {
				goErr = syscall.Errno(errCode)
			}
			isDone := done != 0
			fn.(func(bool, Data, error))(isDone, DataFromHandle(dataObj), goErr)
			if isDone {
				ioWorkMap.Delete(ctx)
			}
		}
	})

	sharedIOCleanupTrampoline = purego.NewCallback(func(errCode int32) {
		// Cleanup handlers don't receive a context — use a side channel.
		// This is handled per-channel via the closure stored at creation time.
	})

	sharedBarrierTrampoline = purego.NewCallback(func(ctx uintptr) {
		workMap.mu.Lock()
		item := workMap.items[ctx]
		delete(workMap.items, ctx)
		workMap.mu.Unlock()
		if item.fn != nil {
			item.fn()
		}
	})

	lib := frameworkHandle
	if lib == 0 {
		for _, path := range frameworkPaths {
			lib, _ = purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
			if lib != 0 {
				break
			}
		}
	}
	if lib == 0 {
		fmt.Fprintf(os.Stderr, "warning: dispatch: failed to load framework from any known path\n")
		_dispatch_io_read_f = func(uintptr, int64, uint64, uintptr, unsafe.Pointer, uintptr) {
			panic("dispatch: dispatch_io_read_f unavailable")
		}
		_dispatch_io_write_f = func(uintptr, int64, uintptr, uintptr, unsafe.Pointer, uintptr) {
			panic("dispatch: dispatch_io_write_f unavailable")
		}
		return
	}
	// dispatch_io private _f variants are not exposed in the public docs.
	purego.RegisterLibFunc(&_dispatch_io_read_f, lib, "dispatch_io_read_f")
	purego.RegisterLibFunc(&_dispatch_io_write_f, lib, "dispatch_io_write_f")

	if sym, err := purego.Dlsym(lib, "_dispatch_queue_attr_concurrent"); err == nil {
		_dispatch_queue_attr_concurrent = dispatch_queue_attr_t(sym)
	}
	if sym, err := purego.Dlsym(lib, "_dispatch_main_q"); err == nil {
		_dispatch_main_q = sym
	}

	// Load dispatch_data_empty global symbol.
	if sym, err := purego.Dlsym(lib, "_dispatch_data_empty"); err == nil {
		_dispatch_data_empty_val = dispatch_data_t(sym)
	}

	// Load source type global symbols.
	sourceTypes := []struct {
		target *SourceType
		name   string
	}{
		{&SourceTypeDataAdd, "_dispatch_source_type_data_add"},
		{&SourceTypeDataOr, "_dispatch_source_type_data_or"},
		{&SourceTypeDataReplace, "_dispatch_source_type_data_replace"},
		{&SourceTypeMachSend, "_dispatch_source_type_mach_send"},
		{&SourceTypeMachRecv, "_dispatch_source_type_mach_recv"},
		{&SourceTypeMemPressure, "_dispatch_source_type_memorypressure"},
		{&SourceTypeProc, "_dispatch_source_type_proc"},
		{&SourceTypeRead, "_dispatch_source_type_read"},
		{&SourceTypeSignal, "_dispatch_source_type_signal"},
		{&SourceTypeTimer, "_dispatch_source_type_timer"},
		{&SourceTypeVnode, "_dispatch_source_type_vnode"},
		{&SourceTypeWrite, "_dispatch_source_type_write"},
	}
	for _, st := range sourceTypes {
		if sym, err := purego.Dlsym(lib, st.name); err == nil {
			*st.target = SourceType(sym)
		}
	}
}

// QoS (Quality of Service) classes for dispatch queues.
// Higher QoS classes get more system resources.
type QOS uint32

const (
	// QOSUnspecified means no explicit quality of service class.
	QOSUnspecified QOS = 0

	// QOSUserInteractive is for work that is interacting with the user,
	// such as operating on the main thread, refreshing the UI, or performing animations.
	QOSUserInteractive QOS = 0x21

	// QOSUserInitiated is for work that the user has initiated and is waiting for.
	QOSUserInitiated QOS = 0x19

	// QOSDefault is the default QoS class used when no explicit class is specified.
	QOSDefault QOS = 0x15

	// QOSUtility is for work that the user is unlikely to be immediately waiting for.
	QOSUtility QOS = 0x11

	// QOSBackground is for work that is not visible to the user, such as indexing or syncing.
	QOSBackground QOS = 0x09
)

// AutoreleaseFrequency controls autorelease pool behavior for queue attrs.
type AutoreleaseFrequency uintptr

const (
	AutoreleaseFrequencyInherit  AutoreleaseFrequency = 0
	AutoreleaseFrequencyWorkItem AutoreleaseFrequency = 1
	AutoreleaseFrequencyNever    AutoreleaseFrequency = 2
)

// Time constants for dispatch operations.
const (
	// TimeNow represents the current time (no delay).
	TimeNow Dispatch_time_t = 0

	// TimeForever represents an infinite timeout.
	TimeForever Dispatch_time_t = ^Dispatch_time_t(0)
)

// QueueAttr configures queue creation.
type QueueAttr struct {
	attr unsafe.Pointer
}

func (a QueueAttr) raw() dispatch_queue_attr_t {
	return dispatch_queue_attr_t(uintptr(a.attr))
}

// SerialQueueAttr returns the default serial queue attribute.
func SerialQueueAttr() QueueAttr {
	return QueueAttr{}
}

// ConcurrentQueueAttr returns the concurrent queue attribute.
func ConcurrentQueueAttr() QueueAttr {
	return QueueAttr{attr: unsafe.Pointer(uintptr(_dispatch_queue_attr_concurrent))}
}

// InitiallyInactive returns a queue attribute that creates inactive queues.
func (a QueueAttr) InitiallyInactive() QueueAttr {
	return QueueAttr{attr: _dispatch_queue_attr_make_initially_inactive(a.attr)}
}

// WithAutoreleaseFrequency returns a queue attribute with the given autorelease frequency.
func (a QueueAttr) WithAutoreleaseFrequency(freq AutoreleaseFrequency) (QueueAttr, error) {
	attr := _dispatch_queue_attr_make_with_autorelease_frequency(a.attr, uintptr(freq))
	if attr == nil {
		return QueueAttr{}, fmt.Errorf("dispatch: invalid autorelease frequency %d", freq)
	}
	return QueueAttr{attr: attr}, nil
}

// WithQOS returns a queue attribute with the given QoS class and relative priority.
func (a QueueAttr) WithQOS(qos QOS, relativePriority int) (QueueAttr, error) {
	attr := _dispatch_queue_attr_make_with_qos_class(a.attr, uint32(qos), relativePriority)
	if attr == nil {
		return QueueAttr{}, fmt.Errorf("dispatch: invalid qos class %d or relative priority %d", qos, relativePriority)
	}
	return QueueAttr{attr: attr}, nil
}

// WorkItemFlags configure dispatch work items.
type WorkItemFlags uintptr

const (
	WorkItemBarrier         WorkItemFlags = 0x1
	WorkItemDetached        WorkItemFlags = 0x2
	WorkItemAssignCurrent   WorkItemFlags = 0x4
	WorkItemNoQOSClass      WorkItemFlags = 0x8
	WorkItemInheritQOSClass WorkItemFlags = 0x10
	WorkItemEnforceQOSClass WorkItemFlags = 0x20
)

// Queue wraps a dispatch queue with Go-friendly methods.
type Queue struct {
	queue dispatch_queue_t
}

// WorkItem wraps a dispatch block object.
type WorkItem struct {
	block objc.Block
}

// ID returns the underlying queue handle as an objc.ID for framework compatibility.
func (q Queue) ID() objc.ID {
	return objc.ID(q.queue)
}

// GetID implements the objectivec.IObject interface.
func (q Queue) GetID() objc.ID {
	return q.ID()
}

// Group wraps a dispatch group for coordinating multiple async operations.
type Group struct {
	group dispatch_group_t
}

// Semaphore wraps a dispatch semaphore for resource counting.
type Semaphore struct {
	sema dispatch_semaphore_t
}

// QueueCreate creates a new serial dispatch queue with the given label.
// Serial queues execute tasks one at a time in FIFO order.
func QueueCreate(label string) Queue {
	return QueueCreateWithAttr(label, SerialQueueAttr())
}

// QueueCreateConcurrent creates a new concurrent dispatch queue with the given label.
// Concurrent queues execute tasks in parallel, subject to system resources.
func QueueCreateConcurrent(label string) Queue {
	return QueueCreateWithAttr(label, ConcurrentQueueAttr())
}

// QueueCreateWithAttr creates a queue with the given attributes.
func QueueCreateWithAttr(label string, attr QueueAttr) Queue {
	return Queue{queue: dispatch_queue_t(_dispatch_queue_create(label, attr.raw()))}
}

// QueueCreateWithTarget creates a queue with the given attributes and target queue.
// A zero target queue uses libdispatch's default target queue.
func QueueCreateWithTarget(label string, attr QueueAttr, target Queue) Queue {
	return Queue{queue: dispatch_queue_t(_dispatch_queue_create_with_target(label, attr.attr, uintptr(target.queue)))}
}

// GetGlobalQueue returns a global concurrent queue with the specified QoS class.
// Global queues are shared system resources and should not be released.
func GetGlobalQueue(qos QOS) Queue {
	return Queue{queue: dispatch_queue_t(_dispatch_get_global_queue(int(qos), 0))}
}

// MainQueue returns the main dispatch queue.
// Work submitted to this queue executes on the application's main thread.
func MainQueue() Queue {
	return Queue{queue: dispatch_queue_t(_dispatch_main_q)}
}

// Main enters the main dispatch event loop and does not return.
func Main() {
	_dispatch_main()
}

// Activate activates an initially inactive queue.
func (q Queue) Activate() {
	_dispatch_activate(uintptr(q.queue))
}

// Resume resumes execution of a suspended queue.
func (q Queue) Resume() {
	_dispatch_resume(uintptr(q.queue))
}

// Suspend suspends execution of the queue.
func (q Queue) Suspend() {
	_dispatch_suspend(uintptr(q.queue))
}

// Async submits a function for asynchronous execution on the queue.
// The function will execute on a GCD-managed thread.
func (q Queue) Async(work func()) {
	_dispatch_async_f(uintptr(q.queue), storeWork(work), sharedTrampoline)
}

// Sync submits a function for synchronous execution on the queue.
// This blocks until the work completes.
//
// Warning: Do not call Sync on a serial queue from within that same queue,
// as this will deadlock.
func (q Queue) Sync(work func()) {
	_dispatch_sync_f(uintptr(q.queue), storeWork(work), sharedTrampoline)
}

// AsyncAndWait submits a function for execution and waits for it to complete.
func (q Queue) AsyncAndWait(work func()) {
	_dispatch_async_and_wait_f(uintptr(q.queue), storeWork(work), sharedTrampoline)
}

// BarrierAsync submits a barrier function for asynchronous execution.
// Only meaningful on concurrent queues - waits for all prior tasks
// to complete, executes exclusively, then resumes concurrent execution.
func (q Queue) BarrierAsync(work func()) {
	_dispatch_barrier_async_f(uintptr(q.queue), storeWork(work), sharedTrampoline)
}

// BarrierSync submits a barrier function and waits for it to complete.
func (q Queue) BarrierSync(work func()) {
	_dispatch_barrier_sync_f(uintptr(q.queue), storeWork(work), sharedTrampoline)
}

// Label returns the label assigned to the queue at creation time.
func (q Queue) Label() string {
	ptr := _dispatch_queue_get_label(uintptr(q.queue))
	if ptr == nil {
		return ""
	}
	return objc.GoString(ptr)
}

// Handle returns the underlying dispatch queue handle for advanced usage.
func (q Queue) Handle() uintptr {
	return uintptr(q.queue)
}

// QOSClass returns the queue's QoS class and relative priority.
func (q Queue) QOSClass() (QOS, int) {
	var relativePriority int32
	qos := _dispatch_queue_get_qos_class(uintptr(q.queue), &relativePriority)
	return QOS(qos), int(relativePriority)
}

// QueueFromHandle creates a Queue from a raw handle.
func QueueFromHandle(handle uintptr) Queue {
	return Queue{queue: dispatch_queue_t(handle)}
}

// SetTargetQueue changes the queue's target queue.
// A zero target queue resets to libdispatch's default target queue.
func (q Queue) SetTargetQueue(target Queue) {
	_dispatch_set_target_queue(uintptr(q.queue), uintptr(target.queue))
}

// AssertCurrent verifies that the current execution context is this queue.
func (q Queue) AssertCurrent() {
	_dispatch_assert_queue(uintptr(q.queue))
}

// AssertCurrentBarrier verifies that the current execution context is this queue as a barrier.
func (q Queue) AssertCurrentBarrier() {
	_dispatch_assert_queue_barrier(uintptr(q.queue))
}

// AssertNotCurrent verifies that the current execution context is not this queue.
func (q Queue) AssertNotCurrent() {
	_dispatch_assert_queue_not(uintptr(q.queue))
}

// AsyncWorkItem submits a work item for asynchronous execution.
func (q Queue) AsyncWorkItem(item WorkItem) {
	_dispatch_async(uintptr(q.queue), unsafe.Pointer(item.block))
}

// SyncWorkItem submits a work item for synchronous execution.
func (q Queue) SyncWorkItem(item WorkItem) {
	_dispatch_sync(uintptr(q.queue), unsafe.Pointer(item.block))
}

// AsyncAndWaitWorkItem submits a work item and waits for it to complete.
func (q Queue) AsyncAndWaitWorkItem(item WorkItem) {
	_dispatch_async_and_wait(uintptr(q.queue), unsafe.Pointer(item.block))
}

// BarrierAsyncWorkItem submits a barrier work item for asynchronous execution.
func (q Queue) BarrierAsyncWorkItem(item WorkItem) {
	_dispatch_barrier_async(uintptr(q.queue), unsafe.Pointer(item.block))
}

// BarrierSyncWorkItem submits a barrier work item and waits for it to complete.
func (q Queue) BarrierSyncWorkItem(item WorkItem) {
	_dispatch_barrier_sync(uintptr(q.queue), unsafe.Pointer(item.block))
}

// After schedules work to execute after a delay.
func After(when Dispatch_time_t, queue Queue, work func()) {
	_dispatch_after_f(uint64(when), uintptr(queue.queue), storeWork(work), sharedTrampoline)
}

// Apply submits work for parallel execution across the given number of iterations.
func Apply(iterations int, queue Queue, work func(iteration int)) {
	if iterations <= 0 {
		return
	}
	block := objc.NewBlock(func(_ objc.Block, iteration uintptr) {
		work(int(iteration))
	})
	defer block.Release()
	_dispatch_apply(uintptr(iterations), uintptr(queue.queue), unsafe.Pointer(block))
}

// ApplyAuto submits work for parallel execution using libdispatch's automatic queue selection.
func ApplyAuto(iterations int, work func(iteration int)) {
	Apply(iterations, Queue{}, work)
}

// TimeFromNow returns a dispatch time representing now + the given nanoseconds.
func TimeFromNow(nanoseconds int64) Dispatch_time_t {
	return Dispatch_time_t(_dispatch_time(uint64(TimeNow), nanoseconds))
}

// WorkItemCreate creates a work item from a Go function.
func WorkItemCreate(flags WorkItemFlags, work func()) WorkItem {
	block := objc.NewBlock(func(_ objc.Block) {
		work()
	})
	item := WorkItem{block: objc.Block(_dispatch_block_create(uintptr(flags), unsafe.Pointer(block)))}
	block.Release()
	return item
}

// WorkItemCreateWithQOS creates a work item with an explicit QoS class.
func WorkItemCreateWithQOS(flags WorkItemFlags, qos QOS, relativePriority int, work func()) WorkItem {
	block := objc.NewBlock(func(_ objc.Block) {
		work()
	})
	item := WorkItem{block: objc.Block(_dispatch_block_create_with_qos_class(uintptr(flags), uint32(qos), relativePriority, unsafe.Pointer(block)))}
	block.Release()
	return item
}

// WorkItemHandle returns the underlying dispatch block handle.
func (w WorkItem) Handle() uintptr {
	return uintptr(w.block)
}

// Perform invokes the work item directly on the current thread.
func (w WorkItem) Perform() {
	w.block.Invoke()
}

// Notify schedules work to run when the work item completes.
func (w WorkItem) Notify(queue Queue, work func()) {
	block := objc.NewBlock(func(_ objc.Block) {
		work()
	})
	defer block.Release()
	_dispatch_block_notify(unsafe.Pointer(w.block), uintptr(queue.queue), unsafe.Pointer(block))
}

// Cancel cancels future execution of the work item.
func (w WorkItem) Cancel() {
	_dispatch_block_cancel(unsafe.Pointer(w.block))
}

// IsCancelled reports whether the work item has been cancelled.
func (w WorkItem) IsCancelled() bool {
	return _dispatch_block_testcancel(unsafe.Pointer(w.block)) != 0
}

// Wait blocks until the work item completes or timeout expires.
func (w WorkItem) Wait(timeout Dispatch_time_t) bool {
	return _dispatch_block_wait(unsafe.Pointer(w.block), uint64(timeout)) == 0
}

// Release releases the underlying block object.
func (w WorkItem) Release() {
	if w.block != 0 {
		w.block.Release()
	}
}

// GroupCreate creates a new dispatch group for coordinating async operations.
func GroupCreate() Group {
	return Group{group: dispatch_group_t(_dispatch_group_create())}
}

// Async submits work to a queue as part of the group.
func (g Group) Async(queue Queue, work func()) {
	_dispatch_group_async_f(uintptr(g.group), uintptr(queue.queue), storeWork(work), sharedTrampoline)
}

// Wait blocks until all work in the group completes or timeout expires.
// Returns true if all work completed, false if timeout expired.
func (g Group) Wait(timeout Dispatch_time_t) bool {
	result := _dispatch_group_wait(uintptr(g.group), uint64(timeout))
	return result == 0
}

// Notify schedules work to execute when all current group work completes.
func (g Group) Notify(queue Queue, work func()) {
	_dispatch_group_notify_f(uintptr(g.group), uintptr(queue.queue), storeWork(work), sharedTrampoline)
}

// Enter manually increments the group's task count.
// Each Enter must be balanced with a Leave.
func (g Group) Enter() {
	_dispatch_group_enter(uintptr(g.group))
}

// Leave manually decrements the group's task count.
func (g Group) Leave() {
	_dispatch_group_leave(uintptr(g.group))
}

// Handle returns the underlying dispatch group handle for advanced usage.
func (g Group) Handle() uintptr {
	return uintptr(g.group)
}

// SemaphoreCreate creates a counting semaphore with the given initial value.
// Use value=0 for signaling, value>0 for resource counting.
func SemaphoreCreate(value int) Semaphore {
	return Semaphore{sema: dispatch_semaphore_t(_dispatch_semaphore_create(value))}
}

// Signal increments the semaphore count.
// If threads are waiting, one will be woken.
// Returns true if a thread was woken.
func (s Semaphore) Signal() bool {
	return _dispatch_semaphore_signal(uintptr(s.sema)) != 0
}

// Wait decrements the semaphore count, blocking if count is zero.
// Returns true if the semaphore was acquired, false on timeout.
func (s Semaphore) Wait(timeout Dispatch_time_t) bool {
	return _dispatch_semaphore_wait(uintptr(s.sema), uint64(timeout)) == 0
}

// Handle returns the underlying dispatch semaphore handle for advanced usage.
func (s Semaphore) Handle() uintptr {
	return uintptr(s.sema)
}

// SemaphoreFromHandle creates a Semaphore from a raw handle.
func SemaphoreFromHandle(handle uintptr) Semaphore {
	return Semaphore{sema: dispatch_semaphore_t(handle)}
}

// GroupFromHandle creates a Group from a raw handle.
func GroupFromHandle(handle uintptr) Group {
	return Group{group: dispatch_group_t(handle)}
}

// ---------- Data ----------

// Data wraps a dispatch data object.
type Data struct {
	data dispatch_data_t
}

// DataFromHandle creates a Data from a raw handle.
func DataFromHandle(handle uintptr) Data {
	return Data{data: dispatch_data_t(handle)}
}

// Handle returns the underlying dispatch data handle.
func (d Data) Handle() uintptr {
	return uintptr(d.data)
}

// DataCreate creates a dispatch data object from a Go byte slice.
// The buffer is copied by libdispatch (NULL destructor = copy semantics),
// so the Go slice may be GC'd after this call.
func DataCreate(buf []byte) Data {
	if len(buf) == 0 {
		return DataEmpty()
	}
	var p runtime.Pinner
	p.Pin(&buf[0])
	defer p.Unpin()
	h := _dispatch_data_create(
		unsafe.Pointer(&buf[0]),
		uintptr(len(buf)),
		0,   // NULL queue = default
		nil, // NULL destructor = copy
	)
	return Data{data: dispatch_data_t(h)}
}

// DataEmpty returns the global empty dispatch data singleton.
func DataEmpty() Data {
	return Data{data: _dispatch_data_empty_val}
}

// DataGetSize returns the number of bytes in the data object.
func DataGetSize(d Data) int {
	return int(_dispatch_data_get_size(uintptr(d.data)))
}

// Len returns the number of bytes.
func (d Data) Len() int {
	return DataGetSize(d)
}

// DataCreateConcat concatenates two data objects.
func DataCreateConcat(a, b Data) Data {
	return Data{data: dispatch_data_t(_dispatch_data_create_concat(uintptr(a.data), uintptr(b.data)))}
}

// DataToBytes extracts bytes from a dispatch data object.
// Returns a copy the caller owns.
func DataToBytes(d Data) []byte {
	size := DataGetSize(d)
	if size == 0 {
		return nil
	}
	var ptr unsafe.Pointer
	var sz uintptr
	mapped := _dispatch_data_create_map(uintptr(d.data), &ptr, &sz)
	out := make([]byte, sz)
	copy(out, unsafe.Slice((*byte)(ptr), sz))
	_dispatch_release(mapped)
	return out
}

// Bytes extracts a copy of the bytes from the data object.
func (d Data) Bytes() []byte {
	return DataToBytes(d)
}

// ---------- Source ----------

// Source wraps a dispatch event source.
type Source struct {
	source dispatch_source_t
}

// SourceFromHandle creates a Source from a raw handle.
func SourceFromHandle(handle uintptr) Source {
	return Source{source: dispatch_source_t(handle)}
}

// Handle returns the underlying dispatch source handle.
func (s Source) Handle() uintptr {
	return uintptr(s.source)
}

// SourceCreate creates a new dispatch source to monitor low-level system events.
// The source is created in a suspended state; call Activate or Resume to begin
// receiving events.
func SourceCreate(typ SourceType, handle, mask uintptr, queue Queue) Source {
	s := _dispatch_source_create(Dispatch_source_type_t(typ), handle, mask, uintptr(queue.queue))
	return Source{source: dispatch_source_t(s)}
}

// Activate marks the source as ready to receive events (macOS 10.12+).
func (s Source) Activate() {
	_dispatch_activate(uintptr(s.source))
}

// Resume resumes event delivery (balances a Suspend call or initial creation).
func (s Source) Resume() {
	_dispatch_resume(uintptr(s.source))
}

// Suspend pauses event delivery.
func (s Source) Suspend() {
	_dispatch_suspend(uintptr(s.source))
}

// Cancel asynchronously cancels the source, preventing further events.
func (s Source) Cancel() {
	_dispatch_source_cancel(uintptr(s.source))
}

// IsCancelled returns true if the source has been cancelled.
func (s Source) IsCancelled() bool {
	return _dispatch_source_testcancel(uintptr(s.source)) != 0
}

// GetHandle returns the monitored system handle associated with the source.
func (s Source) GetHandle() uintptr {
	return _dispatch_source_get_handle(uintptr(s.source))
}

// GetMask returns the monitored event mask associated with the source.
func (s Source) GetMask() uintptr {
	return _dispatch_source_get_mask(uintptr(s.source))
}

// GetData returns pending data for the source (meaning varies by source type).
func (s Source) GetData() uintptr {
	return _dispatch_source_get_data(uintptr(s.source))
}

// MergeData merges a value into the source's pending data (for DATA_ADD/DATA_OR sources).
func (s Source) MergeData(value uintptr) {
	_dispatch_source_merge_data(uintptr(s.source), value)
}

// SetEventHandler installs a handler called each time the source fires.
func (s Source) SetEventHandler(handler func()) {
	id := uintptr(persistentWorkCounter.Add(1))
	persistentWorkMap.Store(id, handler)
	_dispatch_source_set_event_handler_f(uintptr(s.source), unsafe.Pointer(sharedPersistentTrampoline))
	// Set the context to our work ID.
	_dispatch_set_context(uintptr(s.source), id)
}

// SetCancelHandler installs a handler called when the source is cancelled.
func (s Source) SetCancelHandler(handler func()) {
	// Use the same context ID as the event handler.
	// The cancel handler fires once, so we use LoadAndDelete.
	// We need to read the current context to associate the cancel handler.
	ctx := _dispatch_get_context(uintptr(s.source))
	cancelWorkMap.Store(ctx, handler)
	_dispatch_source_set_cancel_handler_f(uintptr(s.source), unsafe.Pointer(sharedCancelTrampoline))
}

// SetRegistrationHandler installs a handler called once when the source
// is first activated (registered with the kernel).
func (s Source) SetRegistrationHandler(handler func()) {
	ctx := _dispatch_get_context(uintptr(s.source))
	registrationWorkMap.Store(ctx, handler)
	_dispatch_source_set_registration_handler_f(uintptr(s.source), unsafe.Pointer(sharedRegistrationTrampoline))
}

// SetTimer configures a timer source's start time, interval, and leeway.
func (s Source) SetTimer(start Dispatch_time_t, interval, leeway time.Duration) {
	_dispatch_source_set_timer(uintptr(s.source), uint64(start), uint64(interval.Nanoseconds()), uint64(leeway.Nanoseconds()))
}

func newDataSource(typ SourceType, handle, mask uintptr, queue Queue, handler func(uintptr)) Source {
	s := SourceCreate(typ, handle, mask, queue)
	s.SetEventHandler(func() {
		handler(s.GetData())
	})
	s.Activate()
	return s
}

// NewDataAddSource creates an activated data-add source.
func NewDataAddSource(queue Queue, handler func(value uintptr)) Source {
	return newDataSource(SourceTypeDataAdd, 0, 0, queue, handler)
}

// NewDataOrSource creates an activated data-or source.
func NewDataOrSource(queue Queue, handler func(value uintptr)) Source {
	return newDataSource(SourceTypeDataOr, 0, 0, queue, handler)
}

// NewDataReplaceSource creates an activated data-replace source.
func NewDataReplaceSource(queue Queue, handler func(value uintptr)) Source {
	return newDataSource(SourceTypeDataReplace, 0, 0, queue, handler)
}

// NewReadSource creates an activated source that fires when bytes are ready to read.
func NewReadSource(fd int, queue Queue, handler func(bytesAvailable uintptr)) Source {
	return newDataSource(SourceTypeRead, uintptr(fd), 0, queue, handler)
}

// NewWriteSource creates an activated source that fires when buffer space is available.
func NewWriteSource(fd int, queue Queue, handler func(bufferSpace uintptr)) Source {
	return newDataSource(SourceTypeWrite, uintptr(fd), 0, queue, handler)
}

// NewSignalSource creates an activated source that fires when the current process receives sig.
func NewSignalSource(sig syscall.Signal, queue Queue, handler func(count uintptr)) Source {
	return newDataSource(SourceTypeSignal, uintptr(sig), 0, queue, handler)
}

// NewMemoryPressureSource creates an activated source for memory pressure changes.
func NewMemoryPressureSource(mask MemoryPressureFlags, queue Queue, handler func(events MemoryPressureFlags)) Source {
	return newDataSource(SourceTypeMemPressure, 0, uintptr(mask), queue, func(value uintptr) {
		handler(MemoryPressureFlags(value))
	})
}

// NewProcessSource creates an activated source that fires when process events occur.
func NewProcessSource(pid int, mask ProcFlags, queue Queue, handler func(events ProcFlags)) Source {
	return newDataSource(SourceTypeProc, uintptr(pid), uintptr(mask), queue, func(value uintptr) {
		handler(ProcFlags(value))
	})
}

// NewVnodeSource creates an activated source that fires when vnode events occur.
func NewVnodeSource(fd int, mask VnodeFlags, queue Queue, handler func(events VnodeFlags)) Source {
	return newDataSource(SourceTypeVnode, uintptr(fd), uintptr(mask), queue, func(value uintptr) {
		handler(VnodeFlags(value))
	})
}

// NewTimerSource creates and configures a timer dispatch source.
// The source is returned in an activated state.
func NewTimerSource(interval, leeway time.Duration, queue Queue, handler func()) Source {
	s := SourceCreate(SourceTypeTimer, 0, 0, queue)
	s.SetEventHandler(handler)
	s.SetTimer(TimeNow, interval, leeway)
	s.Activate()
	return s
}

// ---------- IO ----------

// IO wraps a dispatch I/O channel.
type IO struct {
	io dispatch_io_t
}

// IOFromHandle creates an IO from a raw handle.
func IOFromHandle(handle uintptr) IO {
	return IO{io: dispatch_io_t(handle)}
}

// Handle returns the underlying dispatch I/O handle.
func (i IO) Handle() uintptr {
	return uintptr(i.io)
}

// IOCreate creates a dispatch IO channel for the given file descriptor.
// The cleanup handler is called when the channel is closed.
func IOCreate(typ IOType, fd int, queue Queue, cleanup func(err error)) IO {
	h := _dispatch_io_create(uint(typ), int32(fd), uintptr(queue.queue), newIOCleanupCallback(cleanup))
	return IO{io: dispatch_io_t(h)}
}

// IOCreateWithPath creates a dispatch IO channel for the given file path.
func IOCreateWithPath(typ IOType, path string, oflag int, mode uint32, queue Queue, cleanup func(err error)) IO {
	h := _dispatch_io_create_with_path(uint(typ), path, oflag, uint16(mode), uintptr(queue.queue), newIOCleanupCallback(cleanup))
	return IO{io: dispatch_io_t(h)}
}

// IOCreateWithIO creates a dispatch IO channel derived from an existing channel.
func IOCreateWithIO(typ IOType, parent IO, queue Queue, cleanup func(err error)) IO {
	h := _dispatch_io_create_with_io(uint(typ), uintptr(parent.io), uintptr(queue.queue), newIOCleanupCallback(cleanup))
	return IO{io: dispatch_io_t(h)}
}

// Read reads data from the channel at the given offset.
// The handler is called one or more times as data becomes available.
// When done is true, all data has been read (or an error occurred).
func (i IO) Read(offset int64, length uint64, queue Queue, handler func(done bool, data Data, err error)) {
	id := storeIOWork(handler)
	_dispatch_io_read_f(uintptr(i.io), offset, length, uintptr(queue.queue), unsafe.Pointer(uintptr(id)), sharedIOTrampoline)
}

// Write writes data to the channel at the given offset.
func (i IO) Write(offset int64, data Data, queue Queue, handler func(done bool, remaining Data, err error)) {
	id := storeIOWork(handler)
	_dispatch_io_write_f(uintptr(i.io), offset, uintptr(data.data), uintptr(queue.queue), unsafe.Pointer(uintptr(id)), sharedIOTrampoline)
}

// Close closes the IO channel. Pass IOStop to cancel outstanding operations.
func (i IO) Close(flags IOCloseFlags) {
	_dispatch_io_close(uintptr(i.io), uint(flags))
}

// Barrier schedules a barrier on the IO channel. The barrier function
// executes when all prior read/write operations complete.
func (i IO) Barrier(fn func()) {
	ctx := storeWork(fn)
	_ = ctx
	_dispatch_io_barrier(uintptr(i.io), unsafe.Pointer(sharedBarrierTrampoline))
}

// Descriptor returns the file descriptor associated with the channel.
func (i IO) Descriptor() int {
	return int(_dispatch_io_get_descriptor(uintptr(i.io)))
}

// SetHighWater sets the high-water mark for IO operations.
func (i IO) SetHighWater(bytes uint64) {
	_dispatch_io_set_high_water(uintptr(i.io), uintptr(bytes))
}

// SetLowWater sets the low-water mark for IO operations.
func (i IO) SetLowWater(bytes uint64) {
	_dispatch_io_set_low_water(uintptr(i.io), uintptr(bytes))
}

// SetInterval sets the delivery interval for IO handler callbacks.
func (i IO) SetInterval(interval time.Duration, flags IOIntervalFlags) {
	_dispatch_io_set_interval(uintptr(i.io), uint64(interval.Nanoseconds()), uint(flags))
}

// Read schedules a one-shot asynchronous read from a file descriptor.
func Read(fd int, length int, queue Queue, handler func(data Data, err error)) {
	var accumulated []byte
	var lastErr error
	ch := IOCreate(IOStream, fd, queue, func(err error) {})
	ch.Read(0, uint64(length), queue, func(done bool, data Data, err error) {
		if data.Len() > 0 {
			accumulated = append(accumulated, data.Bytes()...)
		}
		if err != nil {
			lastErr = err
		}
		if done {
			handler(DataCreate(accumulated), lastErr)
		}
	})
}

// ReadBytes schedules a one-shot asynchronous read and copies the result into a Go slice.
func ReadBytes(fd int, length int, queue Queue, handler func(data []byte, err error)) {
	Read(fd, length, queue, func(data Data, err error) {
		handler(data.Bytes(), err)
	})
}

// Write schedules a one-shot asynchronous write to a file descriptor.
func Write(fd int, data Data, queue Queue, handler func(remaining Data, err error)) {
	ch := IOCreate(IOStream, fd, queue, func(err error) {})
	ch.Write(0, data, queue, func(done bool, remaining Data, err error) {
		if done {
			if remaining.Handle() == 0 {
				remaining = DataEmpty()
			}
			handler(remaining, err)
		}
	})
}

// WriteBytes schedules a one-shot asynchronous write from a Go slice.
func WriteBytes(fd int, buf []byte, queue Queue, handler func(remaining []byte, err error)) {
	Write(fd, DataCreate(buf), queue, func(remaining Data, err error) {
		handler(remaining.Bytes(), err)
	})
}

// ReadFD is a convenience function that reads up to length bytes from a
// file descriptor using a stream IO channel. The handler receives the
// accumulated bytes when reading is complete.
func ReadFD(fd int, length int, queue Queue, handler func(data []byte, err error)) {
	ReadBytes(fd, length, queue, handler)
}

// WriteFD is a convenience function that writes bytes to a file descriptor.
func WriteFD(fd int, buf []byte, queue Queue, handler func(remaining []byte, err error)) {
	WriteBytes(fd, buf, queue, handler)
}

// Ensure time is used (for Source timer methods).
var _ = time.Second
