// Code generated from Apple documentation for IOBluetooth. DO NOT EDIT.

package iobluetooth

import (
	"sync"
	"unsafe"

	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/kernel"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [IOBluetoothDevice] class.
var (
	_IOBluetoothDeviceClass     IOBluetoothDeviceClass
	_IOBluetoothDeviceClassOnce sync.Once
)

func getIOBluetoothDeviceClass() IOBluetoothDeviceClass {
	_IOBluetoothDeviceClassOnce.Do(func() {
		_IOBluetoothDeviceClass = IOBluetoothDeviceClass{class: objc.GetClass("IOBluetoothDevice")}
	})
	return _IOBluetoothDeviceClass
}

// GetIOBluetoothDeviceClass returns the class object for IOBluetoothDevice.
func GetIOBluetoothDeviceClass() IOBluetoothDeviceClass {
	return getIOBluetoothDeviceClass()
}

type IOBluetoothDeviceClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (ic IOBluetoothDeviceClass) Class() objc.Class {
	return ic.class
}

// Alloc allocates memory for a new instance of the class.
func (ic IOBluetoothDeviceClass) Alloc() IOBluetoothDevice {
	rv := objc.Send[IOBluetoothDevice](objc.ID(ic.class), objc.Sel("alloc"))
	return rv
}

// An instance of IOBluetoothDevice represents a single remote Bluetooth
// device.
//
// # Overview
//
// An IOBluetoothDevice object may exist independent of the existence of a
// baseband connection with the target device. Using this object, a client can
// request creation and destruction of baseband connections, and request the
// opening of L2CAP and RFCOMM channels on the remote device. Many of the
// other APIs in the IOBluetooth framework will return this object, or it’s
// C counterpart (IOBluetoothDeviceRef).
//
// # Instance Properties
//
//   - [IOBluetoothDevice.AddressString]: Get a string representation of the Bluetooth device address for the target device. The format of the string is the same as returned by IOBluetoothNSStringFromDeviceAddress().
//   - [IOBluetoothDevice.ClassOfDevice]: Gets the full class of device value for the remote device.
//   - [IOBluetoothDevice.ConnectionHandle]: Get the connection handle for the baseband connection.
//   - [IOBluetoothDevice.DeviceClassMajor]: Get the major device class of the device.
//   - [IOBluetoothDevice.DeviceClassMinor]: Get the minor service class of the device.
//   - [IOBluetoothDevice.IsHandsFreeAudioGateway]
//   - [IOBluetoothDevice.IsHandsFreeDevice]
//   - [IOBluetoothDevice.LastNameUpdate]: Get the date/time of the last successful remote name request.
//   - [IOBluetoothDevice.Name]: Get the human readable name of the remote device.
//   - [IOBluetoothDevice.NameOrAddress]: Get the human readable name of the remote device. If the name is not present, it will return a string containing the device’s address.
//   - [IOBluetoothDevice.ServiceClassMajor]: Get the major service class of the device.
//   - [IOBluetoothDevice.Services]: Gets an array of service records for the device.
//
// # Instance Methods
//
//   - [IOBluetoothDevice.AddToFavorites]: Adds the target device to the user’s favorite devices list.
//   - [IOBluetoothDevice.AwakeAfterUsingCoder]
//   - [IOBluetoothDevice.CloseConnection]: Close down the baseband connection to the device.
//   - [IOBluetoothDevice.GetAddress]: Get the Bluetooth device address for the target device.
//   - [IOBluetoothDevice.GetClockOffset]: Get the clock offset value of the device.
//   - [IOBluetoothDevice.GetEncryptionMode]: Get the encryption mode for the baseband connection.
//   - [IOBluetoothDevice.GetLastInquiryUpdate]: Get the date/time of the last time the device was returned during an inquiry.
//   - [IOBluetoothDevice.GetLastServicesUpdate]: Get the date/time of the last SDP query.
//   - [IOBluetoothDevice.GetLinkType]: Get the link type for the baseband connection.
//   - [IOBluetoothDevice.GetPageScanMode]: Get the page scan mode for the device.
//   - [IOBluetoothDevice.GetPageScanPeriodMode]: Get the value of the page scan period mode for the device.
//   - [IOBluetoothDevice.GetPageScanRepetitionMode]: Get the value of the page scan repetition mode for the device.
//   - [IOBluetoothDevice.GetServiceRecordForUUID]: Search for a service record containing the given UUID.
//   - [IOBluetoothDevice.HandsFreeAudioGatewayServiceRecord]
//   - [IOBluetoothDevice.HandsFreeDeviceServiceRecord]
//   - [IOBluetoothDevice.IsConnected]: Indicates whether a baseband connection to the device exists.
//   - [IOBluetoothDevice.IsFavorite]: Reports whether the target device is a favorite for the user.
//   - [IOBluetoothDevice.IsIncoming]: Returns TRUE if the device connection was generated by the remote host.
//   - [IOBluetoothDevice.IsPaired]: Returns whether the target device is paired.
//   - [IOBluetoothDevice.OpenConnection]: Create a baseband connection to the device.
//   - [IOBluetoothDevice.OpenConnectionWithTarget]: Create a baseband connection to the device.
//   - [IOBluetoothDevice.OpenConnectionWithPageTimeoutAuthenticationRequired]: Create a baseband connection to the device.
//   - [IOBluetoothDevice.OpenL2CAPChannelAsyncWithPSMDelegate]: Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
//   - [IOBluetoothDevice.OpenL2CAPChannelAsyncWithPSMWithConfigurationDelegate]: Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
//   - [IOBluetoothDevice.OpenL2CAPChannelSyncWithPSMDelegate]: Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
//   - [IOBluetoothDevice.OpenL2CAPChannelSyncWithPSMWithConfigurationDelegate]: Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
//   - [IOBluetoothDevice.OpenRFCOMMChannelAsyncWithChannelIDDelegate]: Opens a new RFCOMM channel to the target device. Returns immediately.
//   - [IOBluetoothDevice.OpenRFCOMMChannelSyncWithChannelIDDelegate]: Opens a new RFCOMM channel to the target device. Returns only once the channel is open or failed to open.
//   - [IOBluetoothDevice.PerformSDPQuery]: Performs an SDP query on the target device.
//   - [IOBluetoothDevice.PerformSDPQueryUuids]: Performs an SDP query on the target device with the specified service UUIDs.
//   - [IOBluetoothDevice.RawRSSI]: Get the raw RSSI device (if connected).
//   - [IOBluetoothDevice.RecentAccessDate]: Returns the date/time of the most recent access of the target device.
//   - [IOBluetoothDevice.RegisterForDisconnectNotificationSelector]: Allows a client to register for device disconnect notification.
//   - [IOBluetoothDevice.RemoteNameRequest]: Issues a remote name request to the target device.
//   - [IOBluetoothDevice.RemoteNameRequestWithPageTimeout]: Issues a remote name request to the target device.
//   - [IOBluetoothDevice.RemoveFromFavorites]: Removes the target device from the user’s favorite devices list.
//   - [IOBluetoothDevice.RequestAuthentication]: Requests that the existing baseband connection be authenticated.
//   - [IOBluetoothDevice.RSSI]: Get the RSSI device (if connected), above or below the golden range. If the RSSI is within the golden range, a value of 0 is returned. For the actual RSSI value, use getRawRSSI. For more information, see the Bluetooth 4.0 Core Specification.
//   - [IOBluetoothDevice.SendL2CAPEchoRequestLength]: Send an echo request over the L2CAP connection to a remote device.
//   - [IOBluetoothDevice.SetSupervisionTimeout]: Sets the connection supervision timeout.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice
type IOBluetoothDevice struct {
	IOBluetoothObject
}

// IOBluetoothDeviceFromID constructs a [IOBluetoothDevice] from an objc.ID.
//
// An instance of IOBluetoothDevice represents a single remote Bluetooth
// device.
func IOBluetoothDeviceFromID(id objc.ID) IOBluetoothDevice {
	return IOBluetoothDevice{IOBluetoothObject: IOBluetoothObjectFromID(id)}
}

// NOTE: IOBluetoothDevice adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [IOBluetoothDevice] class.
//
// # Instance Properties
//
//   - [IIOBluetoothDevice.AddressString]: Get a string representation of the Bluetooth device address for the target device. The format of the string is the same as returned by IOBluetoothNSStringFromDeviceAddress().
//   - [IIOBluetoothDevice.ClassOfDevice]: Gets the full class of device value for the remote device.
//   - [IIOBluetoothDevice.ConnectionHandle]: Get the connection handle for the baseband connection.
//   - [IIOBluetoothDevice.DeviceClassMajor]: Get the major device class of the device.
//   - [IIOBluetoothDevice.DeviceClassMinor]: Get the minor service class of the device.
//   - [IIOBluetoothDevice.IsHandsFreeAudioGateway]
//   - [IIOBluetoothDevice.IsHandsFreeDevice]
//   - [IIOBluetoothDevice.LastNameUpdate]: Get the date/time of the last successful remote name request.
//   - [IIOBluetoothDevice.Name]: Get the human readable name of the remote device.
//   - [IIOBluetoothDevice.NameOrAddress]: Get the human readable name of the remote device. If the name is not present, it will return a string containing the device’s address.
//   - [IIOBluetoothDevice.ServiceClassMajor]: Get the major service class of the device.
//   - [IIOBluetoothDevice.Services]: Gets an array of service records for the device.
//
// # Instance Methods
//
//   - [IIOBluetoothDevice.AddToFavorites]: Adds the target device to the user’s favorite devices list.
//   - [IIOBluetoothDevice.AwakeAfterUsingCoder]
//   - [IIOBluetoothDevice.CloseConnection]: Close down the baseband connection to the device.
//   - [IIOBluetoothDevice.GetAddress]: Get the Bluetooth device address for the target device.
//   - [IIOBluetoothDevice.GetClockOffset]: Get the clock offset value of the device.
//   - [IIOBluetoothDevice.GetEncryptionMode]: Get the encryption mode for the baseband connection.
//   - [IIOBluetoothDevice.GetLastInquiryUpdate]: Get the date/time of the last time the device was returned during an inquiry.
//   - [IIOBluetoothDevice.GetLastServicesUpdate]: Get the date/time of the last SDP query.
//   - [IIOBluetoothDevice.GetLinkType]: Get the link type for the baseband connection.
//   - [IIOBluetoothDevice.GetPageScanMode]: Get the page scan mode for the device.
//   - [IIOBluetoothDevice.GetPageScanPeriodMode]: Get the value of the page scan period mode for the device.
//   - [IIOBluetoothDevice.GetPageScanRepetitionMode]: Get the value of the page scan repetition mode for the device.
//   - [IIOBluetoothDevice.GetServiceRecordForUUID]: Search for a service record containing the given UUID.
//   - [IIOBluetoothDevice.HandsFreeAudioGatewayServiceRecord]
//   - [IIOBluetoothDevice.HandsFreeDeviceServiceRecord]
//   - [IIOBluetoothDevice.IsConnected]: Indicates whether a baseband connection to the device exists.
//   - [IIOBluetoothDevice.IsFavorite]: Reports whether the target device is a favorite for the user.
//   - [IIOBluetoothDevice.IsIncoming]: Returns TRUE if the device connection was generated by the remote host.
//   - [IIOBluetoothDevice.IsPaired]: Returns whether the target device is paired.
//   - [IIOBluetoothDevice.OpenConnection]: Create a baseband connection to the device.
//   - [IIOBluetoothDevice.OpenConnectionWithTarget]: Create a baseband connection to the device.
//   - [IIOBluetoothDevice.OpenConnectionWithPageTimeoutAuthenticationRequired]: Create a baseband connection to the device.
//   - [IIOBluetoothDevice.OpenL2CAPChannelAsyncWithPSMDelegate]: Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
//   - [IIOBluetoothDevice.OpenL2CAPChannelAsyncWithPSMWithConfigurationDelegate]: Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
//   - [IIOBluetoothDevice.OpenL2CAPChannelSyncWithPSMDelegate]: Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
//   - [IIOBluetoothDevice.OpenL2CAPChannelSyncWithPSMWithConfigurationDelegate]: Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
//   - [IIOBluetoothDevice.OpenRFCOMMChannelAsyncWithChannelIDDelegate]: Opens a new RFCOMM channel to the target device. Returns immediately.
//   - [IIOBluetoothDevice.OpenRFCOMMChannelSyncWithChannelIDDelegate]: Opens a new RFCOMM channel to the target device. Returns only once the channel is open or failed to open.
//   - [IIOBluetoothDevice.PerformSDPQuery]: Performs an SDP query on the target device.
//   - [IIOBluetoothDevice.PerformSDPQueryUuids]: Performs an SDP query on the target device with the specified service UUIDs.
//   - [IIOBluetoothDevice.RawRSSI]: Get the raw RSSI device (if connected).
//   - [IIOBluetoothDevice.RecentAccessDate]: Returns the date/time of the most recent access of the target device.
//   - [IIOBluetoothDevice.RegisterForDisconnectNotificationSelector]: Allows a client to register for device disconnect notification.
//   - [IIOBluetoothDevice.RemoteNameRequest]: Issues a remote name request to the target device.
//   - [IIOBluetoothDevice.RemoteNameRequestWithPageTimeout]: Issues a remote name request to the target device.
//   - [IIOBluetoothDevice.RemoveFromFavorites]: Removes the target device from the user’s favorite devices list.
//   - [IIOBluetoothDevice.RequestAuthentication]: Requests that the existing baseband connection be authenticated.
//   - [IIOBluetoothDevice.RSSI]: Get the RSSI device (if connected), above or below the golden range. If the RSSI is within the golden range, a value of 0 is returned. For the actual RSSI value, use getRawRSSI. For more information, see the Bluetooth 4.0 Core Specification.
//   - [IIOBluetoothDevice.SendL2CAPEchoRequestLength]: Send an echo request over the L2CAP connection to a remote device.
//   - [IIOBluetoothDevice.SetSupervisionTimeout]: Sets the connection supervision timeout.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice
type IIOBluetoothDevice interface {
	IIOBluetoothObject

	// Topic: Instance Properties

	// Get a string representation of the Bluetooth device address for the target device. The format of the string is the same as returned by IOBluetoothNSStringFromDeviceAddress().
	AddressString() string
	// Gets the full class of device value for the remote device.
	ClassOfDevice() BluetoothClassOfDevice
	// Get the connection handle for the baseband connection.
	ConnectionHandle() BluetoothConnectionHandle
	// Get the major device class of the device.
	DeviceClassMajor() BluetoothDeviceClassMajor
	// Get the minor service class of the device.
	DeviceClassMinor() BluetoothDeviceClassMinor
	IsHandsFreeAudioGateway() bool
	IsHandsFreeDevice() bool
	// Get the date/time of the last successful remote name request.
	LastNameUpdate() foundation.NSDate
	// Get the human readable name of the remote device.
	Name() string
	// Get the human readable name of the remote device. If the name is not present, it will return a string containing the device’s address.
	NameOrAddress() string
	// Get the major service class of the device.
	ServiceClassMajor() BluetoothServiceClassMajor
	// Gets an array of service records for the device.
	Services() foundation.INSArray

	// Topic: Instance Methods

	// Adds the target device to the user’s favorite devices list.
	AddToFavorites() kernel.IOReturn
	AwakeAfterUsingCoder(coder foundation.INSCoder) objectivec.IObject
	// Close down the baseband connection to the device.
	CloseConnection() kernel.IOReturn
	// Get the Bluetooth device address for the target device.
	GetAddress() *BluetoothDeviceAddress
	// Get the clock offset value of the device.
	GetClockOffset() BluetoothClockOffset
	// Get the encryption mode for the baseband connection.
	GetEncryptionMode() BluetoothHCIEncryptionMode
	// Get the date/time of the last time the device was returned during an inquiry.
	GetLastInquiryUpdate() foundation.NSDate
	// Get the date/time of the last SDP query.
	GetLastServicesUpdate() foundation.NSDate
	// Get the link type for the baseband connection.
	GetLinkType() BluetoothLinkType
	// Get the page scan mode for the device.
	GetPageScanMode() BluetoothPageScanMode
	// Get the value of the page scan period mode for the device.
	GetPageScanPeriodMode() BluetoothPageScanPeriodMode
	// Get the value of the page scan repetition mode for the device.
	GetPageScanRepetitionMode() BluetoothPageScanRepetitionMode
	// Search for a service record containing the given UUID.
	GetServiceRecordForUUID(sdpUUID IIOBluetoothSDPUUID) IIOBluetoothSDPServiceRecord
	HandsFreeAudioGatewayServiceRecord() IIOBluetoothSDPServiceRecord
	HandsFreeDeviceServiceRecord() IIOBluetoothSDPServiceRecord
	// Indicates whether a baseband connection to the device exists.
	IsConnected() bool
	// Reports whether the target device is a favorite for the user.
	IsFavorite() bool
	// Returns TRUE if the device connection was generated by the remote host.
	IsIncoming() bool
	// Returns whether the target device is paired.
	IsPaired() bool
	// Create a baseband connection to the device.
	OpenConnection() kernel.IOReturn
	// Create a baseband connection to the device.
	OpenConnectionWithTarget(target objectivec.IObject) kernel.IOReturn
	// Create a baseband connection to the device.
	OpenConnectionWithPageTimeoutAuthenticationRequired(target objectivec.IObject, pageTimeoutValue BluetoothHCIPageTimeout, authenticationRequired bool) kernel.IOReturn
	// Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
	OpenL2CAPChannelAsyncWithPSMDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelDelegate objectivec.IObject) kernel.IOReturn
	// Opens a new L2CAP channel to the target device. Returns immediately after starting the opening process.
	OpenL2CAPChannelAsyncWithPSMWithConfigurationDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelConfiguration foundation.INSDictionary, channelDelegate objectivec.IObject) kernel.IOReturn
	// Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
	OpenL2CAPChannelSyncWithPSMDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelDelegate objectivec.IObject) kernel.IOReturn
	// Opens a new L2CAP channel to the target device. Returns only after the channel is opened.
	OpenL2CAPChannelSyncWithPSMWithConfigurationDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelConfiguration foundation.INSDictionary, channelDelegate objectivec.IObject) kernel.IOReturn
	// Opens a new RFCOMM channel to the target device. Returns immediately.
	OpenRFCOMMChannelAsyncWithChannelIDDelegate(rfcommChannel IIOBluetoothRFCOMMChannel, channelID BluetoothRFCOMMChannelID, channelDelegate objectivec.IObject) kernel.IOReturn
	// Opens a new RFCOMM channel to the target device. Returns only once the channel is open or failed to open.
	OpenRFCOMMChannelSyncWithChannelIDDelegate(rfcommChannel IIOBluetoothRFCOMMChannel, channelID BluetoothRFCOMMChannelID, channelDelegate objectivec.IObject) kernel.IOReturn
	// Performs an SDP query on the target device.
	PerformSDPQuery(target objectivec.IObject) kernel.IOReturn
	// Performs an SDP query on the target device with the specified service UUIDs.
	PerformSDPQueryUuids(target objectivec.IObject, uuidArray foundation.INSArray) kernel.IOReturn
	// Get the raw RSSI device (if connected).
	RawRSSI() BluetoothHCIRSSIValue
	// Returns the date/time of the most recent access of the target device.
	RecentAccessDate() foundation.NSDate
	// Allows a client to register for device disconnect notification.
	RegisterForDisconnectNotificationSelector(observer objectivec.IObject, inSelector objc.SEL) IIOBluetoothUserNotification
	// Issues a remote name request to the target device.
	RemoteNameRequest(target objectivec.IObject) kernel.IOReturn
	// Issues a remote name request to the target device.
	RemoteNameRequestWithPageTimeout(target objectivec.IObject, pageTimeoutValue BluetoothHCIPageTimeout) kernel.IOReturn
	// Removes the target device from the user’s favorite devices list.
	RemoveFromFavorites() kernel.IOReturn
	// Requests that the existing baseband connection be authenticated.
	RequestAuthentication() kernel.IOReturn
	// Get the RSSI device (if connected), above or below the golden range. If the RSSI is within the golden range, a value of 0 is returned. For the actual RSSI value, use getRawRSSI. For more information, see the Bluetooth 4.0 Core Specification.
	RSSI() BluetoothHCIRSSIValue
	// Send an echo request over the L2CAP connection to a remote device.
	SendL2CAPEchoRequestLength(data unsafe.Pointer, length uint16) kernel.IOReturn
	// Sets the connection supervision timeout.
	SetSupervisionTimeout(timeout uint16) kernel.IOReturn
}

// Init initializes the instance.
func (b IOBluetoothDevice) Init() IOBluetoothDevice {
	rv := objc.Send[IOBluetoothDevice](b.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (b IOBluetoothDevice) Autorelease() IOBluetoothDevice {
	rv := objc.Send[IOBluetoothDevice](b.ID, objc.Sel("autorelease"))
	return rv
}

// NewIOBluetoothDevice creates a new IOBluetoothDevice instance.
func NewIOBluetoothDevice() IOBluetoothDevice {
	class := getIOBluetoothDeviceClass()
	rv := objc.Send[IOBluetoothDevice](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Returns the IOBluetoothDevice object for the given BluetoothDeviceAddress
//
// address: Pointer to a BluetoothDeviceAddress for which an IOBluetoothDevice instance
// is desired
//
// # Return Value
//
// # Returns the IOBluetoothDevice object for the given BluetoothDeviceAddress
//
// # Discussion
//
// Within a single application, there will be only one instance of
// IOBluetoothDevice for a given remote device address.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/init(address:)
func NewBluetoothDeviceWithAddress(address *BluetoothDeviceAddress) IOBluetoothDevice {
	rv := objc.Send[objc.ID](objc.ID(getIOBluetoothDeviceClass().class), objc.Sel("deviceWithAddress:"), unsafe.Pointer(address))
	return IOBluetoothDeviceFromID(rv)
}

// Returns the IOBluetoothDevice object for the given BluetoothDeviceAddress
//
// address: Pointer to an NSString containing the BD_ADDR for which an
// IOBluetoothDevice instance is desired. The string should be of the form
// xx:xx:xx:xx:xx:xx
//
// # Return Value
//
// # Returns the IOBluetoothDevice object for the given BluetoothDeviceAddress
//
// # Discussion
//
// Within a single application, there will be only one instance of
// IOBluetoothDevice for a given remote device address.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/init(addressString:)
func NewBluetoothDeviceWithAddressString(address string) IOBluetoothDevice {
	rv := objc.Send[objc.ID](objc.ID(getIOBluetoothDeviceClass().class), objc.Sel("deviceWithAddressString:"), objc.String(address))
	return IOBluetoothDeviceFromID(rv)
}

// Adds the target device to the user’s favorite devices list.
//
// # Return Value
//
// Returns kIOReturnSuccess if the device was successfully added to the
// user’s list of favorite devices.
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/addToFavorites()
func (b IOBluetoothDevice) AddToFavorites() kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("addToFavorites"))
	return kernel.IOReturn(rv)
}

// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/awakeAfter(using:)
func (b IOBluetoothDevice) AwakeAfterUsingCoder(coder foundation.INSCoder) objectivec.IObject {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("awakeAfterUsingCoder:"), coder)
	return objectivec.Object{ID: rv}
}

// Close down the baseband connection to the device.
//
// # Return Value
//
// Returns kIOReturnSuccess if the connection has successfully been closed.
//
// # Discussion
//
// This method is synchronous and will not return until the connection has
// been closed (or the command failed). In the future this API will be changed
// to allow asynchronous operation.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/closeConnection()
func (b IOBluetoothDevice) CloseConnection() kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("closeConnection"))
	return kernel.IOReturn(rv)
}

// Get the Bluetooth device address for the target device.
//
// # Return Value
//
// Returns a pointer to the Bluetooth device address of the target device.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getAddress()
func (b IOBluetoothDevice) GetAddress() *BluetoothDeviceAddress {
	rv := objc.Send[unsafe.Pointer](b.ID, objc.Sel("getAddress"))
	return (*BluetoothDeviceAddress)(rv)
}

// Get the clock offset value of the device.
//
// # Return Value
//
// Returns the clock offset value for the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getClockOffset()
func (b IOBluetoothDevice) GetClockOffset() BluetoothClockOffset {
	rv := objc.Send[BluetoothClockOffset](b.ID, objc.Sel("getClockOffset"))
	return BluetoothClockOffset(rv)
}

// Get the encryption mode for the baseband connection.
//
// # Return Value
//
// Returns the encryption mode for the baseband connection. If no baseband
// connection is present, kEncryptionDisabled is returned.
//
// # Discussion
//
// This method only returns a valid result if a baseband connection is present
// (-isConnected returns TRUE).
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getEncryptionMode()
func (b IOBluetoothDevice) GetEncryptionMode() BluetoothHCIEncryptionMode {
	rv := objc.Send[BluetoothHCIEncryptionMode](b.ID, objc.Sel("getEncryptionMode"))
	return BluetoothHCIEncryptionMode(rv)
}

// Get the date/time of the last time the device was returned during an
// inquiry.
//
// # Return Value
//
// Returns the date/time of the last time the device was seen during an
// inquiry. If the device has never been seen during an inquiry, nil is
// returned.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getLastInquiryUpdate()
func (b IOBluetoothDevice) GetLastInquiryUpdate() foundation.NSDate {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("getLastInquiryUpdate"))
	return foundation.NSDateFromID(rv)
}

// Get the date/time of the last SDP query.
//
// # Return Value
//
// Returns the date/time of the last SDP query. If an SDP query has never been
// performed on the device, nil is returned.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getLastServicesUpdate()
func (b IOBluetoothDevice) GetLastServicesUpdate() foundation.NSDate {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("getLastServicesUpdate"))
	return foundation.NSDateFromID(rv)
}

// Get the link type for the baseband connection.
//
// # Return Value
//
// Returns the link type for the baseband connection. If no baseband
// connection is present, kBluetoothLinkTypeNone is returned.
//
// # Discussion
//
// This method only returns a valid result if a baseband connection is present
// (-isConnected returns TRUE).
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getLinkType()
func (b IOBluetoothDevice) GetLinkType() BluetoothLinkType {
	rv := objc.Send[BluetoothLinkType](b.ID, objc.Sel("getLinkType"))
	return BluetoothLinkType(rv)
}

// Get the page scan mode for the device.
//
// # Return Value
//
// Returns the value for the page scan mode for the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getPageScanMode()
func (b IOBluetoothDevice) GetPageScanMode() BluetoothPageScanMode {
	rv := objc.Send[BluetoothPageScanMode](b.ID, objc.Sel("getPageScanMode"))
	return BluetoothPageScanMode(rv)
}

// Get the value of the page scan period mode for the device.
//
// # Return Value
//
// Returns page scan period mode value for the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getPageScanPeriodMode()
func (b IOBluetoothDevice) GetPageScanPeriodMode() BluetoothPageScanPeriodMode {
	rv := objc.Send[BluetoothPageScanPeriodMode](b.ID, objc.Sel("getPageScanPeriodMode"))
	return BluetoothPageScanPeriodMode(rv)
}

// Get the value of the page scan repetition mode for the device.
//
// # Return Value
//
// Returns the page scan repetition mode value for this device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getPageScanRepetitionMode()
func (b IOBluetoothDevice) GetPageScanRepetitionMode() BluetoothPageScanRepetitionMode {
	rv := objc.Send[BluetoothPageScanRepetitionMode](b.ID, objc.Sel("getPageScanRepetitionMode"))
	return BluetoothPageScanRepetitionMode(rv)
}

// Search for a service record containing the given UUID.
//
// sdpUUID: UUID value to search for.
//
// # Return Value
//
// Returns the first service record that contains the given uuid. If no
// service record is found, nil is returned.
//
// # Discussion
//
// This method searches through the device’s services to find a service that
// contains the given UUID. Only the first service record will be returned.
// This method only operates on services that have already been queried. It
// will not initiate a new query. This method should probably be updated to
// return an array of service records if more than one contains the UUID.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/getServiceRecord(for:)
func (b IOBluetoothDevice) GetServiceRecordForUUID(sdpUUID IIOBluetoothSDPUUID) IIOBluetoothSDPServiceRecord {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("getServiceRecordForUUID:"), sdpUUID)
	return IOBluetoothSDPServiceRecordFromID(rv)
}

// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/handsFreeAudioGatewayServiceRecord()
func (b IOBluetoothDevice) HandsFreeAudioGatewayServiceRecord() IIOBluetoothSDPServiceRecord {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("handsFreeAudioGatewayServiceRecord"))
	return IOBluetoothSDPServiceRecordFromID(rv)
}

// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/handsFreeDeviceServiceRecord()
func (b IOBluetoothDevice) HandsFreeDeviceServiceRecord() IIOBluetoothSDPServiceRecord {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("handsFreeDeviceServiceRecord"))
	return IOBluetoothSDPServiceRecordFromID(rv)
}

// Indicates whether a baseband connection to the device exists.
//
// # Return Value
//
// Returns YES if a baseband connection to the device exists.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isConnected()
func (b IOBluetoothDevice) IsConnected() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isConnected"))
	return rv
}

// Reports whether the target device is a favorite for the user.
//
// # Return Value
//
// Returns TRUE if the target device is a favorite for the user, FALSE if not.
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isFavorite()
func (b IOBluetoothDevice) IsFavorite() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isFavorite"))
	return rv
}

// Returns TRUE if the device connection was generated by the remote host.
//
// # Return Value
//
// Returns TRUE if the device connection was generated by the remote host.
//
// # Discussion
//
// Returns TRUE if the device connection was generated by the remote host.
// False if the connection was generated by some other device that connected
// to the local host.
//
// NOTE: This method is only available in macOS 10.2.7 (Bluetooth v1.3) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isIncoming()
func (b IOBluetoothDevice) IsIncoming() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isIncoming"))
	return rv
}

// Returns whether the target device is paired.
//
// # Return Value
//
// Returns TRUE if the target device is paired, FALSE if not.
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isPaired()
func (b IOBluetoothDevice) IsPaired() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isPaired"))
	return rv
}

// Create a baseband connection to the device.
//
// # Return Value
//
// Returns kIOReturnSuccess if the connection was successfully created.
//
// # Discussion
//
// This method is synchronous and will not return until either a connection
// has been established or the create connection has failed (perhaps timed
// out). This method does the same thing as calling -openConnection: with a
// nil target. This call with proceed without authentication required, and
// using the default page timeout value. If authentication or a non-default
// page timeout is required the method
// -openConnection:withPageTimeout:authenticationRequired: should be used
// instead.
//
// As of OS X 10.7, this method will no longer mask out “Connection
// Exists” ‘errors’ with a success result code; your code must account
// for the cases where the baseband connection is already open.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openConnection()
func (b IOBluetoothDevice) OpenConnection() kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openConnection"))
	return kernel.IOReturn(rv)
}

// Create a baseband connection to the device.
//
// # Return Value
//
// Returns kIOReturnSuccess if the connection was successfully created (or if
// asynchronous, if the CREATE_CONNECTION command was successfully issued).
//
// # Discussion
//
// If a target is specified, the open connection call is asynchronous and on
// completion of the CREATE_CONNECTION command, the method
// -connectionComplete:status: will be called on the specified target. If no
// target is specified, the call is synchronous and will not return until the
// connection is open or the CREATE_CONNECTION call has failed. This call with
// proceed without authentication required, and using the default page timeout
// value. If authentication or a non-default page timeout is required the
// method -openConnection:withPageTimeout:authenticationRequired: should be
// used instead.
//
// As of OS X 10.7, this method will no longer mask out “Connection
// Exists” ‘errors’ with a success result code; your code must account
// for the cases where the baseband connection is already open.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openConnection(_:)
func (b IOBluetoothDevice) OpenConnectionWithTarget(target objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openConnection:"), target)
	return kernel.IOReturn(rv)
}

// Create a baseband connection to the device.
//
// target: The target to message when the create connection call is complete
//
// pageTimeoutValue: The page timeout value to use for this call
//
// authenticationRequired: BOOL value to indicate whether authentication should be required for the
// connection
//
// # Return Value
//
// Returns kIOReturnSuccess if the connection was successfully created (or if
// asynchronous, if the CREATE_CONNECTION command was successfully issued).
//
// # Discussion
//
// If a target is specified, the open connection call is asynchronous and on
// completion of the CREATE_CONNECTION command, the method
// -connectionComplete:status: will be called on the specified target. If no
// target is specified, the call is synchronous and will not return until the
// connection is open or the CREATE_CONNECTION call has failed.
//
// NOTE: This method is only available in macOS 10.2.7 (Bluetooth v1.3) or
// later.
//
// As of OS X 10.7, this method will no longer mask out “Connection
// Exists” ‘errors’ with a success result code; your code must account
// for the cases where the baseband connection is already open.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openConnection(_:withPageTimeout:authenticationRequired:)
func (b IOBluetoothDevice) OpenConnectionWithPageTimeoutAuthenticationRequired(target objectivec.IObject, pageTimeoutValue BluetoothHCIPageTimeout, authenticationRequired bool) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openConnection:withPageTimeout:authenticationRequired:"), target, pageTimeoutValue, authenticationRequired)
	return kernel.IOReturn(rv)
}

// Opens a new L2CAP channel to the target device. Returns immediately after
// starting the opening process.
//
// newChannel: A pointer to an IOBluetoothL2CAPChannel object to receive the L2CAP channel
// requested to be opened. The newChannel pointer will only be set if
// kIOReturnSuccess is returned.
//
// psm: The L2CAP PSM value for the new channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the l2cap uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothL2CAPChannel.h” in the definition of the protocol
// IOBluetoothL2CAPChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing L2CAP channel was found).
//
// # Discussion
//
// This method will begin the process of opening a new L2CAP channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The L2CAP channel open process will not complete until
// the client has registered an incoming data listener on the new channel.
// This prevents a situation where the channel succeeds in being configured
// and opened and receives data before the client is listening and is ready
// for it.
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openL2CAPChannelAsync(_:withPSM:delegate:)
func (b IOBluetoothDevice) OpenL2CAPChannelAsyncWithPSMDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openL2CAPChannelAsync:withPSM:delegate:"), newChannel, psm, channelDelegate)
	return kernel.IOReturn(rv)
}

// Opens a new L2CAP channel to the target device. Returns immediately after
// starting the opening process.
//
// newChannel: A pointer to an IOBluetoothL2CAPChannel object to receive the L2CAP channel
// requested to be opened. The newChannel pointer will only be set if
// kIOReturnSuccess is returned.
//
// psm: The L2CAP PSM value for the new channel.
//
// channelConfiguration: The dictionary that describes the initial configuration for the channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the l2cap uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothL2CAPChannel.h” in the definition of the protocol
// IOBluetoothL2CAPChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing L2CAP channel was found). The channel must be released when
// the caller is done with it.
//
// # Discussion
//
// This method will begin the process of opening a new L2CAP channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The L2CAP channel open process will not complete until
// the client has registered an incoming data listener on the new channel.
// This prevents a situation where the channel succeeds in being configured
// and opened and receives data before the client is listening and is ready
// for it. The L2CAP channel object is already retained when this function
// returns success; the channel must be released when the caller is done with
// it.
//
// NOTE: This method is only available in macOS 10.5 (Bluetooth v2.0) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openL2CAPChannelAsync(_:withPSM:withConfiguration:delegate:)
func (b IOBluetoothDevice) OpenL2CAPChannelAsyncWithPSMWithConfigurationDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelConfiguration foundation.INSDictionary, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openL2CAPChannelAsync:withPSM:withConfiguration:delegate:"), newChannel, psm, channelConfiguration, channelDelegate)
	return kernel.IOReturn(rv)
}

// Opens a new L2CAP channel to the target device. Returns only after the
// channel is opened.
//
// newChannel: A pointer to an IOBluetoothL2CAPChannel object to receive the L2CAP channel
// requested to be opened. The newChannel pointer will only be set if
// kIOReturnSuccess is returned.
//
// psm: The L2CAP PSM value for the new channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the l2cap uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothL2CAPChannel.h” in the definition of the protocol
// IOBluetoothL2CAPChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing L2CAP channel was found).
//
// # Discussion
//
// This method will begin the process of opening a new L2CAP channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The L2CAP channel open process will not complete until
// the client has registered an incoming data listener on the new channel.
// This prevents a situation where the channel succeeds in being configured
// and opened and receives data before the client is listening and is ready
// for it.
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openL2CAPChannelSync(_:withPSM:delegate:)
func (b IOBluetoothDevice) OpenL2CAPChannelSyncWithPSMDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openL2CAPChannelSync:withPSM:delegate:"), newChannel, psm, channelDelegate)
	return kernel.IOReturn(rv)
}

// Opens a new L2CAP channel to the target device. Returns only after the
// channel is opened.
//
// newChannel: A pointer to an IOBluetoothL2CAPChannel object to receive the L2CAP channel
// requested to be opened. The newChannel pointer will only be set if
// kIOReturnSuccess is returned.
//
// psm: The L2CAP PSM value for the new channel.
//
// channelConfiguration: The dictionary that describes the initial configuration for the channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the l2cap uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothL2CAPChannel.h” in the definition of the protocol
// IOBluetoothL2CAPChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing L2CAP channel was found). The channel must be released when
// the caller is done with it.
//
// # Discussion
//
// This method will begin the process of opening a new L2CAP channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The L2CAP channel open process will not complete until
// the client has registered an incoming data listener on the new channel.
// This prevents a situation where the channel succeeds in being configured
// and opened and receives data before the client is listening and is ready
// for it. The L2CAP channel object is already retained when this function
// returns success; the channel must be released when the caller is done with
// it.
//
// NOTE: This method is only available in macOS 10.5 (Bluetooth v2.0) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openL2CAPChannelSync(_:withPSM:withConfiguration:delegate:)
func (b IOBluetoothDevice) OpenL2CAPChannelSyncWithPSMWithConfigurationDelegate(newChannel IIOBluetoothL2CAPChannel, psm BluetoothL2CAPPSM, channelConfiguration foundation.INSDictionary, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openL2CAPChannelSync:withPSM:withConfiguration:delegate:"), newChannel, psm, channelConfiguration, channelDelegate)
	return kernel.IOReturn(rv)
}

// Opens a new RFCOMM channel to the target device. Returns immediately.
//
// rfcommChannel: A pointer to an IOBluetoothRFCOMMChannel object to receive the RFCOMM
// channel requested to be opened. The rfcommChannel pointer will only be set
// if kIOReturnSuccess is returned.
//
// channelID: The RFCOMM channel ID for the new channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the rfcomm uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothRFCOMMChannel.h” in the definition of the protocol
// IOBluetoothRFCOMMChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing RFCOMM channel was found). The channel must be released when
// the caller is done with it.
//
// # Discussion
//
// This method will begin the process of opening a new RFCOMM channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The RFCOMM channel open process will not complete
// until the client has registered an incoming data listener on the new
// channel. The RFCOMM channel object is already retained when this function
// returns success; the channel must be released when the caller is done with
// it.
//
// You should verify that the channel you wish to open exists on the remote
// device before attempting to open it, by performing an SDP query. This is
// recommended because the service might have been removed from the, remote
// device or the channel assignments for the service could have changed (this
// is rare, but it does happen frequently on some devices). This also works
// around a bug that existed in early Leopard versions in certain situations
// where the method would return an error; in these instances, the desired
// RFCOMM channel could not be opened again until the calling app was
// restarted.
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openRFCOMMChannelAsync(_:withChannelID:delegate:)
func (b IOBluetoothDevice) OpenRFCOMMChannelAsyncWithChannelIDDelegate(rfcommChannel IIOBluetoothRFCOMMChannel, channelID BluetoothRFCOMMChannelID, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openRFCOMMChannelAsync:withChannelID:delegate:"), rfcommChannel, channelID, channelDelegate)
	return kernel.IOReturn(rv)
}

// Opens a new RFCOMM channel to the target device. Returns only once the
// channel is open or failed to open.
//
// rfcommChannel: A pointer to an IOBluetoothRFCOMMChannel object to receive the RFCOMM
// channel requested to be opened. The rfcommChannel pointer will only be set
// if kIOReturnSuccess is returned.
//
// channelID: The RFCOMM channel ID for the new channel.
//
// channelDelegate: The object that will play the role of delegate for the channel. A channel
// delegate is the object the rfcomm uses as target for data and events. The
// developer will implement only the the methods he/she is interested in. A
// list of the possible methods is at the end of the file
// “IOBluetoothRFCOMMChannel.h” in the definition of the protocol
// IOBluetoothRFCOMMChannelDelegate.
//
// # Return Value
//
// Returns kIOReturnSuccess if the open process was successfully started (or
// if an existing RFCOMM channel was found). The channel must be released when
// the caller is done with it.
//
// # Discussion
//
// This method will begin the process of opening a new RFCOMM channel to the
// target device. The baseband connection to the device will be opened if it
// is not open already. The RFCOMM channel open process will not complete
// until the client has registered an incoming data listener on the new
// channel. The RFCOMM channel object is already retained when this function
// returns success; the channel must be released when the caller is done with
// it.
//
// You should verify that the channel you wish to open exists on the remote
// device before attempting to open it, by performing an SDP query. This is
// recommended because the service might have been removed from the, remote
// device or the channel assignments for the service could have changed (this
// is rare, but it does happen frequently on some devices). This also works
// around a bug that existed in early Leopard versions in certain situations
// where the method would return an error; in these instances, the desired
// RFCOMM channel could not be opened again until the calling app was
// restarted.
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/openRFCOMMChannelSync(_:withChannelID:delegate:)
func (b IOBluetoothDevice) OpenRFCOMMChannelSyncWithChannelIDDelegate(rfcommChannel IIOBluetoothRFCOMMChannel, channelID BluetoothRFCOMMChannelID, channelDelegate objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("openRFCOMMChannelSync:withChannelID:delegate:"), rfcommChannel, channelID, channelDelegate)
	return kernel.IOReturn(rv)
}

// Performs an SDP query on the target device.
//
// target: The target to message when the SDP query is complete
//
// # Return Value
//
// Returns kIOReturnSuccess if the SDP query was successfully started.
//
// # Discussion
//
// As a result of this call, a baseband connection will be built to the device
// (if not already connected). Then, an L2CAP channel will be opened to the
// SDP server on the device. At that point, a Service Search Attribute request
// will be issued with a UUID of 0x0100 (L2CAP) and an attribute range of
// 0x0000 - 0xffff specified. This will cause the SDP server to return all
// attributes of all L2CAP-derived services on the device. The results
// essentially encompass all services on the device. This function is always
// asynchronous. If a target is specified, when the SDP query is complete (or
// an error is encountered), the method -sdpQueryComplete:status: will be
// called on the given target. If no target is specified, the request is still
// asynchronous, but no callback will be made. That can be useful if the
// client has registered for SDP service changed notifications.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/performSDPQuery(_:)
func (b IOBluetoothDevice) PerformSDPQuery(target objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("performSDPQuery:"), target)
	return kernel.IOReturn(rv)
}

// Performs an SDP query on the target device with the specified service
// UUIDs.
//
// target: The target to message when the SDP query is complete
//
// uuidArray: An array of IOBluetoothSDPUUID objects for each service the caller is
// interested in
//
// # Return Value
//
// Returns kIOReturnSuccess if the SDP query was successfully started.
//
// # Discussion
//
// As a result of this call, a baseband connection will be built to the device
// (if not already connected). Then, an L2CAP channel will be opened to the
// SDP server on the device. At that point, a Service Search Attribute request
// will be issued for each service UUID specified in the UUID array.
//
// This function is always asynchronous. If a target is specified, when the
// SDP query is complete (or an error is encountered), the method
// -sdpQueryComplete:status: will be called on the given target. If no target
// is specified, the request is still asynchronous, but no callback will be
// made. That can be useful if the client has registered for SDP service
// changed notifications.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/performSDPQuery(_:uuids:)
func (b IOBluetoothDevice) PerformSDPQueryUuids(target objectivec.IObject, uuidArray foundation.INSArray) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("performSDPQuery:uuids:"), target, uuidArray)
	return kernel.IOReturn(rv)
}

// Get the raw RSSI device (if connected).
//
// # Return Value
//
// Returns the raw RSSI of the device.
//
// # Discussion
//
// This value is the perceived RSSI value, not relative the the golden range
// (see getRSSI for that value). This value will not available on all
// Bluetooth modules. If the value cannot be read (e.g. the device is
// disconnected) or is not available on a module, a value of +127 will be
// returned.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/rawRSSI()
func (b IOBluetoothDevice) RawRSSI() BluetoothHCIRSSIValue {
	rv := objc.Send[BluetoothHCIRSSIValue](b.ID, objc.Sel("rawRSSI"))
	return BluetoothHCIRSSIValue(rv)
}

// Returns the date/time of the most recent access of the target device.
//
// # Return Value
//
// Returns the date/time of the most recent access of the target device. If
// the device has not been accessed, nil is returned.
//
// # Discussion
//
// This is the date that -recentDevices uses to sort its list of the most
// recently accessed devices.
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/recentAccessDate()
func (b IOBluetoothDevice) RecentAccessDate() foundation.NSDate {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("recentAccessDate"))
	return foundation.NSDateFromID(rv)
}

// Allows a client to register for device disconnect notification.
//
// observer: Target observer object
//
// inSelector: Selector to be sent to the observer when the connection is destroyed
//
// # Return Value
//
// Returns an IOBluetoothUserNotification representing the outstanding device
// disconnect notification. To unregister the notification, call -unregister
// of the returned IOBluetoothUserNotification object. If an error is
// encountered creating the notification, nil is returned.
//
// # Discussion
//
// The given selector will be called on the target observer when the target
// device’s connection is closed. The selector should contain two arguments.
// The first is the user notification object. The second is the
// IOBluetoothDevice that was disconnected.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/register(forDisconnectNotification:selector:)
func (b IOBluetoothDevice) RegisterForDisconnectNotificationSelector(observer objectivec.IObject, inSelector objc.SEL) IIOBluetoothUserNotification {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("registerForDisconnectNotification:selector:"), observer, inSelector)
	return IOBluetoothUserNotificationFromID(rv)
}

// Issues a remote name request to the target device.
//
// target: The target to message when the remote name request is complete
//
// # Return Value
//
// Returns kIOReturnSuccess if the remote name request was successfully issued
// (and if synchronous, if the request completed successfully).
//
// # Discussion
//
// If a target is specified, the request is asynchronous and on completion of
// the request, the method
//
// - (void)remoteNameRequestComplete:(IOBluetoothDevice *)device
// status:(IOReturn)status;
//
// will be called on the specified target. If no target is specified, the
// request is made synchronously and won’t return until the request is
// complete. This call with operate with the default page timeout value. If a
// different page timeout value is desired, the method
// -remoteNameRequest:withPageTimeout: should be used instead.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/remoteNameRequest(_:)
func (b IOBluetoothDevice) RemoteNameRequest(target objectivec.IObject) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("remoteNameRequest:"), target)
	return kernel.IOReturn(rv)
}

// Issues a remote name request to the target device.
//
// target: The target to message when the remote name request is complete
//
// pageTimeoutValue: The page timeout value to use for this call
//
// # Return Value
//
// Returns kIOReturnSuccess if the remote name request was successfully issued
// (and if synchronous, if the request completed successfully).
//
// # Discussion
//
// If a target is specified, the request is asynchronous and on completion of
// the REMOTE_NAME_REQUEST command, the method
// -remoteNameRequestComplete:status:name: will be called on the specified
// target. If no target is specified, the request is made synchronously and
// won’t return until the request is complete.
//
// NOTE: This method is only available in macOS 10.2.7 (Bluetooth v1.3) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/remoteNameRequest(_:withPageTimeout:)
func (b IOBluetoothDevice) RemoteNameRequestWithPageTimeout(target objectivec.IObject, pageTimeoutValue BluetoothHCIPageTimeout) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("remoteNameRequest:withPageTimeout:"), target, pageTimeoutValue)
	return kernel.IOReturn(rv)
}

// Removes the target device from the user’s favorite devices list.
//
// # Return Value
//
// Returns kIOReturnSuccess if the device was successfully removed from the
// user’s list of favorite devices.
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/removeFromFavorites()
func (b IOBluetoothDevice) RemoveFromFavorites() kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("removeFromFavorites"))
	return kernel.IOReturn(rv)
}

// Requests that the existing baseband connection be authenticated.
//
// # Return Value
//
// Returns kIOReturnSuccess if the connection has been successfully been
// authenticated. Returns an error if authentication fails or no baseband
// connection exists.
//
// # Discussion
//
// In order to authenticate a baseband connection, a link key needs to be
// generated as a result of the pairing process. This call will synchronously
// initiate the pairing process with the target device and not return until
// the authentication process is complete. This API will be updated to allow
// for asynchronous operation.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/requestAuthentication()
func (b IOBluetoothDevice) RequestAuthentication() kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("requestAuthentication"))
	return kernel.IOReturn(rv)
}

// Get the RSSI device (if connected), above or below the golden range. If the
// RSSI is within the golden range, a value of 0 is returned. For the actual
// RSSI value, use getRawRSSI. For more information, see the Bluetooth 4.0
// Core Specification.
//
// # Return Value
//
// Returns the RSSI of the device. If the value cannot be read (e.g. the
// device is disconnected), a value of +127 will be returned.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/rssi()
func (b IOBluetoothDevice) RSSI() BluetoothHCIRSSIValue {
	rv := objc.Send[BluetoothHCIRSSIValue](b.ID, objc.Sel("RSSI"))
	return BluetoothHCIRSSIValue(rv)
}

// Send an echo request over the L2CAP connection to a remote device.
//
// data: (Void *) - Pointer to buffer to send.
//
// length: (UInt16) - Length of the buffer to send
//
// # Return Value
//
// Returns kIOReturnSuccess if the echo request was able to be sent.
//
// # Discussion
//
// The current implementation returns when the request has been sent, but does
// not indicate when a response is received. Also, the baseband connection
// must be up for the echo request to be sent. In the future, this method will
// also open the connection if necessary. The API will be updated to allow the
// client to be informed when the echo response has been received (both
// synchronously and asynchronously).
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/sendL2CAPEchoRequest(_:length:)
func (b IOBluetoothDevice) SendL2CAPEchoRequestLength(data unsafe.Pointer, length uint16) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("sendL2CAPEchoRequest:length:"), data, length)
	return kernel.IOReturn(rv)
}

// Sets the connection supervision timeout.
//
// timeout: A client-supplied link supervision timeout value to use to monitor the
// connection. The timeout value should be specified in slots, so you can use
// the BluetoothGetSlotsFromSeconds macro to get the proper value. e.g.
// BluetoothGetSlotsFromSeconds( 5.0 ) will give yield the proper number of
// slots (8000) for 5 seconds.
//
// # Return Value
//
// Returns kIOReturnSuccess if it was possible to set the connection
// supervision timeout.
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.5 (Bluetooth v2.0) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/setSupervisionTimeout(_:)
func (b IOBluetoothDevice) SetSupervisionTimeout(timeout uint16) kernel.IOReturn {
	rv := objc.Send[kernel.IOReturn](b.ID, objc.Sel("setSupervisionTimeout:"), timeout)
	return kernel.IOReturn(rv)
}

// Gets an array of the user’s favorite devices.
//
// # Return Value
//
// Returns an array of device objects representing the user’s favorite
// devices. If the user has no favorites, nil is returned.
//
// # Discussion
//
// The resulting array contains IOBluetoothDevice objects.
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/favoriteDevices()
func (_IOBluetoothDeviceClass IOBluetoothDeviceClass) FavoriteDevices() foundation.INSArray {
	rv := objc.Send[objc.ID](objc.ID(_IOBluetoothDeviceClass.class), objc.Sel("favoriteDevices"))
	return foundation.NSArrayFromID(rv)
}

// Gets an array of all of the paired devices on the system.
//
// # Return Value
//
// Returns an array of device objects for all of the paired devices on the
// system. If there are no paired devices, nil is returned.
//
// # Discussion
//
// The resulting array contains IOBluetoothDevice objects. The paired devices
// are currently NOT stored per user, so this is all devices paired by any
// user.
//
// NOTE: This method is only available in macOS 10.2.5 (Bluetooth v1.2) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/pairedDevices()
func (_IOBluetoothDeviceClass IOBluetoothDeviceClass) PairedDevices() foundation.INSArray {
	rv := objc.Send[objc.ID](objc.ID(_IOBluetoothDeviceClass.class), objc.Sel("pairedDevices"))
	return foundation.NSArrayFromID(rv)
}

// Gets an array of recently used Bluetooth devices.
//
// numDevices: The number of devices to return.
//
// # Return Value
//
// Returns an array of device objects recently used by the system. If no
// devices have been accessed, nil is returned.
//
// # Discussion
//
// The resulting array contains IOBluetoothDevice objects sorted in reverse
// chronological order. The most recently accessed devices are first. If the
// numDevices parameter is 0, all devices accessed by the system are returned.
// If numDevices is non-zero, only the most recent devices are returned.
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/recentDevices(_:)
func (_IOBluetoothDeviceClass IOBluetoothDeviceClass) RecentDevices(numDevices uint64) foundation.INSArray {
	rv := objc.Send[objc.ID](objc.ID(_IOBluetoothDeviceClass.class), objc.Sel("recentDevices:"), numDevices)
	return foundation.NSArrayFromID(rv)
}

// Allows a client to register for device connect notifications for any
// connection.
//
// observer: Target observer object
//
// inSelector: Selector to be sent to the observer when a new connection is made
//
// # Return Value
//
// Returns an IOBluetoothUserNotification representing the outstanding device
// connect notification. To unregister the notification, call -unregister on
// the returned IOBluetoothUserNotification object. If an error is encountered
// creating the notification, nil is returned. The returned
// IOBluetoothUserNotification object will be valid for as long as the
// notification is registered. It is not necessary to retain the result. Once
// -unregister is called on it, it will no longer be valid.
//
// # Discussion
//
// The given selector will be called on the target observer whenever any
// device connection is made. The selector should accept two arguments. The
// first is the user notification object. The second is the device that was
// connected.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/register(forConnectNotifications:selector:)
func (_IOBluetoothDeviceClass IOBluetoothDeviceClass) RegisterForConnectNotificationsSelector(observer objectivec.IObject, inSelector objc.SEL) IOBluetoothUserNotification {
	rv := objc.Send[objc.ID](objc.ID(_IOBluetoothDeviceClass.class), objc.Sel("registerForConnectNotifications:selector:"), observer, inSelector)
	return IOBluetoothUserNotificationFromID(rv)
}

// Get a string representation of the Bluetooth device address for the target
// device. The format of the string is the same as returned by
// IOBluetoothNSStringFromDeviceAddress().
//
// # Discussion
//
// NOTE: This method is only available in macOS 10.2.4 (Bluetooth v1.1) or
// later.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/addressString
func (b IOBluetoothDevice) AddressString() string {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("addressString"))
	return foundation.NSStringFromID(rv).String()
}

// Gets the full class of device value for the remote device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/classOfDevice
func (b IOBluetoothDevice) ClassOfDevice() BluetoothClassOfDevice {
	rv := objc.Send[BluetoothClassOfDevice](b.ID, objc.Sel("classOfDevice"))
	return BluetoothClassOfDevice(rv)
}

// Get the connection handle for the baseband connection.
//
// # Discussion
//
// This method only returns a valid result if a baseband connection is present
// (-isConnected returns TRUE).
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/connectionHandle
func (b IOBluetoothDevice) ConnectionHandle() BluetoothConnectionHandle {
	rv := objc.Send[BluetoothConnectionHandle](b.ID, objc.Sel("connectionHandle"))
	return BluetoothConnectionHandle(rv)
}

// Get the major device class of the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/deviceClassMajor
func (b IOBluetoothDevice) DeviceClassMajor() BluetoothDeviceClassMajor {
	rv := objc.Send[BluetoothDeviceClassMajor](b.ID, objc.Sel("deviceClassMajor"))
	return BluetoothDeviceClassMajor(rv)
}

// Get the minor service class of the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/deviceClassMinor
func (b IOBluetoothDevice) DeviceClassMinor() BluetoothDeviceClassMinor {
	rv := objc.Send[BluetoothDeviceClassMinor](b.ID, objc.Sel("deviceClassMinor"))
	return BluetoothDeviceClassMinor(rv)
}

// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isHandsFreeAudioGateway
func (b IOBluetoothDevice) IsHandsFreeAudioGateway() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isHandsFreeAudioGateway"))
	return rv
}

// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/isHandsFreeDevice
func (b IOBluetoothDevice) IsHandsFreeDevice() bool {
	rv := objc.Send[bool](b.ID, objc.Sel("isHandsFreeDevice"))
	return rv
}

// Get the date/time of the last successful remote name request.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/lastNameUpdate
func (b IOBluetoothDevice) LastNameUpdate() foundation.NSDate {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("lastNameUpdate"))
	return foundation.NSDateFromID(objc.ID(rv))
}

// Get the human readable name of the remote device.
//
// # Discussion
//
// This only returns a value if a remote name request has been performed on
// the target device. If a successful remote name request has not been
// completed, nil is returned. To perform a remote name request, call
// -remoteNameRequest. If a remote name request has been successfully
// completed, the method -getLastNameUpdate will return the date/time of the
// last successful request.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/name
func (b IOBluetoothDevice) Name() string {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("name"))
	return foundation.NSStringFromID(rv).String()
}

// Get the human readable name of the remote device. If the name is not
// present, it will return a string containing the device’s address.
//
// # Discussion
//
// If a remote name request has been successfully completed, the device name
// will be returned. If not, a string containg the device address in the
// format of “XX-XX-XX-XX-XX-XX” will be returned.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/nameOrAddress
func (b IOBluetoothDevice) NameOrAddress() string {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("nameOrAddress"))
	return foundation.NSStringFromID(rv).String()
}

// Get the major service class of the device.
//
// # Discussion
//
// This value is only meaningful if the target device has been seen during an
// inquiry. This can be by checking the result of -getLastInquiryUpdate. If
// nil is returned, then the device hasn’t been seen.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/serviceClassMajor
func (b IOBluetoothDevice) ServiceClassMajor() BluetoothServiceClassMajor {
	rv := objc.Send[BluetoothServiceClassMajor](b.ID, objc.Sel("serviceClassMajor"))
	return BluetoothServiceClassMajor(rv)
}

// Gets an array of service records for the device.
//
// # Return Value
//
// Returns an array of service records for the device if an SDP query has been
// performed. If no SDP query has been performed, nil is returned.
//
// # Discussion
//
// The resulting array contains IOBluetoothSDPServiceRecord objects. The
// service records are only present if an SDP query has been done on the
// target object. This can be determined by calling -getLastServicesUpdate. It
// will return the last date/time of the SDP query. To initiate an SDP query
// on a device, use -performSDPQuery: as defined above.
//
// Instead of allowing individual clients to query for different services and
// service attributes, the system request all of the device’s services and
// service attributes.
//
// See: https://developer.apple.com/documentation/IOBluetooth/IOBluetoothDevice/services
func (b IOBluetoothDevice) Services() foundation.INSArray {
	rv := objc.Send[objc.ID](b.ID, objc.Sel("services"))
	return foundation.NSArrayFromID(objc.ID(rv))
}
