// Code generated from Apple documentation for OSLog. DO NOT EDIT.

// Package oslog provides Go bindings for the OSLog framework.
//
// A unified logging system for the reading of historical data.
//
// The OSLog framework allows you to read logs. With the unified logging
// system, you can build custom debugging and analysis tools to be used
// alongside Apple tools like Instruments and Console. To learn more about how
// to create logs, see [Logging].
//
// # Read Log Entries
//
//   - [OSLogStore]: A set of entries from the unified logging system.
//   - [OSLogEnumerator]: An enumerator that can access and list log entries.
//
// # Log Entries
//
//   - [OSLogEntry]: A single entry from the unified logging system.
//   - [OSLogEntryActivity]: An entry generated by an activity event.
//   - [OSLogEntryBoundary]: The metadata that partitions sequences of other entries.
//   - [OSLogEntryLog]: A log entry.
//   - [OSLogEntrySignpost]: An entry containing a signpost.
//   - [OSLogEntryFromProcess]: A protocol that defines subclasses containing metadata about a process.
//   - [OSLogEntryWithPayload]: A protocol defining subclasses that represent entries made using a handle and a format string.
//
// # Entry Data
//
//   - [OSLogMessageComponent]: The message arguments for a particular entry.
//   - [OSLogPosition]: A representation of a point in a sequence of entries in the unified logging system.
//
// # Key Types
//
//   - [OSLogEntrySignpost] - An entry containing a signpost.
//   - [OSLogEntryLog] - A log entry.
//   - [OSLogEntryActivity] - An entry generated by an activity event.
//   - [OSLogMessageComponent] - The message arguments for a particular entry.
//   - [OSLogStore] - A set of entries from the unified logging system.
//   - [OSLogEntry] - A single entry from the unified logging system.
//   - [OSLogEntryBoundary] - The metadata that partitions sequences of other entries.
//   - [OSLogEnumerator] - An enumerator that can access and list log entries.
//   - [OSLogPosition] - A representation of a point in a sequence of entries in the unified logging system.
package oslog

import (
	"fmt"
	"os"

	"github.com/ebitengine/purego"
)

// frameworkPaths lists paths to try when loading the OSLog library.
// The framework bundle path is tried first; a /usr/lib dylib fallback covers
// C-API frameworks that are not in the dyld shared cache as bundles.
var frameworkPaths = []string{
	"/System/Library/Frameworks/OSLog.framework/OSLog",
	"/usr/lib/libOSLog.dylib",
}

// frameworkHandle is the handle to the loaded framework.
var frameworkHandle uintptr

func init() {
	for _, path := range frameworkPaths {
		h, err := purego.Dlopen(path, purego.RTLD_LAZY|purego.RTLD_GLOBAL)
		if err == nil {
			frameworkHandle = h
			return
		}
	}
	// Loading is best-effort: the warning is silent by default because a missing
	// framework is harmless unless one of its symbols is actually called. Set
	// APPLE_FRAMEWORK_LOAD_DEBUG to surface load failures while diagnosing.
	if os.Getenv("APPLE_FRAMEWORK_LOAD_DEBUG") != "" {
		fmt.Fprintf(os.Stderr, "warning: OSLog: failed to load framework from any known path\n")
	}
}
