// Code generated from Apple documentation for OSLog. DO NOT EDIT.

package oslog

import (
	"sync"

	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objc"
)

// The class instance for the [OSLogEntryLog] class.
var (
	_OSLogEntryLogClass     OSLogEntryLogClass
	_OSLogEntryLogClassOnce sync.Once
)

func getOSLogEntryLogClass() OSLogEntryLogClass {
	_OSLogEntryLogClassOnce.Do(func() {
		_OSLogEntryLogClass = OSLogEntryLogClass{class: objc.GetClass("OSLogEntryLog")}
	})
	return _OSLogEntryLogClass
}

// GetOSLogEntryLogClass returns the class object for OSLogEntryLog.
func GetOSLogEntryLogClass() OSLogEntryLogClass {
	return getOSLogEntryLogClass()
}

type OSLogEntryLogClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (oc OSLogEntryLogClass) Class() objc.Class {
	return oc.class
}

// Alloc allocates memory for a new instance of the class.
func (oc OSLogEntryLogClass) Alloc() OSLogEntryLog {
	rv := objc.Send[OSLogEntryLog](objc.ID(oc.class), objc.Sel("alloc"))
	return rv
}

// A log entry.
//
// # Overview
//
// These log entries are generated by the os_log API. To learn more about how
// to generate a log entry, see [os_log(_:dso:log:_:_:)] and
// [os_log(_:dso:log:type:_:)].
//
// # Accessing Log Levels
//
//   - [OSLogEntryLog.Level]: The log level of the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryLog
//
// [os_log(_:dso:log:_:_:)]: https://developer.apple.com/documentation/os/os_log(_:dso:log:_:_:)
// [os_log(_:dso:log:type:_:)]: https://developer.apple.com/documentation/os/os_log(_:dso:log:type:_:)
type OSLogEntryLog struct {
	OSLogEntry
}

// OSLogEntryLogFromID constructs a [OSLogEntryLog] from an objc.ID.
//
// A log entry.
func OSLogEntryLogFromID(id objc.ID) OSLogEntryLog {
	return OSLogEntryLog{OSLogEntry: OSLogEntryFromID(id)}
}

// NOTE: OSLogEntryLog adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [OSLogEntryLog] class.
//
// # Accessing Log Levels
//
//   - [IOSLogEntryLog.Level]: The log level of the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryLog
type IOSLogEntryLog interface {
	IOSLogEntry

	// Topic: Accessing Log Levels

	// The log level of the entry.
	Level() OSLogEntryLogLevel
}

// Init initializes the instance.
func (o OSLogEntryLog) Init() OSLogEntryLog {
	rv := objc.Send[OSLogEntryLog](o.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (o OSLogEntryLog) Autorelease() OSLogEntryLog {
	rv := objc.Send[OSLogEntryLog](o.ID, objc.Sel("autorelease"))
	return rv
}

// NewOSLogEntryLog creates a new OSLogEntryLog instance.
func NewOSLogEntryLog() OSLogEntryLog {
	class := getOSLogEntryLogClass()
	rv := objc.Send[OSLogEntryLog](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// The activity identifier associated with the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/activityIdentifier
func (o OSLogEntryLog) ActivityIdentifier() uint64 {
	rv := objc.Send[uint64](o.ID, objc.Sel("activityIdentifier"))
	return rv
}

// The payload’s category.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryWithPayload/category
func (o OSLogEntryLog) Category() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("category"))
	return foundation.NSStringFromID(rv).String()
}

// The payload’s components.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryWithPayload/components
func (o OSLogEntryLog) Components() []OSLogMessageComponent {
	rv := objc.Send[[]objc.ID](o.ID, objc.Sel("components"))
	return objc.ConvertSlice(rv, func(id objc.ID) OSLogMessageComponent {
		return OSLogMessageComponentFromID(id)
	})
}

// The payload’s format string.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryWithPayload/formatString
func (o OSLogEntryLog) FormatString() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("formatString"))
	return foundation.NSStringFromID(rv).String()
}

// The name of the process that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/process
func (o OSLogEntryLog) Process() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("process"))
	return foundation.NSStringFromID(rv).String()
}

// The process identifier that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/processIdentifier
func (o OSLogEntryLog) ProcessIdentifier() int32 {
	rv := objc.Send[int32](o.ID, objc.Sel("processIdentifier"))
	return rv
}

// The name of the binary image that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/sender
func (o OSLogEntryLog) Sender() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("sender"))
	return foundation.NSStringFromID(rv).String()
}

// The payload’s subsystem.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryWithPayload/subsystem
func (o OSLogEntryLog) Subsystem() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("subsystem"))
	return foundation.NSStringFromID(rv).String()
}

// The identifier of the thread that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier
func (o OSLogEntryLog) ThreadIdentifier() uint64 {
	rv := objc.Send[uint64](o.ID, objc.Sel("threadIdentifier"))
	return rv
}

// The log level of the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryLog/level-swift.property
func (o OSLogEntryLog) Level() OSLogEntryLogLevel {
	rv := objc.Send[OSLogEntryLogLevel](o.ID, objc.Sel("level"))
	return OSLogEntryLogLevel(rv)
}

// Protocol methods for OSLogEntryFromProcess

// Protocol methods for OSLogEntryWithPayload
