// Code generated from Apple documentation for OSLog. DO NOT EDIT.

package oslog

import (
	"sync"

	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objc"
)

// The class instance for the [OSLogEntryActivity] class.
var (
	_OSLogEntryActivityClass     OSLogEntryActivityClass
	_OSLogEntryActivityClassOnce sync.Once
)

func getOSLogEntryActivityClass() OSLogEntryActivityClass {
	_OSLogEntryActivityClassOnce.Do(func() {
		_OSLogEntryActivityClass = OSLogEntryActivityClass{class: objc.GetClass("OSLogEntryActivity")}
	})
	return _OSLogEntryActivityClass
}

// GetOSLogEntryActivityClass returns the class object for OSLogEntryActivity.
func GetOSLogEntryActivityClass() OSLogEntryActivityClass {
	return getOSLogEntryActivityClass()
}

type OSLogEntryActivityClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (oc OSLogEntryActivityClass) Class() objc.Class {
	return oc.class
}

// Alloc allocates memory for a new instance of the class.
func (oc OSLogEntryActivityClass) Alloc() OSLogEntryActivity {
	rv := objc.Send[OSLogEntryActivity](objc.ID(oc.class), objc.Sel("alloc"))
	return rv
}

// An entry generated by an activity event.
//
// # Identifying the Parent
//
//   - [OSLogEntryActivity.ParentActivityIdentifier]: The identifier of the parent activity.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryActivity
type OSLogEntryActivity struct {
	OSLogEntry
}

// OSLogEntryActivityFromID constructs a [OSLogEntryActivity] from an objc.ID.
//
// An entry generated by an activity event.
func OSLogEntryActivityFromID(id objc.ID) OSLogEntryActivity {
	return OSLogEntryActivity{OSLogEntry: OSLogEntryFromID(id)}
}

// NOTE: OSLogEntryActivity adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [OSLogEntryActivity] class.
//
// # Identifying the Parent
//
//   - [IOSLogEntryActivity.ParentActivityIdentifier]: The identifier of the parent activity.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryActivity
type IOSLogEntryActivity interface {
	IOSLogEntry

	// Topic: Identifying the Parent

	// The identifier of the parent activity.
	ParentActivityIdentifier() uint64
}

// Init initializes the instance.
func (o OSLogEntryActivity) Init() OSLogEntryActivity {
	rv := objc.Send[OSLogEntryActivity](o.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (o OSLogEntryActivity) Autorelease() OSLogEntryActivity {
	rv := objc.Send[OSLogEntryActivity](o.ID, objc.Sel("autorelease"))
	return rv
}

// NewOSLogEntryActivity creates a new OSLogEntryActivity instance.
func NewOSLogEntryActivity() OSLogEntryActivity {
	class := getOSLogEntryActivityClass()
	rv := objc.Send[OSLogEntryActivity](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// The activity identifier associated with the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/activityIdentifier
func (o OSLogEntryActivity) ActivityIdentifier() uint64 {
	rv := objc.Send[uint64](o.ID, objc.Sel("activityIdentifier"))
	return rv
}

// The name of the process that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/process
func (o OSLogEntryActivity) Process() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("process"))
	return foundation.NSStringFromID(rv).String()
}

// The process identifier that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/processIdentifier
func (o OSLogEntryActivity) ProcessIdentifier() int32 {
	rv := objc.Send[int32](o.ID, objc.Sel("processIdentifier"))
	return rv
}

// The name of the binary image that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/sender
func (o OSLogEntryActivity) Sender() string {
	rv := objc.Send[objc.ID](o.ID, objc.Sel("sender"))
	return foundation.NSStringFromID(rv).String()
}

// The identifier of the thread that made the entry.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryFromProcess/threadIdentifier
func (o OSLogEntryActivity) ThreadIdentifier() uint64 {
	rv := objc.Send[uint64](o.ID, objc.Sel("threadIdentifier"))
	return rv
}

// The identifier of the parent activity.
//
// See: https://developer.apple.com/documentation/OSLog/OSLogEntryActivity/parentActivityIdentifier
func (o OSLogEntryActivity) ParentActivityIdentifier() uint64 {
	rv := objc.Send[uint64](o.ID, objc.Sel("parentActivityIdentifier"))
	return rv
}

// Protocol methods for OSLogEntryFromProcess
