// Code generated from Apple documentation for AudioToolbox. DO NOT EDIT.

package audiotoolbox

import (
	"sync"

	"github.com/tmc/apple/foundation"
	"github.com/tmc/apple/objc"
	"github.com/tmc/apple/objectivec"
)

// The class instance for the [AUParameterNode] class.
var (
	_AUParameterNodeClass     AUParameterNodeClass
	_AUParameterNodeClassOnce sync.Once
)

func getAUParameterNodeClass() AUParameterNodeClass {
	_AUParameterNodeClassOnce.Do(func() {
		_AUParameterNodeClass = AUParameterNodeClass{class: objc.GetClass("AUParameterNode")}
	})
	return _AUParameterNodeClass
}

// GetAUParameterNodeClass returns the class object for AUParameterNode.
func GetAUParameterNodeClass() AUParameterNodeClass {
	return getAUParameterNodeClass()
}

type AUParameterNodeClass struct {
	class objc.Class
}

// Class returns the underlying Objective-C class pointer.
func (ac AUParameterNodeClass) Class() objc.Class {
	return ac.class
}

// Alloc allocates memory for a new instance of the class.
func (ac AUParameterNodeClass) Alloc() AUParameterNode {
	rv := objc.Send[AUParameterNode](objc.ID(ac.class), objc.Sel("alloc"))
	return rv
}

// An object that represents a node in an audio unit’s parameter tree.
//
// # Overview
//
// Nodes are instances of either an [AUParameter] or [AUParameterGroup] class.
//
// # Identifiers
//
//   - [AUParameterNode.Identifier]: A non-localized, permanent name for the parameter node.
//   - [AUParameterNode.KeyPath]: A key path generated by concatenating the identifiers of the parameter and its parents.
//   - [AUParameterNode.DisplayName]: A localized display name for the parameter node.
//   - [AUParameterNode.DisplayNameWithLength]: Another version of the display name, possibly truncated to a desired length.
//
// # Observers
//
//   - [AUParameterNode.TokenByAddingParameterObserver]: Adds an observer for a single parameter or all parameters in a group.
//   - [AUParameterNode.TokenByAddingParameterRecordingObserver]: Adds a recording observer for a single parameter or all parameters in a group.
//   - [AUParameterNode.TokenByAddingParameterAutomationObserver]
//   - [AUParameterNode.RemoveParameterObserver]: Remove a specific parameter observer.
//
// # Audio Unit Implementations
//
//   - [AUParameterNode.ImplementorValueObserver]: The callback for parameter value changes.
//   - [AUParameterNode.SetImplementorValueObserver]
//   - [AUParameterNode.ImplementorValueProvider]: The callback for refreshing known stale values in a parameter tree.
//   - [AUParameterNode.SetImplementorValueProvider]
//   - [AUParameterNode.ImplementorStringFromValueCallback]: The callback for providing a string representation of a parameter value.
//   - [AUParameterNode.SetImplementorStringFromValueCallback]
//   - [AUParameterNode.ImplementorValueFromStringCallback]: The callback for converting a string to a parameter value.
//   - [AUParameterNode.SetImplementorValueFromStringCallback]
//   - [AUParameterNode.ImplementorDisplayNameWithLengthCallback]: The callback for obtaining an abbreviated version of a parameter node display name.
//   - [AUParameterNode.SetImplementorDisplayNameWithLengthCallback]
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode
type AUParameterNode struct {
	objectivec.Object
}

// AUParameterNodeFromID constructs a [AUParameterNode] from an objc.ID.
//
// An object that represents a node in an audio unit’s parameter tree.
func AUParameterNodeFromID(id objc.ID) AUParameterNode {
	return AUParameterNode{objectivec.Object{ID: id}}
}

// NOTE: AUParameterNode adopts protocols; skip strict compile-time interface assertion.
// Protocol method surfaces are generated separately and may include optional methods.

// An interface definition for the [AUParameterNode] class.
//
// # Identifiers
//
//   - [IAUParameterNode.Identifier]: A non-localized, permanent name for the parameter node.
//   - [IAUParameterNode.KeyPath]: A key path generated by concatenating the identifiers of the parameter and its parents.
//   - [IAUParameterNode.DisplayName]: A localized display name for the parameter node.
//   - [IAUParameterNode.DisplayNameWithLength]: Another version of the display name, possibly truncated to a desired length.
//
// # Observers
//
//   - [IAUParameterNode.TokenByAddingParameterObserver]: Adds an observer for a single parameter or all parameters in a group.
//   - [IAUParameterNode.TokenByAddingParameterRecordingObserver]: Adds a recording observer for a single parameter or all parameters in a group.
//   - [IAUParameterNode.TokenByAddingParameterAutomationObserver]
//   - [IAUParameterNode.RemoveParameterObserver]: Remove a specific parameter observer.
//
// # Audio Unit Implementations
//
//   - [IAUParameterNode.ImplementorValueObserver]: The callback for parameter value changes.
//   - [IAUParameterNode.SetImplementorValueObserver]
//   - [IAUParameterNode.ImplementorValueProvider]: The callback for refreshing known stale values in a parameter tree.
//   - [IAUParameterNode.SetImplementorValueProvider]
//   - [IAUParameterNode.ImplementorStringFromValueCallback]: The callback for providing a string representation of a parameter value.
//   - [IAUParameterNode.SetImplementorStringFromValueCallback]
//   - [IAUParameterNode.ImplementorValueFromStringCallback]: The callback for converting a string to a parameter value.
//   - [IAUParameterNode.SetImplementorValueFromStringCallback]
//   - [IAUParameterNode.ImplementorDisplayNameWithLengthCallback]: The callback for obtaining an abbreviated version of a parameter node display name.
//   - [IAUParameterNode.SetImplementorDisplayNameWithLengthCallback]
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode
type IAUParameterNode interface {
	objectivec.IObject

	// Topic: Identifiers

	// A non-localized, permanent name for the parameter node.
	Identifier() string
	// A key path generated by concatenating the identifiers of the parameter and its parents.
	KeyPath() string
	// A localized display name for the parameter node.
	DisplayName() string
	// Another version of the display name, possibly truncated to a desired length.
	DisplayNameWithLength(maximumLength int) string

	// Topic: Observers

	// Adds an observer for a single parameter or all parameters in a group.
	TokenByAddingParameterObserver(observer Uint64Float32Handler) AUParameterObserverToken
	// Adds a recording observer for a single parameter or all parameters in a group.
	TokenByAddingParameterRecordingObserver(observer Int64AURecordedParameterEventHandler) AUParameterObserverToken
	TokenByAddingParameterAutomationObserver(observer Int64AUParameterAutomationEventHandler) AUParameterObserverToken
	// Remove a specific parameter observer.
	RemoveParameterObserver(token AUParameterObserverToken)

	// Topic: Audio Unit Implementations

	// The callback for parameter value changes.
	ImplementorValueObserver() AUParameterFloat32Handler
	SetImplementorValueObserver(value AUParameterFloat32Handler)
	// The callback for refreshing known stale values in a parameter tree.
	ImplementorValueProvider() Float32AUParameterHandler
	SetImplementorValueProvider(value Float32AUParameterHandler)
	// The callback for providing a string representation of a parameter value.
	ImplementorStringFromValueCallback() StringVoidHandler
	SetImplementorStringFromValueCallback(value StringVoidHandler)
	// The callback for converting a string to a parameter value.
	ImplementorValueFromStringCallback() Float32AUParameterStringHandler
	SetImplementorValueFromStringCallback(value Float32AUParameterStringHandler)
	// The callback for obtaining an abbreviated version of a parameter node display name.
	ImplementorDisplayNameWithLengthCallback() StringAUParameterNodeInt64Handler
	SetImplementorDisplayNameWithLengthCallback(value StringAUParameterNodeInt64Handler)
}

// Init initializes the instance.
func (p AUParameterNode) Init() AUParameterNode {
	rv := objc.Send[AUParameterNode](p.ID, objc.Sel("init"))
	return rv
}

// Autorelease adds the receiver to the current autorelease pool.
func (p AUParameterNode) Autorelease() AUParameterNode {
	rv := objc.Send[AUParameterNode](p.ID, objc.Sel("autorelease"))
	return rv
}

// NewAUParameterNode creates a new AUParameterNode instance.
func NewAUParameterNode() AUParameterNode {
	class := getAUParameterNodeClass()
	rv := objc.Send[AUParameterNode](objc.ID(class.class), objc.Sel("new"))
	return rv
}

// Another version of the display name, possibly truncated to a desired
// length.
//
// maximumLength: The maximum length, in characters, of the display name.
//
// # Return Value
//
// A truncated display name.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/displayName(withLength:)
func (p AUParameterNode) DisplayNameWithLength(maximumLength int) string {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("displayNameWithLength:"), maximumLength)
	return foundation.NSStringFromID(rv).String()
}

// Adds an observer for a single parameter or all parameters in a group.
//
// observer: A block called after the value of a parameter has changed.
//
// # Return Value
//
// A token which can be passed to the
// [AUParameterNode.RemoveParameterObserver] or
// [AUParameter.SetValueOriginator] methods.
//
// # Discussion
//
// An audio unit view can use an observer to be notified of changes to a
// single parameter or all parameters in a group. These callbacks are
// throttled so as to limit the rate of redundant notifications in the case of
// frequent changes to a single parameter.
//
// This block is called in an arbitrary thread context and it is responsible
// for thread-safety. It must not make any calls to add or remove other
// observers, including itself, as this will deadlock.
//
// An audio unit should interact with the parameter node via the
// [AUParameterNode.ImplementorValueObserver] and
// [AUParameterNode.ImplementorValueProvider] properties.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterObserver:)
func (p AUParameterNode) TokenByAddingParameterObserver(observer Uint64Float32Handler) AUParameterObserverToken {
	_block0, _ := NewUint64Float32Block(observer)
	rv := objc.Send[AUParameterObserverToken](p.ID, objc.Sel("tokenByAddingParameterObserver:"), _block0)
	return AUParameterObserverToken(rv)
}

// Adds a recording observer for a single parameter or all parameters in a
// group.
//
// observer: A block called to record parameter changes.
//
// # Return Value
//
// A token which can be passed to the
// [AUParameterNode.RemoveParameterObserver] or
// [AUParameter.SetValueOriginator] methods.
//
// # Discussion
//
// A host can use a recording observer to capture a series of changes to a
// parameter value as generated by a UI gesture. Unlike a non-recording
// observer, these callbacks are not throttled.
//
// This block is called in an arbitrary thread context and it is responsible
// for thread-safety. It must not make any calls to add or remove other
// observers, including itself, as this will deadlock.
//
// An audio unit should interact with the parameter node via the
// [AUParameterNode.ImplementorValueObserver] and
// [AUParameterNode.ImplementorValueProvider] properties.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterRecordingObserver:)
func (p AUParameterNode) TokenByAddingParameterRecordingObserver(observer Int64AURecordedParameterEventHandler) AUParameterObserverToken {
	_block0, _ := NewInt64AURecordedParameterEventBlock(observer)
	rv := objc.Send[AUParameterObserverToken](p.ID, objc.Sel("tokenByAddingParameterRecordingObserver:"), _block0)
	return AUParameterObserverToken(rv)
}

// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/token(byAddingParameterAutomationObserver:)
func (p AUParameterNode) TokenByAddingParameterAutomationObserver(observer Int64AUParameterAutomationEventHandler) AUParameterObserverToken {
	_block0, _ := NewInt64AUParameterAutomationEventBlock(observer)
	rv := objc.Send[AUParameterObserverToken](p.ID, objc.Sel("tokenByAddingParameterAutomationObserver:"), _block0)
	return AUParameterObserverToken(rv)
}

// Remove a specific parameter observer.
//
// token: The token corresponding to the given observer.
//
// # Discussion
//
// This call will remove the callback corresponding to the given token. This
// operation blocks until any callbacks currently in progress have completed.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/removeParameterObserver(_:)
func (p AUParameterNode) RemoveParameterObserver(token AUParameterObserverToken) {
	objc.Send[objc.ID](p.ID, objc.Sel("removeParameterObserver:"), token)
}

// A non-localized, permanent name for the parameter node.
//
// # Discussion
//
// All child nodes, under any given parent, must have a unique identifier.
// From release to release, an audio unit must not change its parameters’
// identifiers; this will invalidate any hosts’ documents that refer to the
// parameters.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/identifier
func (p AUParameterNode) Identifier() string {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("identifier"))
	return foundation.NSStringFromID(rv).String()
}

// A key path generated by concatenating the identifiers of the parameter and
// its parents.
//
// # Discussion
//
// When recording parameter values, hosts should bind to the parameter key
// path (unless an audio unit specifically documents that its parameter
// addresses are stable and persistent). The individual node identifiers in a
// key path are separated by periods (`.`). Passing a node’s key path to a
// parameter tree’s [value(forKeyPath:)] method returns the same node.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/keyPath
//
// [value(forKeyPath:)]: https://developer.apple.com/documentation/ObjectiveC/NSObject-swift.class/value(forKeyPath:)
func (p AUParameterNode) KeyPath() string {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("keyPath"))
	return foundation.NSStringFromID(rv).String()
}

// A localized display name for the parameter node.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/displayName
func (p AUParameterNode) DisplayName() string {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("displayName"))
	return foundation.NSStringFromID(rv).String()
}

// The callback for parameter value changes.
//
// # Discussion
//
// This block receives all externally-generated changes to parameter values.
// It should store the new value in its audio signal processing state
// (assuming that state is separate from the parameter object).
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/implementorValueObserver
func (p AUParameterNode) ImplementorValueObserver() AUParameterFloat32Handler {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("implementorValueObserver"))
	_ = rv
	return nil
}
func (p AUParameterNode) SetImplementorValueObserver(value AUParameterFloat32Handler) {
	block, cleanup := NewAUParameterFloat32Block(value)
	defer cleanup()
	objc.Send[struct{}](p.ID, objc.Sel("setImplementorValueObserver:"), block)
}

// The callback for refreshing known stale values in a parameter tree.
//
// # Discussion
//
// The audio unit should return the current value for this parameter; the
// parameter node object then stores this value.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/implementorValueProvider
func (p AUParameterNode) ImplementorValueProvider() Float32AUParameterHandler {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("implementorValueProvider"))
	_ = rv
	return nil
}
func (p AUParameterNode) SetImplementorValueProvider(value Float32AUParameterHandler) {
	block, cleanup := NewFloat32AUParameterBlock(value)
	defer cleanup()
	objc.Send[struct{}](p.ID, objc.Sel("setImplementorValueProvider:"), block)
}

// The callback for providing a string representation of a parameter value.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/implementorStringFromValueCallback
func (p AUParameterNode) ImplementorStringFromValueCallback() StringVoidHandler {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("implementorStringFromValueCallback"))
	_ = rv
	return nil
}
func (p AUParameterNode) SetImplementorStringFromValueCallback(value StringVoidHandler) {
	block, cleanup := NewStringVoidBlock(value)
	defer cleanup()
	objc.Send[struct{}](p.ID, objc.Sel("setImplementorStringFromValueCallback:"), block)
}

// The callback for converting a string to a parameter value.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/implementorValueFromStringCallback
func (p AUParameterNode) ImplementorValueFromStringCallback() Float32AUParameterStringHandler {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("implementorValueFromStringCallback"))
	_ = rv
	return nil
}
func (p AUParameterNode) SetImplementorValueFromStringCallback(value Float32AUParameterStringHandler) {
	block, cleanup := NewFloat32AUParameterStringBlock(value)
	defer cleanup()
	objc.Send[struct{}](p.ID, objc.Sel("setImplementorValueFromStringCallback:"), block)
}

// The callback for obtaining an abbreviated version of a parameter node
// display name.
//
// See: https://developer.apple.com/documentation/AudioToolbox/AUParameterNode/implementorDisplayNameWithLengthCallback
func (p AUParameterNode) ImplementorDisplayNameWithLengthCallback() StringAUParameterNodeInt64Handler {
	rv := objc.Send[objc.ID](p.ID, objc.Sel("implementorDisplayNameWithLengthCallback"))
	_ = rv
	return nil
}
func (p AUParameterNode) SetImplementorDisplayNameWithLengthCallback(value StringAUParameterNodeInt64Handler) {
	block, cleanup := NewStringAUParameterNodeInt64Block(value)
	defer cleanup()
	objc.Send[struct{}](p.ID, objc.Sel("setImplementorDisplayNameWithLengthCallback:"), block)
}
