// Command e5rtstack runs a stack of transformer blocks on the Neural Engine
// through the private e5rt direct-dispatch route, in one dispatch, and checks
// what comes back against a float64 CPU reference of the whole stack.
//
// e5rtblock runs one block and closes its second residual on the host. That is
// fine for one block and wrong for a stack: a host round trip between every
// layer is most of the cost of a small model, and it makes the example say
// nothing about whether a deep graph can be encoded at all. This program keeps
// everything on the engine. The host writes the input once, calls execute once,
// and reads the output once, whatever the depth.
//
// # Closing the residual on the device
//
// Each layer is three programs. GenSDPAForward ends in add(x, projection), so
// it carries the first residual itself. GenFFNForwardRMSReLU2 carries neither,
// so the second residual is a third program here: a two-input elementwise add,
// generated by genAdd below, whose output buffer is the next layer's input
// buffer. Nothing is copied between layers and the host never sees an
// intermediate activation.
//
// That makes 3N programs, all encoded into an execution stream in order. Order
// is what the stream runs them in; it does not reorder operations to satisfy a
// dependency, so encoding a layer's residual add before the feed forward it
// reads yields a stale result rather than an error.
//
// # Fifteen operations, and how to go deeper
//
// A process can hold fifteen precompiled compute operations at once. The
// sixteenth fails with status 13. That limit is not the weight file ceiling —
// it counts operations, not weights, and a trivial weightless program hits it
// just the same — and it caps this design at five layers, since each layer is
// three operations.
//
// Releasing an operation frees its slot, but releasing one that has already
// been encoded does not, because the stream holds it. Releasing the stream
// frees them all. So a stack deeper than five layers runs in phases: encode
// what fits, execute, release the stream, encode the next group. Every buffer
// is allocated once and stays bound across the boundary, so the phases hand
// activations to each other in place — what a phase boundary costs is the
// encode, not a copy or a host round trip. Sixteen layers run this way here.
//
// The pool is shared between processes rather than reserved per process. Two
// copies of this program running at once reproducibly get fifteen operations
// and seven, so a process cannot assume all fifteen will be available.
//
// # The weight file ceiling is per compile
//
// One attention program needs six weight files and one feed forward program
// needs three. Nine per layer, and the compiler stops accepting weight files at
// sixteen — so a stack that put every layer's weights in one directory would
// fail to compile at two layers. It compiles here because each program is
// compiled separately from its own directory, which is what makes the ceiling a
// per-compile limit rather than a limit on model size. Packing many tensors
// into one file is the other way around it; see x/ane/mil's BlobWriter.
//
// # What is checked
//
// The reference recomputes every layer in float64 from the same weights. Depth
// is the thing this program adds over e5rtblock, so it also checks that the
// depth is real: each layer's attention scores must have enough spread that the
// softmax selects rather than averages, and the N-layer result must differ from
// the (N-1)-layer result by more than the tolerance. Without that second check
// a stack whose later layers contributed nothing would pass exactly as well as
// one that worked.
//
// Residual growth is reported per layer. Every value on the engine is fp16, and
// a residual stream that grows geometrically with depth runs out of range; the
// program prints the peak magnitude after each layer so a stack approaching
// that limit is visible rather than silently wrong.
//
//	go run ./examples/ane/e5rtstack
//	go run ./examples/ane/e5rtstack -layers 6 -dim 128 -heads 8 -seq 32 -hidden 256
package main

import (
	"flag"
	"fmt"
	"log"
	"math"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/tmc/apple/x/ane"
	"github.com/tmc/apple/x/ane/e5rt"
	"github.com/tmc/apple/x/ane/mil"
)

func main() {
	log.SetFlags(0)
	layers := flag.Int("layers", 4, "number of transformer blocks")
	dim := flag.Int("dim", 64, "model width")
	heads := flag.Int("heads", 4, "attention heads")
	seq := flag.Int("seq", 16, "sequence length")
	hidden := flag.Int("hidden", 128, "feed forward width")
	flag.Parse()

	if *dim%*heads != 0 {
		log.Fatalf("dim %d is not a multiple of heads %d", *dim, *heads)
	}
	if *layers < 2 {
		log.Fatalf("layers %d: a stack of fewer than two blocks is what e5rtblock already runs", *layers)
	}
	if err := run(*layers, *dim, *heads, *seq, *hidden); err != nil {
		log.Fatal(err)
	}
}

// blockWeights are the parameters of one transformer block.
type blockWeights struct {
	rms1 []float32 // [dim]
	wq   []float32 // [dim][dim] OIHW
	wk   []float32
	wv   []float32
	wo   []float32
	rms2 []float32 // [dim]
	w1   []float32 // [hidden][dim]
	w2   []float32 // [dim][hidden]
}

// randomWeights returns n deterministic pseudo-random values in [-spread,
// spread), from a xorshift generator seeded by seed.
//
// Decorrelated values are the point. Correlated weights cancel under a dot
// product over hundreds of terms instead of accumulating like a random walk,
// and attention whose scores are all equal is an average over positions, which
// a wrong head split and a missing causal mask both reproduce exactly. See the
// e5rtblock example, where a smooth sinusoidal fill made the whole comparison
// vacuous.
func randomWeights(n int, spread float64, seed uint64) []float32 {
	state := seed*2862933555777941757 + 3037000493
	next := func() float64 {
		state ^= state << 13
		state ^= state >> 7
		state ^= state << 17
		// The top 53 bits, mapped to [-1, 1).
		return float64(state>>11)/(1<<52) - 1
	}
	out := make([]float32, n)
	for i := range out {
		out[i] = float32(next() * spread)
	}
	return out
}

// newBlockWeights builds deterministic weights for one layer, distinct per
// layer, whose scales are chosen so that every stage contributes.
//
// A projection sums over its input width, so a weight of scale s produces an
// output of roughly s*sqrt(width) for a unit-scale input; the scales below
// invert that. The two output projections are damped relative to the residual
// so that the residual stream grows with depth rather than exploding: each
// layer adds a fraction of what it received, which is the regime a real model
// runs in and the one fp16 survives.
func newBlockWeights(dim, hidden int, layer int) *blockWeights {
	// Distinct seeds per layer, so no two layers compute the same function.
	// A stack of identical layers would hide an encoding order bug.
	s := func(base uint64) uint64 { return base + 1000*uint64(layer) }
	rms := func(n int, seed uint64) []float32 {
		// RMSNorm weights vary around one: a constant would hide a channel misorder.
		out := randomWeights(n, 0.2, seed)
		for i := range out {
			out[i] += 1
		}
		return out
	}
	inv := func(width int) float64 { return 1 / math.Sqrt(float64(width)) }
	return &blockWeights{
		rms1: rms(dim, s(11)),
		// The query and key scales carry a margin over the unit-magnitude
		// point. Score spread varies from layer to layer, and at depth eight
		// the thinnest layer fell just under the spread this program demands
		// before it will call a match meaningful.
		wq:   randomWeights(dim*dim, 1.25*inv(dim), s(22)),
		wk:   randomWeights(dim*dim, 1.25*inv(dim), s(33)),
		wv:   randomWeights(dim*dim, inv(dim), s(44)),
		wo:   randomWeights(dim*dim, 0.35*inv(dim), s(55)),
		rms2: rms(dim, s(66)),
		w1:   randomWeights(hidden*dim, inv(dim), s(77)),
		w2:   randomWeights(dim*hidden, 0.35*inv(hidden), s(88)),
	}
}

// layerFunctions holds the three compiled functions of one layer.
type layerFunctions struct {
	attn, ffn, add uintptr
}

// maxLiveOps is how many precompiled compute operations e5rt will let a process
// hold at once. Creating the next one fails with status 13.
//
// Measured, not documented anywhere: a trivial weightless program can be
// compiled and its function retained forty times over without complaint, but
// the sixteenth live operation is refused. This is a different limit from the
// weight file ceiling — it counts operations, and it does not care how many
// weights they carry.
//
// Releasing an operation frees its slot, but releasing one that has already
// been encoded does not: the execution stream holds it. Releasing the stream
// frees them all, which is what makes phasing work — see runner.execute.
//
// The pool is shared between processes. Two of these programs running at once
// reproducibly get fifteen and seven, so a process cannot assume fifteen will
// be there.
const maxLiveOps = 15

// opsPerLayer is how many operations one transformer block encodes: attention,
// feed forward, and the residual add.
const opsPerLayer = 3

func run(layers, dim, heads, seq, hidden int) error {
	lib, err := e5rt.Open()
	if err != nil {
		return err
	}
	fmt.Printf("resolved %d of %d listed symbols\n\n", len(lib.Resolved()), len(e5rt.Symbols))
	fmt.Printf("stack: %d layers, dim %d, heads %d, seq %d, hidden %d\n", layers, dim, heads, seq, hidden)

	w := make([]*blockWeights, layers)
	for l := range w {
		w[l] = newBlockWeights(dim, hidden, l)
	}

	input := make([]float32, dim*seq)
	for i := range input {
		input[i] = float32(0.5 * math.Sin(float64(i)*0.21))
	}
	if err := checkDiscriminating(input, w, dim, heads, seq, hidden); err != nil {
		return err
	}

	// Compile every program. Each gets its own directory, which is what keeps
	// each compile under the weight file ceiling.
	start := time.Now()
	var dirs []string
	defer func() {
		for _, dir := range dirs {
			os.RemoveAll(dir)
		}
	}()
	fns := make([]layerFunctions, layers)
	for l := range layers {
		attnDir, err := writeAttentionModel(dim, heads, seq, w[l])
		if err != nil {
			return err
		}
		ffnDir, err := writeFFNModel(dim, hidden, seq, w[l])
		if err != nil {
			return err
		}
		addDir, err := writeModel(genAdd(dim, seq), nil)
		if err != nil {
			return err
		}
		dirs = append(dirs, attnDir, ffnDir, addDir)

		if fns[l].attn, err = compileFunction(lib, attnDir); err != nil {
			return fmt.Errorf("layer %d attention: %w", l, err)
		}
		if fns[l].ffn, err = compileFunction(lib, ffnDir); err != nil {
			return fmt.Errorf("layer %d feed forward: %w", l, err)
		}
		if fns[l].add, err = compileFunction(lib, addDir); err != nil {
			return fmt.Errorf("layer %d residual add: %w", l, err)
		}
		if l == 0 {
			reportBackend(attnDir, "attention")
			reportBackend(ffnDir, "feed forward")
			reportBackend(addDir, "residual add")
		}
	}
	fmt.Printf("  compiled %d programs in %v\n", opsPerLayer*layers, time.Since(start).Round(time.Millisecond))

	// Buffers, all allocated once and never released. x[l] is layer l's input
	// and x[layers] is the stack output; x2 and f are each layer's two
	// intermediates. They outlive the operations that read them, which is what
	// lets a phased run hand data from one phase to the next without copying.
	acts := dim * seq
	r := &runner{
		lib: lib, fns: fns, layers: layers, acts: acts,
		layersPerPhase: maxLiveOps / opsPerLayer,
	}
	r.x = make([]uintptr, layers+1)
	r.xPtr = make([]uintptr, layers+1)
	for l := range r.x {
		if r.x[l], r.xPtr[l], err = allocBuffer(lib, acts*2); err != nil {
			return err
		}
	}
	r.x2 = make([]uintptr, layers)
	r.f = make([]uintptr, layers)
	for l := range layers {
		if r.x2[l], _, err = allocBuffer(lib, acts*2); err != nil {
			return err
		}
		if r.f[l], _, err = allocBuffer(lib, acts*2); err != nil {
			return err
		}
	}

	phases := (layers + r.layersPerPhase - 1) / r.layersPerPhase
	if phases == 1 {
		fmt.Printf("  %d operations fit under the limit of %d, so the whole stack is one stream and one execute\n",
			opsPerLayer*layers, maxLiveOps)
	} else {
		fmt.Printf("  %d operations exceed the limit of %d live at once, so the stack runs in %d phases of at most %d layers\n",
			opsPerLayer*layers, maxLiveOps, phases, r.layersPerPhase)
	}

	got, elapsed, err := r.dispatch(input)
	if err != nil {
		return err
	}
	fmt.Printf("  first dispatch %v for %d layers, including the encode\n",
		elapsed.Round(time.Microsecond), layers)

	want, peaks := stackReference(input, w, dim, heads, seq, hidden)
	fmt.Printf("  residual peak by layer:")
	for l, p := range peaks {
		fmt.Printf(" %d:%.2f", l+1, p)
	}
	fmt.Println()
	if err := compare("stack output", got, want); err != nil {
		return err
	}

	// Control: move one input element and require the output to follow. When
	// the stack fits in one phase this re-executes the same stream without
	// re-encoding, so it tests the bound buffers rather than a fresh setup.
	perturbed := append([]float32(nil), input...)
	perturbed[0] += 1
	got2, elapsed2, err := r.dispatch(perturbed)
	if err != nil {
		return err
	}
	if r.held != 0 {
		fmt.Printf("  second dispatch %v, re-executing the encoded stream (%v per layer)\n",
			elapsed2.Round(time.Microsecond), (elapsed2 / time.Duration(layers)).Round(time.Microsecond))
	} else {
		fmt.Printf("  second dispatch %v, re-encoding every phase (%v per layer)\n",
			elapsed2.Round(time.Microsecond), (elapsed2 / time.Duration(layers)).Round(time.Microsecond))
	}
	moved := 0
	for i := range got {
		if got[i] != got2[i] {
			moved++
		}
	}
	if moved == 0 {
		return fmt.Errorf("perturbing an input changed nothing; the engine is not reading the bound buffer")
	}
	want2, _ := stackReference(perturbed, w, dim, heads, seq, hidden)
	if err := compare("perturbed stack output", got2, want2); err != nil {
		return err
	}
	fmt.Printf("  control: perturbing one input element moved %d of %d outputs, and the new output still matches its reference\n",
		moved, len(got))
	return nil
}

// runner holds everything needed to run the stack: the compiled functions, the
// activation buffers, and any stream kept alive between calls.
type runner struct {
	lib            *e5rt.Lib
	fns            []layerFunctions
	layers         int
	acts           int
	layersPerPhase int

	x    []uintptr // layers+1 activation buffers, x[0] in and x[layers] out
	xPtr []uintptr // their host addresses
	x2   []uintptr // per layer, the attention output
	f    []uintptr // per layer, the feed forward output

	// held is the stream from a single-phase stack, kept encoded so that a
	// second call re-executes rather than rebuilds. A stack that needs more
	// than one phase cannot do this: the phase boundary releases the stream,
	// and that release is the only thing that frees the operation slots.
	held uintptr
}

// dispatch writes the stack input, runs every layer, and reads the stack
// output. The host touches nothing in between, whatever the depth.
func (r *runner) dispatch(input []float32) ([]float32, time.Duration, error) {
	writeFP16(r.xPtr[0], input)
	start := time.Now()
	if err := r.execute(); err != nil {
		return nil, 0, err
	}
	elapsed := time.Since(start)
	return readFP16(r.xPtr[r.layers], r.acts), elapsed, nil
}

// execute runs the stack, in as many phases as the operation limit requires.
//
// The phase boundary is a stream release, not a data movement: every buffer is
// allocated once and stays bound across the boundary, so the next phase reads
// exactly what the previous one left in place. What the boundary costs is the
// encode, which has to be redone because releasing the stream is what frees the
// operations to be created again.
func (r *runner) execute() error {
	if r.held != 0 {
		return r.lib.ExecuteSync(r.held)
	}
	for lo := 0; lo < r.layers; lo += r.layersPerPhase {
		hi := min(lo+r.layersPerPhase, r.layers)
		stream, ops, err := r.encodePhase(lo, hi)
		if err != nil {
			return err
		}
		if err := r.lib.ExecuteSync(stream); err != nil {
			return fmt.Errorf("execute layers %d-%d: %w", lo, hi-1, err)
		}
		if lo == 0 && hi == r.layers {
			// One phase covers the whole stack, so keep it encoded.
			r.held = stream
			return nil
		}
		for _, op := range ops {
			r.lib.OperationRelease(op)
		}
		r.lib.ExecutionStreamRelease(stream)
	}
	return nil
}

// encodePhase creates and wires the operations for layers [lo, hi) and encodes
// them into a fresh stream, in order.
//
// Order is not a detail. The stream runs operations in the order they were
// encoded and does not reorder them to satisfy a dependency: encoding a layer's
// residual add before the feed forward it reads produces a stale result rather
// than an error.
func (r *runner) encodePhase(lo, hi int) (uintptr, []uintptr, error) {
	stream, err := r.lib.ExecutionStreamCreate()
	if err != nil {
		return 0, nil, err
	}
	var ops []uintptr
	for l := lo; l < hi; l++ {
		attn, err := newOperation(r.lib, r.fns[l].attn)
		if err != nil {
			return 0, nil, fmt.Errorf("layer %d attention operation: %w", l, err)
		}
		ffn, err := newOperation(r.lib, r.fns[l].ffn)
		if err != nil {
			return 0, nil, fmt.Errorf("layer %d feed forward operation: %w", l, err)
		}
		add, err := newOperation(r.lib, r.fns[l].add)
		if err != nil {
			return 0, nil, fmt.Errorf("layer %d residual operation: %w", l, err)
		}
		ops = append(ops, attn, ffn, add)

		// attention: x[l] -> x2[l], carrying the first residual itself.
		// feed forward: x2[l] -> f[l], reading the same buffer object, no copy.
		// residual: x2[l] + f[l] -> x[l+1], the next layer's input.
		binds := []struct {
			op    uintptr
			port  string
			buf   uintptr
			input bool
		}{
			{attn, "x", r.x[l], true},
			{attn, "out", r.x2[l], false},
			{ffn, "x", r.x2[l], true},
			{ffn, "out", r.f[l], false},
			{add, "a", r.x2[l], true},
			{add, "b", r.f[l], true},
			{add, "out", r.x[l+1], false},
		}
		for _, b := range binds {
			if err := bind(r.lib, b.op, b.port, b.buf, b.input); err != nil {
				return 0, nil, fmt.Errorf("layer %d bind %s: %w", l, b.port, err)
			}
		}
		for _, op := range []uintptr{attn, ffn, add} {
			if err := r.lib.EncodeOperation(stream, op); err != nil {
				return 0, nil, fmt.Errorf("layer %d encode: %w", l, err)
			}
		}
	}
	return stream, ops, nil
}

// genAdd generates a MIL program adding two activations elementwise.
//
// This is the layer's second residual. The feed forward generator does not add
// it, and doing it on the host would put a read and a write between every pair
// of layers, so it is a program of its own whose output buffer is the next
// layer's input buffer.
func genAdd(dim, seq int) string {
	var b strings.Builder
	b.WriteString("program(1.3)\n")
	b.WriteString(`[buildInfo = dict<string, string>({{"coremlc-component-MIL", "3400.4.1"}, {"coremlc-version", "3400.6.1"}})]` + "\n")
	b.WriteString("{\n")
	fmt.Fprintf(&b, "    func main<ios18>(tensor<fp16, [1, %d, 1, %d]> a, tensor<fp16, [1, %d, 1, %d]> b) {\n",
		dim, seq, dim, seq)
	fmt.Fprintf(&b, "        tensor<fp16, [1,%d,1,%d]> out = add(x=a,y=b)[name=string(\"res\")];\n", dim, seq)
	b.WriteString("    } -> (out);\n}\n")
	return b.String()
}

// stackReference recomputes every layer in float64 and returns the stack output
// along with the peak magnitude of the residual stream after each layer.
func stackReference(x []float32, w []*blockWeights, dim, heads, seq, hidden int) ([]float64, []float64) {
	cur := make([]float64, len(x))
	for i, v := range x {
		cur[i] = float64(v)
	}
	peaks := make([]float64, len(w))
	for l := range w {
		cur = blockReference(cur, w[l], dim, heads, seq, hidden)
		for _, v := range cur {
			peaks[l] = math.Max(peaks[l], math.Abs(v))
		}
	}
	return cur, peaks
}

// blockReference recomputes one block in float64.
func blockReference(in []float64, w *blockWeights, dim, heads, seq, hidden int) []float64 {
	headDim := dim / heads

	// Attention: RMSNorm, QKV, scaled dot product with a causal mask, output
	// projection, residual.
	xn := rmsNorm(in, w.rms1, dim, seq)
	q := project(xn, w.wq, dim, dim, seq)
	k := project(xn, w.wk, dim, dim, seq)
	v := project(xn, w.wv, dim, dim, seq)

	// attn[c][s] in the same [dim][seq] layout the engine uses.
	attn := make([]float64, dim*seq)
	scale := 1 / math.Sqrt(float64(headDim))
	for h := range heads {
		for i := range seq {
			// Scores against every position at or before i.
			scores := make([]float64, i+1)
			maxScore := math.Inf(-1)
			for j := 0; j <= i; j++ {
				var dot float64
				for d := range headDim {
					c := h*headDim + d
					dot += q[c*seq+i] * k[c*seq+j]
				}
				scores[j] = dot * scale
				maxScore = math.Max(maxScore, scores[j])
			}
			var sum float64
			for j := range scores {
				scores[j] = math.Exp(scores[j] - maxScore)
				sum += scores[j]
			}
			for d := range headDim {
				c := h*headDim + d
				var acc float64
				for j := range scores {
					acc += scores[j] * v[c*seq+j]
				}
				attn[c*seq+i] = acc / sum
			}
		}
	}
	proj := project(attn, w.wo, dim, dim, seq)
	x2 := make([]float64, dim*seq)
	for i := range x2 {
		x2[i] = in[i] + proj[i]
	}

	// Feed forward: RMSNorm, W1, ReLU squared, W2, then the residual that the
	// generator leaves out and genAdd supplies on the engine.
	fn := rmsNorm(x2, w.rms2, dim, seq)
	h1 := project(fn, w.w1, hidden, dim, seq)
	for i, v := range h1 {
		if v < 0 {
			h1[i] = 0
		} else {
			h1[i] = v * v
		}
	}
	f := project(h1, w.w2, dim, hidden, seq)
	out := make([]float64, dim*seq)
	for i := range out {
		out[i] = x2[i] + f[i]
	}
	return out
}

// checkDiscriminating reports whether this stack, with these weights and this
// input, exercises what it claims to.
//
// It is a check on the test, not on the engine. Two ways a stack comparison can
// pass while proving nothing: attention whose scores are all equal is an average
// over positions, which a wrong head split and a missing causal mask reproduce
// exactly; and a stack whose later layers barely move the residual is a shallow
// stack wearing a depth flag, so an encoding that dropped the last layer would
// match just as well.
func checkDiscriminating(x []float32, w []*blockWeights, dim, heads, seq, hidden int) error {
	headDim := dim / heads
	cur := make([]float64, len(x))
	for i, v := range x {
		cur[i] = float64(v)
	}
	worstSpread := math.Inf(1)
	for l := range w {
		xn := rmsNorm(cur, w[l].rms1, dim, seq)
		q := project(xn, w[l].wq, dim, dim, seq)
		k := project(xn, w[l].wk, dim, dim, seq)
		scale := 1 / math.Sqrt(float64(headDim))
		lo, hi := math.Inf(1), math.Inf(-1)
		for h := range heads {
			for i := range seq {
				for j := 0; j <= i; j++ {
					var dot float64
					for d := range headDim {
						c := h*headDim + d
						dot += q[c*seq+i] * k[c*seq+j]
					}
					lo = math.Min(lo, dot*scale)
					hi = math.Max(hi, dot*scale)
				}
			}
		}
		worstSpread = math.Min(worstSpread, hi-lo)
		cur = blockReference(cur, w[l], dim, heads, seq, hidden)
	}
	fmt.Printf("  worst attention score spread over %d layers: %.3f\n", len(w), worstSpread)
	if worstSpread < 1 {
		return fmt.Errorf("some layer's softmax is nearly uniform, so its attention degenerates to an average and this program cannot tell a correct block from several wrong ones")
	}

	// Depth must matter: the last layer has to move the result by more than the
	// tolerance the comparison will use, or dropping it would go unnoticed.
	shallow, _ := stackReference(x, w[:len(w)-1], dim, heads, seq, hidden)
	full := cur
	var delta, peak float64
	for i := range full {
		delta = math.Max(delta, math.Abs(full[i]-shallow[i]))
		peak = math.Max(peak, math.Abs(full[i]))
	}
	tol := tolerance(peak)
	fmt.Printf("  the last layer moves the result by %.3f against a tolerance of %.3f\n", delta, tol)
	if delta <= tol {
		return fmt.Errorf("the last layer changes the result by less than the comparison tolerance, so a stack that dropped it would pass this test")
	}
	return nil
}

// rmsNorm normalizes each position over the channel axis and applies the
// per-channel weight, matching the generators: mean of squares over channels,
// plus epsilon, raised to -1/2.
func rmsNorm(x []float64, weight []float32, dim, seq int) []float64 {
	out := make([]float64, dim*seq)
	for s := range seq {
		var sum float64
		for c := range dim {
			v := x[c*seq+s]
			sum += v * v
		}
		inv := math.Pow(sum/float64(dim)+1e-5, -0.5)
		for c := range dim {
			out[c*seq+s] = x[c*seq+s] * inv * float64(weight[c])
		}
	}
	return out
}

// project applies an OIHW 1x1 convolution: out[o][s] = sum_i w[o][i] * x[i][s].
func project(x []float64, weight []float32, outCh, inCh, seq int) []float64 {
	out := make([]float64, outCh*seq)
	for o := range outCh {
		row := weight[o*inCh : (o+1)*inCh]
		for s := range seq {
			var acc float64
			for i := range inCh {
				acc += float64(row[i]) * x[i*seq+s]
			}
			out[o*seq+s] = acc
		}
	}
	return out
}

// tolerance returns the fp16-scale tolerance for a result of the given peak
// magnitude. Error accumulates with depth, so this is deliberately proportional
// rather than absolute; the caller prints the peak alongside it.
func tolerance(peak float64) float64 { return 0.03*peak + 0.01 }

// compare reports the worst difference against an fp16-scale tolerance. It
// prints the peak magnitude of the reference alongside, so a small difference
// against a small reference is not read as agreement.
func compare(label string, got []float32, want []float64) error {
	if len(got) != len(want) {
		return fmt.Errorf("%s: %d values, want %d", label, len(got), len(want))
	}
	var worst, peak float64
	for i := range got {
		if math.IsNaN(float64(got[i])) || math.IsInf(float64(got[i]), 0) {
			return fmt.Errorf("%s: element %d is %v; the residual stream left fp16 range", label, i, got[i])
		}
		worst = math.Max(worst, math.Abs(float64(got[i])-want[i]))
		peak = math.Max(peak, math.Abs(want[i]))
	}
	tol := tolerance(peak)
	if worst > tol {
		return fmt.Errorf("%s: worst |diff| %.4f exceeds tolerance %.4f (reference peak |%.4f|)", label, worst, tol, peak)
	}
	fmt.Printf("  %s matches the float64 reference over %d values: worst |diff| %.4f, tolerance %.4f, reference peak |%.4f|\n",
		label, len(got), worst, tol, peak)
	return nil
}

// writeAttentionModel writes an attention program and its six weight files.
func writeAttentionModel(dim, heads, seq int, w *blockWeights) (string, error) {
	rms1, err := mil.BuildVectorWeightBlob(w.rms1)
	if err != nil {
		return "", err
	}
	wq, err := mil.BuildWeightBlob(w.wq, dim, dim)
	if err != nil {
		return "", err
	}
	wk, err := mil.BuildWeightBlob(w.wk, dim, dim)
	if err != nil {
		return "", err
	}
	wv, err := mil.BuildWeightBlob(w.wv, dim, dim)
	if err != nil {
		return "", err
	}
	wo, err := mil.BuildWeightBlob(w.wo, dim, dim)
	if err != nil {
		return "", err
	}
	mask, err := mil.BuildCausalMaskBlob(seq)
	if err != nil {
		return "", err
	}
	return writeModel(mil.GenSDPAForward(dim, heads, seq), map[string][]byte{
		"rms1.bin": rms1,
		"wq.bin":   wq,
		"wk.bin":   wk,
		"wv.bin":   wv,
		"wo.bin":   wo,
		"mask.bin": mask,
	})
}

// writeFFNModel writes a feed forward program and its three weight files.
func writeFFNModel(dim, hidden, seq int, w *blockWeights) (string, error) {
	rms2, err := mil.BuildVectorWeightBlob(w.rms2)
	if err != nil {
		return "", err
	}
	w1, err := mil.BuildWeightBlob(w.w1, hidden, dim)
	if err != nil {
		return "", err
	}
	w2, err := mil.BuildWeightBlob(w.w2, dim, hidden)
	if err != nil {
		return "", err
	}
	return writeModel(mil.GenFFNForwardRMSReLU2(dim, hidden, seq), map[string][]byte{
		"rms2.bin": rms2,
		"w1.bin":   w1,
		"w2.bin":   w2,
	})
}

// writeModel writes a model directory holding text and its weight files.
func writeModel(text string, weights map[string][]byte) (string, error) {
	dir, err := os.MkdirTemp("", "e5rtstack")
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Join(dir, "weights"), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "model.mil"), []byte(text), 0o644); err != nil {
		return "", err
	}
	for name, blob := range weights {
		if err := os.WriteFile(filepath.Join(dir, "weights", name), blob, 0o644); err != nil {
			return "", err
		}
	}
	return dir, nil
}

// compileFunction compiles the model in dir for the Neural Engine and retains
// its "main" function.
//
// The function is not the operation. Functions are cheap to hold — forty of
// them coexist without complaint — and operations are the scarce resource, so
// every program is compiled once here and turned into an operation only for the
// phase that runs it.
func compileFunction(lib *e5rt.Lib, dir string) (uintptr, error) {
	config, err := lib.CompilerConfigOptionsCreate()
	if err != nil {
		return 0, err
	}
	defer lib.CompilerConfigOptionsRelease(config)
	if err := lib.CompilerConfigOptionsSetCacheBundleLocation(config, dir); err != nil {
		return 0, err
	}
	compiler, err := lib.CompilerCreateWithConfig(config)
	if err != nil {
		return 0, err
	}
	defer lib.CompilerRelease(compiler)
	options, err := lib.CompilerOptionsCreate()
	if err != nil {
		return 0, err
	}
	defer lib.CompilerOptionsRelease(options)
	if err := lib.CompilerOptionsSetComputeDeviceTypesMask(options, e5rt.ComputeDeviceANE); err != nil {
		return 0, err
	}
	library, err := lib.CompilerCompile(compiler, filepath.Join(dir, "model.mil"), options)
	if err != nil {
		return 0, err
	}
	return lib.ProgramLibraryRetainProgramFunction(library, "main")
}

// newOperation builds an executable operation for a compiled function. This is
// what counts against maxLiveOps.
func newOperation(lib *e5rt.Lib, function uintptr) (uintptr, error) {
	opOptions, err := lib.PrecompiledComputeOpOptionsCreate(function)
	if err != nil {
		return 0, err
	}
	defer lib.PrecompiledComputeOpOptionsRelease(opOptions)
	if err := lib.PrecompiledComputeOpOptionsSetOperationName(opOptions, "main"); err != nil {
		return 0, err
	}
	return lib.OperationCreatePrecompiled(opOptions)
}

// allocBuffer allocates a CPU-visible buffer object and returns it with its
// host address.
func allocBuffer(lib *e5rt.Lib, nbytes int) (uintptr, uintptr, error) {
	buf, err := lib.BufferObjectAlloc(uintptr(max((nbytes+63)&^63, 64)), 0)
	if err != nil {
		return 0, 0, err
	}
	ptr, err := lib.BufferObjectGetDataPtr(buf)
	if err != nil {
		return 0, 0, err
	}
	return buf, ptr, nil
}

// bind binds an already-allocated buffer object to a named port. Binding one
// buffer to two ports of two programs is what chains a layer to the next.
func bind(lib *e5rt.Lib, op uintptr, name string, buf uintptr, input bool) error {
	var port uintptr
	var err error
	if input {
		port, err = lib.OperationRetainInputPort(op, name)
	} else {
		port, err = lib.OperationRetainOutputPort(op, name)
	}
	if err != nil {
		return err
	}
	defer lib.IOPortRelease(port)
	return lib.IOPortBindBufferObject(port, buf)
}

// reportBackend prints which backend the compiler chose, read from the
// <function>_<backend> directories it leaves in the cache location. The device
// mask is a permission and not a placement, so this is the only local evidence
// that the work was put on the engine.
func reportBackend(cacheDir, label string) {
	seen := map[string]bool{}
	filepath.WalkDir(cacheDir, func(path string, d os.DirEntry, err error) error {
		if err != nil || !d.IsDir() || filepath.Base(filepath.Dir(path)) != "main" {
			return nil
		}
		if suffix, ok := strings.CutPrefix(d.Name(), "main_"); ok {
			seen[suffix] = true
		}
		return nil
	})
	if len(seen) == 0 {
		fmt.Printf("  backend for %s: UNKNOWN (no main_* directory in the compiled bundle)\n", label)
		return
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	fmt.Printf("  backend for %s: the compiler emitted %v\n", label, names)
}

func writeFP16(dst uintptr, src []float32) {
	out := fp16SliceAt(dst, len(src))
	for i, v := range src {
		out[i] = ane.Float32ToFP16(v)
	}
}

func readFP16(src uintptr, n int) []float32 {
	in := fp16SliceAt(src, n)
	out := make([]float32, n)
	for i, v := range in {
		out[i] = ane.FP16ToFloat32(v)
	}
	return out
}
